RAPID_Wapiti_project

Last edited 20260825 by Robby Jost

USE:
1. Initial cleaning and formatting of Master Sample Data worksheet.
2. Calculation of TSS parameters
3. Merging of field data with TSS, DOC, ions, and nutrients via the sample_num.


The output csv files are saved here: '/content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC'

# Start up workflow:
load libraries -> connect to google drive -> load field data entry spreadsheet via url to the Google Sheet "wapiti_fire_water_sample_data" -> define functions.

# Cleaning operations:
remove extra columns, specify columns that are string, numeric, & datetime datatypes, declare no data values as -9999, format date & time columns.

# Dataset descriptions:
1. count and percentage of nodata (-9999) values in each column.
2. Field data rows grouped by site and sample date.

# Create parameter specific dataframes

# export dataframes
CURRENT_OUTPUTS:
1. *wapiti_water_data_entry_sample_data_CLEANED.csv*
  A csv file with cleaned original columns from field entry spreadsheet.
2.  *wapiti_water_TSS_sample_data_CLEANED.csv*
  A csv file with suspended sediment related columns.
3. *wapiti_water_DOC_sample_data_CLEANED.csv*
  A csv file with Dissolved organic carbon related columns
4. *wapiti_water_ALL_sample_data_CLEANED.csv*
  A csv file with newly derived TSS and DOC columns
# Inprogress
concentration data, calculated Detection Limits, and standard deviations.
Addition of Ions and Nurtients datasets when these get processsed.
---
### Developer notes on new features to add
Create a function that scans the output csv files and returns the most recent date of samples collected and the sample numbers.
Create another function that scans the Shimazu, nutrients (AA5600?) and IC folder in the Bergstrom_Lab drive scraping the latest file of processed data and the max sample number in the respective files.
Create a third function (or refactor the current merge function) to add the new batch of data to the ALL_CLEANED.csv file.

## **Import packages**

In [1]:
import datetime
import glob
import os
import gspread
import numpy as np
import pandas as pd
from google.colab import auth
from google.auth import default
from google.colab import drive

# Authenticate Colab and give access to your drive

In [2]:
# Running this cell will bring multiple prompts to access your drive. Accept and continue

# connect to your google drive (needed for saving files at the end)
drive.mount('/content/drive')
# Authenticate with Google Colab to access spreadsheets
auth.authenticate_user()
creds, _ = default()

gc = gspread.authorize(creds)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# out path to save files in wapiti shared drive
out_path = '/content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC'

### Load Data from Google Sheet

In [4]:
# path to wapiti shared drive
root_path = '/content/drive/Shareddrives/RAPID_Wapiti_project'
# read in the spreadsheet
url = 'https://docs.google.com/spreadsheets/d/1bF-Za-wf4RdvGU84KIQ1ZHTNx46QItcQgyukLzkRKAM'
try:
    spreadsheet = gc.open_by_url(url)
    print(f'Successfully opened spreadsheet by url: {url}')
except gspread.exceptions.SpreadsheetNotFound:
    print(f"Spreadsheet '{url}' not found by url.")
    spreadsheet = None

Successfully opened spreadsheet by url: https://docs.google.com/spreadsheets/d/1bF-Za-wf4RdvGU84KIQ1ZHTNx46QItcQgyukLzkRKAM

In [5]:
if spreadsheet:
    # select the first worksheet "Master Sample Data"
    worksheet = spreadsheet.sheet1
    # Get all values from the worksheet and create a DataFrame
    records = worksheet.get_all_values()

    df = pd.DataFrame(records)

    print("Data loaded successfully into a pandas DataFrame.")
    #display(df.head())
else:
    print("Could not load data due to spreadsheet not being found or an invalid ID.")

Data loaded successfully into a pandas DataFrame.

## This section formats and cleans some artifacts in the data_entry spreadsheet that would otherwise mess with data analysis

In [6]:
header_row = df.iloc[0]
header_row = [val if val != '' else f"unamed_{i}" for i, val in enumerate(header_row)]
# set new headers and drop the first row
df.columns = header_row
df = df[1:].reset_index(drop=True)
df = df.replace(['-9999', -9999], np.nan)

In [7]:
# Identify all columns that contain 'Unnamed' (case-insensitive check)
unnamed_cols = [col for col in df.columns if 'unamed' in str(col).lower()]

# Drop the unnamed columns from your DataFrame
df.drop(columns=unnamed_cols, inplace=True)

In [8]:
# Define the columns you want to keep as strings/objects datatypes
exclude_cols = {'site','date', 'time','bottles_collected','tin_num', 'notes'}

for col in df.columns:
    if col not in exclude_cols:
        # Convert the rest to numeric, coercing errors to NaN
        df[col] = pd.to_numeric(df[col], errors='coerce')
    else:
        # confirms the skipped columns that don't get converted
        print(f"Skipping numeric conversion for: {col}")

Skipping numeric conversion for: site
Skipping numeric conversion for: date
Skipping numeric conversion for: time
Skipping numeric conversion for: bottles_collected
Skipping numeric conversion for: tin_num
Skipping numeric conversion for: notes

In [9]:
# standardize datetime columns
# Convert Date (Standardizing to YYYY-MM-DD for Pandas internal use)
df['date'] = pd.to_datetime(df['date'], format='%m/%d/%y', errors='coerce')

# make sure everything is a string then remove colons and whitespace
df['time'] = df['time'].astype(str).str.replace(':', '').str.strip()


# re-insert the colon so it's "HH:MM"
df['time'] = df['time'].str.zfill(4) # Ensures "900" becomes "0900"
df['time'] = df['time'].str[:2] + ':' + df['time'].str[2:]

# Convert to a proper time object for calculations
df['time_cleaned'] = pd.to_datetime(df['time'], format='%H:%M', errors='coerce').dt.time

# Display to verify
print(df[['date', 'time', 'time_cleaned']].head())

        date   time time_cleaned
0 2024-10-11  15:00     15:00:00
1 2024-10-11  11:34     11:34:00
2 2024-10-11  14:15     14:15:00
3 2024-10-11  15:27     15:27:00
4 2024-10-12  10:20     10:20:00

# Calculate TSS columns

In [10]:

# columns to use for total suspended solids
tss_cols = [
    'sample_num', 'date','site', 'tin_num','tin_filter_weight', 'bottle_tare',
    'bottle_full', 'tin_filter_sed_weight', 'tin_filter_sed_ashed_weight'
]
tss_df = df[tss_cols].copy()

In [11]:
# convert from g to mg
tss_df['sed_weight_mg'] = (tss_df['tin_filter_sed_weight'] - tss_df['tin_filter_weight']) * 1000

tss_df['TSS_conc_mgL-1'] = (tss_df['bottle_full'] - tss_df['bottle_tare']) / 1000

tss_df["susp_solids_mg"] = (tss_df['tin_filter_sed_weight'] - tss_df['tin_filter_weight']) * 1000

tss_df["susp_sed_mg"] = (tss_df['tin_filter_sed_weight'] - tss_df['tin_filter_sed_ashed_weight']) * 1000

#  Shimadzu Datasets
1. Merge the processed TOC & NPOC csv files into a single dataframe.
2. Remove the 'blank', 'check1', 'check2' row. Are those important?
3. check for duplicates and remove

In [12]:
def clean_toc_data(file_path:str) -> pd.DataFrame:
    """
    Read all CSV files in a directory into a single DataFrame and clean it up.

    Args:
        file_path (str): The path to the directory containing the CSV files.

    Returns:
        pd.DataFrame: A DataFrame containing the cleaned TOC data.
    """

    # glob the spreadsheets
    csv_files = glob.glob(file_path)
    # read csv file into dataframe
    toc_processed_df = pd.concat([pd.read_csv(file, header=0) for file in csv_files], ignore_index=True)
    toc_processed_df.replace(['NA', -9999], np.nan, inplace=True)
    # copy the dataframe with the relevant columns
    toc_processed_cols = ['SampleNum', 'SiteName', 'TOC_conc', 'NPOC_conc']
    toc_df = toc_processed_df[toc_processed_cols].copy()
    # replace the column names to match the field entry spreadsheet
    toc_df.columns = ['sample_num', 'site', 'TOC_conc', 'NPOC_conc']
    # Drop the rows with NA values
    toc_df.dropna(axis=0, inplace=True)

    toc_df.sort_values(by='sample_num', inplace=True)

    # dropping the second duplicate - temporary measure
    toc_df_cleaned = toc_df.drop_duplicates(subset=['sample_num'], keep='first')

    return toc_df_cleaned

In [13]:
# file path to TOC data
toc_path = '/content/drive/Shareddrives/Watershed_Biogeochemistry_Lab/Projects/ShimadzuTOC/ProcessedData'
fname_string = '*_processedData*.csv'

In [14]:
if os.path.exists(toc_path):
  print(f"path found, cleaning TOC data")
  toc_df = clean_toc_data(os.path.join(toc_path, fname_string))
else:
  print(f"{toc_path} not found")

path found, cleaning TOC data

# Merge datasets

In [15]:
def merge_new_columns(
    primary_df: pd.DataFrame,
    incoming_df: pd.DataFrame,
    join_key: str = 'sample_num'
) -> pd.DataFrame:
    """Joins only the unique columns from an incoming DataFrame into a primary DataFrame.

    This function isolates columns in `incoming_df` that do not already exist in
    `primary_df`, filters out duplicate rows based on the `join_key` to prevent
    row multiplication, and performs a left merge. This prevents the creation
    of redundant column suffixes (e.g., '_x', '_y') for columns like site names
    that exist across multiple uncleaned datasets.

    Args:
        primary_df: The primary DataFrame acting as the left table.
            This dataframe retains all of its original columns and rows.
        incoming_df: The secondary DataFrame acting as the right table
            from which new, unique columns will be extracted.
        join_key: The column name to join the two dataframes on.
            Defaults to 'sample_num'.

    Returns:
        A new DataFrame containing all original data from `primary_df`
        augmented with the unique columns from `incoming_df`.

    Raises:
        KeyError: If the `join_key` is missing from either `primary_df` or
            `incoming_df`.
    """
    # 1. Get the sets of columns
    primary_cols = set(primary_df.columns)
    incoming_cols = set(incoming_df.columns)

    # 2. Find columns in incoming_df that are NOT in primary_df
    unique_new_cols = incoming_cols - primary_cols

    # 3. We MUST keep the join_key so we can actually perform the merge
    cols_to_keep = list(unique_new_cols) + [join_key]

    # 4. Filter the incoming dataframe to only those columns
    incoming_filtered = incoming_df[cols_to_keep]

    # 5. NEW: Clean up any duplicate join keys in the incoming data (our previous fix!)
    incoming_filtered = incoming_filtered.drop_duplicates(subset=[join_key], keep='first')

    # 6. Merge cleanly without worrying about _x or _y column suffixes
    refactored_df = pd.merge(primary_df, incoming_filtered, on=join_key, how='left')

    return refactored_df

In [16]:
# Start with your primary master df (df)
final_df = df.copy()

# Dynamically pull unique columns from tss_df
final_df = merge_new_columns(final_df, tss_df)

# Dynamically pull unique columns from toc_df
final_df = merge_new_columns(final_df, toc_df)

# guardrail to ensure no rows were accidentally multiplied
assert len(final_df) == len(df), f"Row count changed from {len(df)} to {len(final_df)}!"
print(f"Merge Complete! Final shape: {final_df.shape}. Original df shape: {df.shape}")

Merge Complete! Final shape: (616, 25). Original df shape: (616, 19)

# This section provides different descriptions of the data entry spreadsheet

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sample_num                   616 non-null    int64
 1   site                         616 non-null    object
 2   date                         611 non-null    datetime64[ns]
 3   time                         616 non-null    object
 4   field_temp                   560 non-null    float64
 5   field_EC                     605 non-null    float64
 6   lab_pH                       602 non-null    float64
 7   lab_EC                       316 non-null    float64
 8   bottles_collected            610 non-null    object
 9   bottle_site_num              317 non-null    float64
 10  tin_num                      602 non-null    object
 11  tin_weight                   602 non-null    float64
 12  tin_filter_weight            602 non-null    float64
 13  bottle_tare                  602 non-null    float64
 14  bottle_full                  597 non-null    float64
 15  tin_filter_sed_weight        595 non-null    float64
 16  tin_filter_sed_ashed_weight  597 non-null    float64
 17  notes                        616 non-null    object
 18  time_cleaned                 611 non-null    object
dtypes: datetime64[ns](1), float64(11), int64(1), object(6)
memory usage: 91.6+ KB

In [18]:
# Calculate the count and percentage of missing data per column
missing_data = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    '% Missing': (df.isnull().sum() / len(df)) * 100
})

print(missing_data.sort_values(by='% Missing', ascending=False))

                             Missing Values  % Missing
lab_EC                                  300  48.701299
bottle_site_num                         299  48.538961
field_temp                               56   9.090909
tin_filter_sed_weight                    21   3.409091
bottle_full                              19   3.084416
tin_filter_sed_ashed_weight              19   3.084416
tin_weight                               14   2.272727
bottle_tare                              14   2.272727
tin_filter_weight                        14   2.272727
tin_num                                  14   2.272727
lab_pH                                   14   2.272727
field_EC                                 11   1.785714
bottles_collected                         6   0.974026
date                                      5   0.811688
time_cleaned                              5   0.811688
site                                      0   0.000000
sample_num                                0   0.000000
time                                      0   0.000000
notes                                     0   0.000000

## Groupby sample date

In [19]:
# see all the records for each date
for date, group in df.groupby("date"):
    print(f"--- Data for Site: {date} ---")
    display(group) # Shows the first 5 rows for each site
    print("\n")

--- Data for Site: 2024-10-11 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
0,1,Warm_Sp,2024-10-11,15:00,NaN,NaN,8.39,NaN,"TSS, Nuts",NaN,19,1.075,1.208,88.57,1135.00,1.208,1.205,,15:00:00
1,2,SH_Cr,2024-10-11,11:34,NaN,NaN,7.91,NaN,"TSS, Nuts",NaN,26,1.083,1.214,88.54,1133.87,1.234,NaN,,11:34:00
2,3,Canyon_Cr_SFP,2024-10-11,14:15,NaN,NaN,7.97,NaN,"TSS, Nuts",NaN,25,1.098,1.232,87.50,1117.52,1.241,1.236,,14:15:00
3,4,BJ_Cr,2024-10-11,15:27,NaN,NaN,7.79,NaN,"TSS, Nuts",NaN,21,1.080,1.213,87.43,1080.30,1.238,NaN,,15:27:00

--- Data for Site: 2024-10-12 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
4,5,SFP_Alder_Cr,2024-10-12,10:20,12.0,107.0,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,16,1.0950,1.228,88.35,1159.42,1.231,1.22800,,10:20:00
5,6,SFP_DW,2024-10-12,11:15,9.8,103.0,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.0600,1.195,88.49,1156.48,1.196,1.19400,,11:15:00
6,7,SFP_BJ,2024-10-12,12:30,9.4,98.4,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Glass vial broke, sample gone",12:30:00
7,8,BJ_Cr,2024-10-12,12:30,8.0,54.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,12:30:00
8,9,Warm_Sp,2024-10-12,13:15,13.0,114.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,13:15:00
9,10,SFP_Chap,2024-10-12,13:30,10.5,89.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Glass vial broke, sample gone",13:30:00
10,11,Chapman_Cr,2024-10-12,13:30,8.7,110.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,13:30:00
11,12,SFP_Wolf_Cr,2024-10-12,14:45,15.4,84.2,8.22,NaN,"TSS, Nuts, DOC,Alk",NaN,18,1.1110,1.243,88.23,1153.16,1.244,1.24300,,14:45:00
12,13,Fox_Cr,2024-10-12,15:00,11.5,185.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,15:00:00
13,14,Canyon_Cr_SFP,2024-10-12,15:45,12.1,103.7,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,15:45:00
14,15,SFP_Canyon_Cr,2024-10-12,16:00,11.8,83.7,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.1100,1.246,88.36,1152.62,1.249,1.24800,,16:00:00
15,16,SH_Cr,2024-10-12,16:30,13.0,98.3,8.05,NaN,"TSS, Nuts, DOC, Alk",NaN,23,1.1103,1.237,87.63,1147.85,1.240,1.23791,,16:30:00

--- Data for Site: 2024-10-13 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
16,17,SH_Cr,2024-10-13,16:00,13.3,100.2,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,24,1.065,1.199,88.81,1141.80,1.218,NaN,"Glass vial broke, sample gone",16:00:00
17,18,Camp_Cr,2024-10-13,16:30,12.4,84.6,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.091,1.226,88.92,1139.68,1.250,1.248,,16:30:00

--- Data for Site: 2024-10-19 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
18,19,SFP_Alder_Cr,2024-10-19,09:45,7.1,106.8,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.080,1.210,87.36,1155.33,1.217,1.21300,,09:45:00
19,20,SFP_DW,2024-10-19,10:30,5.2,103.2,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.076,1.212,102.42,1123.30,1.215,1.21300,Glass bottle cracked but still held some water...,10:30:00
20,21,BJ_Cr,2024-10-19,11:00,4.2,54.1,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.090,1.230,101.06,1082.96,1.246,1.23700,"Glass vial broke, sample gone",11:00:00
21,22,Warm_Sp,2024-10-19,11:40,8.2,115.2,8.27,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.086,1.217,100.99,1135.94,1.214,1.21200,"Glass vial broke, sample gone",11:40:00
22,23,SFP_Chap,2024-10-19,12:00,5.5,90.4,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,10,1.083,1.212,103.19,1121.86,1.215,1.21400,"Glass vial broke, sample gone",12:00:00
23,24,Fox_Cr,2024-10-19,12:20,6.5,187.4,7.64,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.062,1.193,101.27,1153.79,1.194,1.19200,"Glass vial broke, sample gone",12:20:00
24,25,SFP_Wolf_Cr,2024-10-19,12:40,6.8,91.2,8.15,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.063,1.193,101.20,1140.83,1.195,1.19100,"Glass vial broke, sample gone",12:40:00
25,26,Canyon_Cr_SFP,2024-10-19,13:00,6.9,108.9,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.085,1.215,101.63,1141.61,1.219,1.21700,Glass bottle cracked but still held some water...,13:00:00
26,27,SFP_Canyon_Cr,2024-10-19,13:15,7.3,81.7,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.085,1.214,103.07,1130.51,1.217,1.21600,,13:15:00
27,28,Camp_Cr,2024-10-19,13:45,8.1,79.8,7.97,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.107,1.237,101.39,1113.49,1.241,1.23900,"Glass vial broke, sample gone",13:45:00
28,29,SH_Cr,2024-10-19,14:10,8.1,89.5,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.067,1.196,101.43,1001.98,1.214,1.21100,"Glass vial broke, sample gone",14:10:00
29,30,SFP_Wapiti,2024-10-19,15:00,7.6,78.2,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,2,1.150,1.270,101.07,1152.46,1.229,1.22829,"Glass vial broke, sample gone",15:00:00
30,31,Avalanche_Cr,2024-10-19,17:40,9.6,130.5,8.13,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.100,1.230,101.45,1110.23,1.240,1.23700,,17:40:00
31,32,Canyon_cr_avalanche (HP_old),2024-10-19,18:00,7.9,101.6,8.06,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.080,1.210,101.21,1153.17,1.223,1.22000,"Glass vial broke, sample gone",18:00:00
32,33,SFP_BJ,2024-10-19,18:20,9.6,97.8,8.13,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.110,1.230,101.40,1143.84,1.234,1.23000,"Glass vial broke, sample gone",18:20:00

--- Data for Site: 2024-11-03 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
33,34,SFP_Wapiti,2024-11-03,10:30,5.1,75.1,7.82,NaN,"TSS, Nuts, DOC, Alk",NaN,27,1.101,1.227,88.73,1142.95,1.2312,1.22705,,10:30:00
34,35,Camp_Cr,2024-11-03,11:00,2.8,77.0,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,28,1.108,1.232,88.33,1129.93,1.2364,1.23461,,11:00:00
35,36,SH_Cr,2024-11-03,11:10,1.7,82.1,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,29,1.117,1.243,88.79,1120.02,1.2546,1.24751,,11:10:00
36,37,HP,2024-11-03,12:30,3.0,96.6,7.74,NaN,"TSS, Nuts, DOC, Alk",NaN,30,1.096,1.220,88.64,1136.18,1.2240,1.22213,,12:30:00
37,38,Avalanche_Cr,2024-11-03,13:15,4.0,123.2,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,31,1.094,1.217,87.64,1123.76,1.2695,1.26391,,13:15:00
38,39,Canyon_cr_avalanche (HP_old),2024-11-03,13:20,4.0,95.6,7.84,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.098,1.211,88.13,1139.86,1.2202,NaN,,13:20:00
39,40,GO_Cr,2024-11-03,13:30,3.7,132.8,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,33,1.106,1.237,88.55,1055.63,1.2436,1.23988,,13:30:00
40,41,Fox_Cr,2024-11-03,14:00,4.5,173.6,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,34,1.065,1.197,88.55,1148.14,1.2019,1.19760,,14:00:00
41,42,SFP_Wolf_Cr,2024-11-03,14:40,5.4,86.5,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.101,1.230,88.71,1136.85,1.2356,1.23254,,14:40:00
42,43,Canyon_Cr_SFP,2024-11-03,15:00,4.1,103.1,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,36,1.078,1.209,87.69,1078.19,1.2155,1.21401,,15:00:00
43,44,SFP_Canyon_Cr,2024-11-03,15:10,5.7,78.4,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,42,1.069,1.193,101.22,1065.01,1.1993,1.19448,,15:10:00

--- Data for Site: 2024-11-04 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
44,45,SFP_Chap,2024-11-04,13:00,5.1,86.7,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,37,1.080,1.210,88.64,1139.50,1.2188,1.21068,,13:00:00
45,46,Chapman_Cr,2024-11-04,13:20,5.1,105.9,8.03,NaN,"TSS, Nuts, DOC, Alk",NaN,38,1.095,1.227,88.42,1091.96,1.2360,1.22905,,13:20:00
46,47,Warm_Sp,2024-11-04,13:40,8.2,109.4,8.14,NaN,"TSS, Nuts, DOC, Alk",NaN,39,1.101,1.229,87.87,1120.70,1.2360,1.23234,,13:40:00
47,48,SFP_BJ,2024-11-04,14:00,5.8,93.0,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,40,1.104,1.237,88.01,1105.42,1.2452,1.23789,,14:00:00
48,49,BJ_Cr,2024-11-04,14:20,4.3,52.3,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,41,1.062,1.186,88.58,1075.83,1.1922,1.18744,,14:20:00
49,50,SFP_DW,2024-11-04,16:15,4.9,99.0,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,43,1.096,1.223,101.44,1091.72,1.2306,1.22174,,16:15:00

--- Data for Site: 2024-11-09 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
50,51,SFP_Alder_Cr,2024-11-09,08:30,NaN,111.9,8.41,NaN,"TSS, Nuts, DOC, Alk",NaN,44,1.092,1.214,88.07,1115.80,1.21681,1.21594,,08:30:00
51,52,SFP_DW,2024-11-09,09:40,NaN,104.8,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,45,1.099,1.223,88.79,1115.61,1.22771,1.22673,,09:40:00
52,53,BJ_Cr,2024-11-09,10:15,NaN,61.6,8.12,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.201,1.223,88.56,1119.97,1.22534,1.22395,,10:15:00
53,54,SFP_BJ,2024-11-09,10:30,NaN,101.5,8.22,NaN,"TSS, Nuts, DOC, Alk",NaN,47,1.095,1.218,88.11,1121.83,1.22115,1.22053,,10:30:00
54,55,Warm_Sp,2024-11-09,10:35,NaN,116.1,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,48,1.098,1.222,88.59,1122.91,1.22274,1.22237,,10:35:00
55,56,SFP_Chap,2024-11-09,10:45,NaN,95.7,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,49,1.088,1.210,88.12,1130.00,1.21255,1.21184,,10:45:00
56,57,HP,2024-11-09,11:00,NaN,100.3,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.088,1.210,88.73,1133.81,1.21524,1.21425,,11:00:00
57,58,Avalanche_Cr,2024-11-09,11:15,NaN,127.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.062,1.185,88.77,1125.45,1.18642,1.18574,,11:15:00
58,59,GO_Cr,2024-11-09,11:30,NaN,136.5,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,52,1.055,1.179,88.75,939.39,1.18053,1.17979,,11:30:00
59,60,Fox_Cr,2024-11-09,11:40,NaN,175.2,8.51,NaN,"Nuts, DOC, Alk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TSS bottle leaked in cooler,11:40:00
60,61,SFP_Wolf_Cr,2024-11-09,11:50,NaN,93.3,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,54,1.079,1.204,88.75,1143.00,1.20588,1.20511,,11:50:00
61,62,Canyon_Cr_SFP,2024-11-09,12:00,NaN,107.8,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.095,1.218,87.69,1129.60,1.22278,1.22189,,12:00:00
62,63,SFP_Canyon_Cr,2024-11-09,12:10,NaN,82.1,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,53,1.083,1.211,88.91,1144.09,1.21080,1.21022,,12:10:00
63,64,Camp_Cr,2024-11-09,12:20,NaN,79.6,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,56,1.088,1.213,88.95,1125.12,1.21643,1.21510,,12:20:00
64,65,SH_Cr,2024-11-09,12:30,NaN,80.5,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,57,1.074,1.204,88.59,1067.57,1.20766,1.20682,,12:30:00
65,66,SFP_Wapiti,2024-11-09,12:40,NaN,86.6,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.083,1.207,88.31,1117.76,1.21005,1.20902,,12:40:00
66,67,Wapiti_Cr,2024-11-09,16:00,NaN,87.5,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,59,1.092,1.213,88.08,1034.73,1.21914,1.21791,,16:00:00

--- Data for Site: 2024-11-24 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
67,68,SFP_Alder_Cr,2024-11-24,09:15,NaN,94.3,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10401,1.22797,88.51,1143.17,1.25297,1.24823,,09:15:00
68,69,SFP_DW,2024-11-24,09:54,NaN,115.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11079,1.23411,88.35,1137.70,1.24575,1.24357,,09:54:00
69,70,BJ_Cr,2024-11-24,10:53,NaN,70.3,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08887,1.21197,88.25,1130.70,1.21413,1.21233,,10:53:00
70,71,SFP_BJ,2024-11-24,16:00,NaN,105.1,7.82,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06384,1.18838,87.79,1108.58,1.19682,1.19571,Bottle says SFP at warm springs,16:00:00
71,72,Warm_Sp,2024-11-24,11:07,NaN,112.4,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07599,1.19937,88.32,1138.31,1.24092,1.23873,,11:07:00
72,73,SFP_Chap,2024-11-24,11:20,NaN,91.0,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10635,1.22996,88.68,1136.98,1.23372,1.23261,,11:20:00
73,74,HP,2024-11-24,11:42,NaN,109.9,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10604,1.23191,87.83,1128.19,1.23412,1.23288,,11:42:00
74,75,Avalanche_Cr,2024-11-24,11:55,NaN,126.9,8.11,NaN,"TSS, Nuts, DOC, Alk",NaN,16,1.09612,1.21856,88.49,1124.38,1.22548,1.22249,,11:55:00
75,76,GO_Cr,2024-11-24,12:11,NaN,135.9,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09748,1.22225,88.49,837.95,1.22509,1.22367,TSS bottle not completely filled,12:11:00
76,77,Fox_Cr,2024-11-24,13:30,NaN,188.9,8.03,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08234,1.20739,87.46,1127.14,1.20993,1.20851,,13:30:00
77,78,SFP_Wolf_Cr,2024-11-24,13:14,NaN,88.4,7.86,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06125,1.18578,88.33,1126.42,1.18904,1.18784,,13:14:00
78,79,Canyon_Cr_SFP,2024-11-24,14:05,NaN,108.1,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09381,1.21783,88.40,1137.76,1.22348,1.22174,,14:05:00
79,80,SFP_Canyon_Cr,2024-11-24,14:15,NaN,77.5,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08550,1.20881,88.46,1137.13,1.21528,1.21436,,14:15:00
80,81,Camp_Cr,2024-11-24,15:20,NaN,85.3,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10358,1.22630,87.42,1110.77,1.23685,1.23572,,15:20:00
81,82,SH_Cr,2024-11-24,15:11,NaN,79.4,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06299,1.18718,887.59,1126.84,1.23012,1.22715,,15:11:00

--- Data for Site: 2025-01-17 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
82,83,SFP_Alder_Cr,2025-01-17,07:44,0.2,25.5,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09747,1.227600,88.43,1124.32,1.22865,1.22795,Lab(omega) EC = 127.5 @7.8C,07:44:00
83,84,SFP_DW,2025-01-17,08:22,0.3,5.3,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06382,1.188810,88.36,1124.99,1.18921,1.18879,Lab(omega) EC = 120.8 @8.0C,08:22:00
84,85,BJ_Cr,2025-01-17,09:13,1.1,52.2,7.21,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06293,1.189689,87.46,1034.02,1.18888,1.18744,Lab(omega) EC = 64.67 @7.8C,09:13:00
85,86,SFP_BJ,2025-01-17,09:58,1.2,92.5,7.14,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06119,1.192060,88.47,1103.92,1.19452,1.19363,Lab(omega) EC = 114.5 @8.3C,09:58:00
86,87,Warm_Sp,2025-01-17,10:35,5.3,107.7,7.44,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10076,1.231950,87.44,1123.14,1.23693,1.23622,Lab(omega) EC = 133.9 @8.0C,10:35:00
87,88,SFP_Chap,2025-01-17,16:04,NaN,NaN,7.03,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07589,1.206600,88.35,715.64,1.21031,1.20928,Lab(omega) EC = 101.6 @11.9C,16:04:00
88,89,HP,2025-01-17,11:25,1.3,92.4,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09364,1.224960,88.71,1121.81,1.22545,1.22479,Lab(omega) EC = 114.3 @8.5C,11:25:00
89,90,Avalanche_Cr,2025-01-17,11:45,1.7,116.8,7.38,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06185,1.193120,88.34,1063.49,1.19561,1.19490,Lab(omega) EC = 145.3 @7.2C,11:45:00
90,91,GO_Cr,2025-01-17,11:57,1.5,121.0,7.06,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10344,1.235790,87.63,824.64,1.24951,1.24705,Lab(omega) EC = 130.9 @9.2C,11:57:00
91,92,Fox_Cr,2025-01-17,15:21,1.2,160.4,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08876,1.218640,88.46,1034.95,1.23582,1.22010,Lab EC(omega) = 199.8 @8.9C,15:21:00
92,93,SFP_Wolf_Cr,2025-01-17,15:34,1.3,84.5,7.47,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08231,1.212310,88.07,920.59,1.21761,1.21658,Lab(omega) EC = 104.4 @7.6C,15:34:00
93,94,Canyon_Cr_SFP,2025-01-17,14:32,1.7,100.5,7.34,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08727,1.217280,87.82,1121.66,1.22062,1.21937,Lab(omega) EC = 124.5 @9.2C,14:32:00
94,95,SFP_Canyon_Cr,2025-01-17,14:19,1.9,75.4,7.50,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08280,1.213340,88.36,1126.74,1.21895,1.21649,Lab(omega) EC = 93.70 @7.9C,14:19:00
95,96,Camp_Cr,2025-01-17,13:52,1.4,79.5,7.05,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11069,1.241280,88.54,634.51,1.24499,1.24419,Lab(omega) EC = 98.33 @11.9C,13:52:00
96,97,SH_Cr,2025-01-17,13:41,1.3,65.0,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10626,1.237230,88.23,1053.98,1.41141,1.40853,"Lab(metrohm) EC = 81.43 @8.6C, **used both met...",13:41:00

--- Data for Site: 2025-01-30 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
97,98,SFP_Alder_Cr,2025-01-30,16:24,0.5,109.2,8.11,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06184,1.19256,87.45,1158.5,1.20222,1.20111,Lab(metrohm) EC = 111.5 @7.5C,16:24:00
98,99,SFP_DW,2025-01-30,15:50,0.5,92.2,8.04,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10346,1.23338,88.52,1161.6,1.23482,1.23414,Lab(metrohm) EC = 106.3 @4.7C,15:50:00
99,100,BJ_Cr,2025-01-30,15:00,0.8,49.7,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06124,1.19253,88.37,511.1,1.19471,1.19341,"Had to break through ice for sample,Lab(metroh...",15:00:00
100,101,SFP_BJ,2025-01-30,14:10,NaN,98.8,7.77,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09178,1.22851,87.62,1108.6,1.23037,1.23037,Lab(metrohm) EC = 103.0 @4.4C,14:10:00
101,102,Warm_Sp,2025-01-30,14:06,6.3,98.7,7.97,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10623,1.23845,88.33,1168.1,1.24267,1.24186,Lab(metrohm) EC = 125.7 @6.4C,14:06:00
102,103,SFP_Chap,2025-01-30,13:37,1.8,91.2,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10059,1.23101,87.83,920.0,1.23209,1.23167,Lab(metrohm) EC = 95.39 @5.1C,13:37:00
103,104,HP,2025-01-30,08:51,3.7,98.6,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08219,1.21282,88.71,1103.5,1.21434,1.21434,Lab(metrohm) EC = 101.0 @7.5C,08:51:00
104,105,Avalanche_Cr,2025-01-30,09:08,0.6,124.3,7.75,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11063,1.24091,88.43,644.8,1.24326,1.24241,Lab(metrohm) EC = 127.8 @5.9C,09:08:00
106,107,Fox_Cr,2025-01-30,12:50,0.9,88.0,7.73,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08727,1.21984,88.32,1138.2,1.22171,1.22084,"Had to break through ice for sample,Lab(metroh...",12:50:00
107,108,SFP_Wolf_Cr,2025-01-30,13:05,0.6,96.4,7.74,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07592,1.20942,88.49,1162.2,1.23606,1.23278,Lab(metrohm) EC = 94.81 @7.8C,13:05:00
108,109,Canyon_Cr_SFP,2025-01-30,10:27,0.3,68.3,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09359,1.22525,88.48,1108.0,1.22912,1.22815,Lab(metrohm) EC = 113.6 @5.2C,10:27:00
109,110,SFP_Canyon_Cr,2025-01-30,10:35,0.3,48.2,8.14,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06288,1.19365,87.46,1115.2,1.19501,1.19404,Lab(metrohm) EC = 88.88 @5.3C,10:35:00
110,111,Camp_Cr,2025-01-30,11:35,1.0,81.9,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06383,1.19489,88.10,1093.6,1.19737,1.19661,Lab(metrohm) EC = 86.73 @5.2C,11:35:00
111,112,SH_Cr,2025-01-30,11:22,0.3,20.9,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08864,1.21926,88.22,1124.9,1.23974,1.23806,"Had to break through ice for sample,Lab(metroh...",11:22:00

--- Data for Site: 2025-02-15 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
112,113,SFP_Alder_Cr,2025-02-15,08:50,0.6,102.7,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08888,1.21926,87.43,1135.29,1.22298,1.22181,,08:50:00
113,114,SFP_DW,2025-02-15,13:00,0.3,99.3,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09773,1.22826,88.41,1140.12,1.24042,1.23833,,13:00:00
114,115,BJ_Cr,2025-02-15,14:00,2.2,64.2,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06219,1.19369,88.42,1092.78,1.19824,1.19601,Had to break through ice,14:00:00
115,116,SFP_BJ,2025-02-15,14:50,3.3,92.4,8.04,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10355,1.23456,87.80,1112.77,1.24461,1.24045,,14:50:00
116,117,Warm_Sp,2025-02-15,15:40,8.4,120.6,7.94,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08724,1.21766,88.71,1123.34,1.22059,1.21977,,15:40:00
117,118,SFP_Chap,2025-02-15,16:05,3.9,83.9,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07609,1.20675,87.47,1089.64,1.21370,1.21233,,16:05:00
121,122,Fox_Cr,2025-02-15,16:35,1.9,170.5,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11074,1.24235,88.20,1121.89,1.24343,1.24254,,16:35:00
122,123,SFP_Wolf_Cr,2025-02-15,17:10,3.2,84.9,7.94,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06451,1.19522,88.48,1145.03,1.20021,1.19857,,17:10:00
123,124,Canyon_Cr_SFP,2025-02-15,15:25,3.0,103.4,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09383,1.22452,88.36,1135.65,1.23561,1.23328,,15:25:00
124,125,SFP_Canyon_Cr,2025-02-15,16:30,3.5,73.0,8.06,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08241,1.21369,88.36,1141.91,1.22480,1.22148,,16:30:00
125,126,Camp_Cr,2025-02-15,14:35,2.7,82.4,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10411,1.23431,88.51,1072.96,1.23677,1.23586,,14:35:00
126,127,SH_Cr,2025-02-15,14:20,1.5,67.9,NaN,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10091,1.23171,88.11,737.44,1.25185,1.25060,"1L Bottle not all the way full, had to break t...",14:20:00
127,128,SFP_Wapiti,2025-02-15,12:45,3.2,71.9,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06310,1.19565,88.36,1132.84,1.19638,1.19598,,12:45:00

--- Data for Site: 2025-03-02 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
128,129,SFP_Alder_Cr,2025-03-02,08:15,3.3,96.2,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09389,1.22051,87.84,1126.01,1.22893,1.22688,,08:15:00
129,130,SFP_DW,2025-03-02,08:55,2.2,98.7,7.34,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06467,1.19248,88.36,1138.82,1.20327,1.20161,,08:55:00
130,131,BJ_Cr,2025-03-02,10:15,1.8,55.1,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09785,1.22371,88.38,1107.88,1.22524,1.22442,,10:15:00
131,132,SFP_BJ,2025-03-02,18:40,6.1,93.1,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07619,1.20186,88.98,1150.60,1.20924,1.20818,,18:40:00
132,133,Warm_Sp,2025-03-02,18:30,9.1,114.3,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11082,1.23651,88.40,1094.01,1.26331,1.26164,,18:30:00
134,135,HP,2025-03-02,11:00,2.7,96.0,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08246,1.20842,88.52,1082.60,1.30633,1.30441,,11:00:00
135,136,Avalanche_Cr,2025-03-02,11:26,3.2,115.3,7.60,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08899,1.21565,88.71,1142.03,1.27106,1.26811,,11:26:00
136,137,GO_Cr,2025-03-02,12:00,3.7,119.4,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10647,1.23326,87.82,1137.83,1.24189,1.23959,,12:00:00
137,138,Fox_Cr,2025-03-02,17:20,4.2,135.0,7.49,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10362,1.22975,88.44,1128.95,1.24023,1.23667,,17:20:00
138,139,SFP_Wolf_Cr,2025-03-02,17:30,5.2,90.7,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10414,1.23144,88.36,1146.14,1.24064,1.23833,,17:30:00
139,140,Canyon_Cr_SFP,2025-03-02,16:00,4.6,106.9,7.39,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06321,1.18977,88.49,1146.88,1.19927,1.19713,,16:00:00
140,141,SFP_Canyon_Cr,2025-03-02,16:20,5.1,75.4,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06128,1.18713,88.32,1148.42,1.22394,1.22004,,16:20:00
141,142,Camp_Cr,2025-03-02,15:20,5.4,86.2,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08295,1.21562,87.61,1147.96,1.53894,1.52569,,15:20:00
142,143,SH_Cr,2025-03-02,15:00,5.8,54.0,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09429,1.22181,88.43,1140.23,1.43265,1.42028,,15:00:00

--- Data for Site: 2025-03-19 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
143,144,SFP_Alder_Cr,2025-03-19,08:10,3.9,90.1,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09403,1.22094,88.35,1141.14,1.22874,1.22665,,08:10:00
144,145,SFP_DW,2025-03-19,08:41,1.8,99.9,7.65,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06415,1.19247,88.52,1111.06,1.19563,1.19446,,08:41:00
145,146,BJ_Cr,2025-03-19,09:35,0.6,55.6,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07624,1.20391,89.20,1065.29,1.20717,1.20549,,09:35:00
146,147,SFP_BJ,2025-03-19,10:15,1.1,93.6,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09785,1.22314,87.44,1118.01,1.22588,1.22503,,10:15:00
147,148,Warm_Sp,2025-03-19,10:55,4.6,115.0,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06415,1.18929,87.63,1101.42,1.19518,1.19413,,10:55:00
148,149,SFP_Chap,2025-03-19,11:25,1.1,87.2,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06326,1.19051,87.48,1124.43,1.19770,1.19595,,11:25:00
149,150,Fox_Cr,2025-03-19,14:30,3.0,134.9,7.59,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08901,1.21797,88.50,1105.05,1.21977,1.21875,,14:30:00
150,151,SFP_Wolf_Cr,2025-03-19,14:45,5.2,88.4,7.68,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11103,1.23731,87.80,1134.36,1.24189,1.24065,,14:45:00
151,152,Canyon_Cr_SFP,2025-03-19,13:45,2.4,110.5,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10429,1.23124,88.36,1140.98,1.24274,1.23768,,13:45:00
152,153,SFP_Canyon_Cr,2025-03-19,13:50,4.1,72.7,7.71,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10376,1.22966,88.44,1119.97,1.23447,1.23343,,13:50:00
153,154,Camp_Cr,2025-03-19,13:10,2.8,79.5,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10655,1.23277,88.70,1092.33,1.23857,1.23781,,13:10:00
154,155,SH_Cr,2025-03-19,12:55,0.6,60.2,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08315,1.20921,88.23,1133.60,1.22533,1.22314,,12:55:00

--- Data for Site: 2025-03-30 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
155,156,SFP_Alder_Cr,2025-03-30,08:30,5.6,58.1,7.70,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09782,1.22538,87.80,1140.05,1.24697,1.24309,,08:30:00
156,157,SFP_DW,2025-03-30,09:05,4.8,81.9,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06159,1.18897,87.86,1129.93,1.21011,1.20605,,09:05:00
157,158,BJ_Cr,2025-03-30,10:05,3.1,53.8,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09409,1.22086,88.70,1046.68,1.22345,1.22242,,10:05:00
158,159,SFP_BJ,2025-03-30,10:55,4.5,81.1,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11092,1.23704,88.44,1122.86,1.26056,1.25819,,10:55:00
159,160,Warm_Sp,2025-03-30,11:30,7.0,103.5,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08731,1.21494,88.33,1089.77,1.43392,1.43092,,11:30:00
160,161,SFP_Chap,2025-03-30,11:45,4.6,82.4,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.20318,88.45,1143.75,1.21837,1.21578,,11:45:00
161,162,Fox_Cr,2025-03-30,15:45,5.3,103.2,7.49,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10101,1.22627,87.44,1112.12,1.23878,1.23499,,15:45:00
162,163,SFP_Wolf_Cr,2025-03-30,16:05,7.5,82.4,7.67,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06213,1.18783,87.63,1134.69,1.20102,1.19899,,16:05:00
163,164,Canyon_Cr_SFP,2025-03-30,14:50,5.9,110.2,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08321,1.20998,88.23,1135.60,1.23161,1.22774,,14:50:00
164,165,SFP_Canyon_Cr,2025-03-30,15:00,7.3,69.1,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10659,1.23238,88.55,1113.29,1.25168,1.25051,,15:00:00
165,166,Camp_Cr,2025-03-30,14:20,6.1,71.4,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10384,1.23126,88.99,1020.61,1.23609,1.23547,,14:20:00
166,167,SH_Cr,2025-03-30,14:10,6.0,51.1,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10439,1.23196,88.38,1109.36,1.25098,1.23938,,14:10:00
167,168,Nutcracker_Cr,2025-03-30,13:15,6.8,82.4,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06423,1.19138,88.35,1054.18,1.20208,1.20025,"New Site, small debris flow occured inbetween ...",13:15:00

--- Data for Site: 2025-04-15 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
168,169,SFP_Alder_Cr,2025-04-15,16:05,8.5,59.0,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09413,1.22029,87.63,1121.48,1.24459,1.24034,,16:05:00
169,170,SFP_DW,2025-04-15,15:30,8.5,69.0,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08749,1.21478,88.52,1140.66,1.23038,1.22771,,15:30:00
170,171,BJ_Cr,2025-04-15,14:55,7.6,48.3,7.41,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.20369,87.44,1016.08,1.20812,1.20594,,14:55:00
171,172,SFP_BJ,2025-04-15,14:40,9.4,75.9,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11310,1.23828,88.99,1152.88,1.26024,1.25817,,14:40:00
172,173,Warm_Sp,2025-04-15,14:25,11.0,86.7,7.68,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08255,1.20955,88.50,1102.97,1.27461,1.27259,,14:25:00
173,174,SFP_Chap,2025-04-15,14:15,8.5,75.6,7.54,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07538,1.20229,88.45,1151.89,1.21678,1.21457,,14:15:00
174,175,Fox_Cr,2025-04-15,12:50,6.5,86.3,7.23,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06582,1.19321,88.33,1161.69,1.21205,1.20693,,12:50:00
175,176,SFP_Wolf_Cr,2025-04-15,13:00,6.9,71.9,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08336,1.20979,88.38,1123.55,1.23004,1.22603,pine needle,13:00:00
176,177,Canyon_Cr_SFP,2025-04-15,12:25,5.6,92.6,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06215,1.18917,89.20,1159.66,1.21881,1.21461,,12:25:00
177,178,SFP_Canyon_Cr,2025-04-15,12:35,6.5,59.8,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08497,1.21185,88.36,1151.81,1.23882,1.23741,,12:35:00
178,179,Camp_Cr,2025-04-15,10:50,5.4,57.8,7.60,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06160,1.18801,87.80,1051.64,1.24008,1.23792,,10:50:00
179,180,SH_Cr,2025-04-15,10:55,4.6,43.5,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10390,1.23156,87.48,1133.55,1.38447,1.37621,,10:55:00
180,181,Nutcracker_Cr,2025-04-15,12:15,9.9,100.5,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10430,1.23019,88.23,1103.09,1.23278,1.23224,,12:15:00
181,182,HP,2025-04-15,13:30,5.1,90.8,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11092,1.23741,87.86,1122.84,1.26152,1.25643,,13:30:00
182,183,Avalanche_Cr,2025-04-15,13:45,5.8,74.8,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09805,1.22438,88.55,1152.61,1.43208,1.33420,,13:45:00
183,184,GO_Cr,2025-04-15,14:00,5.4,81.0,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06438,1.19094,88.35,1134.45,1.22039,1.21249,,14:00:00
184,185,SFP_Wapiti,2025-04-15,09:55,4.7,73.2,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10662,1.23314,88.44,1022.68,1.23553,1.23472,,09:55:00
185,186,Wapiti_Cr,2025-04-15,10:20,3.1,62.3,7.70,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06343,1.18968,88.70,1145.44,1.19419,1.19271,,10:20:00

--- Data for Site: 2025-04-28 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
186,187,SFP_Alder_Cr,2025-04-28,09:00,6.9,52.9,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10124,1.23313,89.61,1124.44,1.30538,1.29695,,09:00:00
187,188,SFP_DW,2025-04-28,09:30,6.0,58.9,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09152,1.22256,87.87,1124.32,1.28359,1.27662,,09:30:00
188,189,BJ_Cr,2025-04-28,10:05,5.5,44.7,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09423,1.22711,88.34,1112.23,1.23377,1.23103,,10:05:00
189,190,SFP_BJ,2025-04-28,10:20,5.7,63.9,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09453,1.22665,88.72,1142.14,1.27748,1.27417,,10:20:00
190,191,Warm_Sp,2025-04-28,10:30,6.2,71.6,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.04190,1.23573,88.23,1131.04,1.37904,1.37575,,10:30:00
191,192,SFP_Chap,2025-04-28,10:40,6.2,61.5,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08333,1.21148,87.83,1138.43,1.25432,1.25067,,10:40:00
192,193,Fox_Cr,2025-04-28,13:40,8.4,74.2,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06186,1.19313,88.56,1142.09,1.20863,1.20434,,13:40:00
193,194,SFP_Wolf_Cr,2025-04-28,13:50,8.2,57.5,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06344,1.19517,87.47,1136.03,1.24947,1.24621,,13:50:00
194,195,Canyon_Cr_SFP,2025-04-28,13:20,7.7,70.9,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06605,1.19278,88.36,1114.68,1.23775,1.23330,,13:20:00
195,196,SFP_Canyon_Cr,2025-04-28,13:30,7.7,45.2,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10635,1.23833,88.44,1133.73,1.25607,1.25442,,13:30:00
196,197,Camp_Cr,2025-04-28,13:00,8.2,51.2,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08759,1.21932,88.53,1121.14,1.23404,1.23288,,13:00:00
197,198,SH_Cr,2025-04-28,12:50,8.5,40.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06224,1.19431,87.45,1142.47,1.57037,1.55268,,12:50:00
198,199,Nutcracker_Cr,2025-04-28,13:10,13.0,103.8,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08265,1.21078,89.00,1093.28,1.21468,1.21361,,13:10:00
199,200,HP,2025-04-28,11:00,4.7,73.7,7.80,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06437,1.19664,88.51,1147.04,1.22149,1.21752,,11:00:00
200,201,Avalanche_Cr,2025-04-28,11:25,5.7,64.2,7.77,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10662,1.23833,88.46,1143.78,1.76401,1.74821,relatively large sandy grains,11:25:00
201,202,GO_Cr,2025-04-28,11:35,5.9,68.3,7.78,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08501,1.21681,88.48,1084.39,1.25479,1.24834,,11:35:00
202,203,SFP_Wapiti,2025-04-28,12:40,7.2,54.9,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07563,1.20614,88.39,1150.80,1.21133,1.21038,,12:40:00
203,204,Wapiti_Cr,2025-04-28,12:20,5.4,58.8,7.84,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08554,1.21706,87.63,1101.13,1.22485,1.22263,,12:20:00

--- Data for Site: 2025-05-10 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
204,205,SFP_Alder_Cr,2025-05-10,15:45,10.4,41.7,7.21,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10429,1.23715,88.54,1150.84,1.33699,1.32745,,15:45:00
205,206,SFP_DW,2025-05-10,15:15,9.7,44.8,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11105,1.24201,87.45,1140.98,1.33674,1.32903,,15:15:00
206,207,BJ_Cr,2025-05-10,14:40,10.9,42.8,7.04,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09419,1.22554,88.38,1141.69,1.24912,1.24645,,14:40:00
207,208,SFP_BJ,2025-05-10,14:30,10.4,45.6,7.18,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08271,1.21348,87.65,1157.67,1.35082,1.34374,,14:30:00
208,209,Warm_Sp,2025-05-10,14:20,9.5,52.8,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08478,1.21667,88.40,1162.06,1.57770,1.56572,,14:20:00
209,210,SFP_Chap,2025-05-10,14:10,10.9,44.8,7.33,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.10631,1.23682,88.44,1149.29,1.27844,1.25749,tss sample had small twig,14:10:00
210,211,Fox_Cr,2025-05-10,12:50,11.2,85.3,7.11,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08761,1.21878,88.57,1150.82,1.23162,1.22601,,12:50:00
211,212,SFP_Wolf_Cr,2025-05-10,13:00,8.4,42.7,7.24,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06182,1.19346,88.49,1148.18,1.25481,1.24748,,13:00:00
212,213,Canyon_Cr_SFP,2025-05-10,12:30,7.8,59.4,6.92,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.08322,1.21485,87.88,1139.71,1.34684,1.32987,,12:30:00
213,214,SFP_Canyon_Cr,2025-05-10,12:35,7.8,35.9,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06432,1.19784,88.50,1137.44,1.25111,1.24572,,12:35:00
214,215,Camp_Cr,2025-05-10,12:20,11.3,52.3,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09147,1.22239,88.35,1136.59,1.31439,1.30763,,12:20:00
215,216,SH_Cr,2025-05-10,12:15,11.2,35.5,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06334,1.19487,88.72,1162.66,2.18516,2.16329,tss had gravel sized rock,12:15:00
216,217,HP,2025-05-10,13:30,7.2,55.4,7.03,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09812,1.22966,87.49,1147.26,1.29725,1.28673,,13:30:00
217,218,Avalanche_Cr,2025-05-10,13:45,7.8,51.6,7.06,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09147,1.22702,89.00,1130.46,1.60014,1.56489,,13:45:00
218,219,GO_Cr,2025-05-10,13:55,8.8,45.6,7.17,NaN,"TSS, Nuts, DOC, Alk",NaN,"19,46",2.17692,2.44051,88.39,1140.98,2.77911,2.70147,Two filters used due to high volume of sedimen...,13:55:00
219,220,SFP_Wapiti,2025-05-10,11:50,8.0,34.9,7.07,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06595,1.19851,88.46,1148.39,1.23501,1.23088,,11:50:00
220,221,Wapiti_Cr,2025-05-10,10:05,5.7,56.8,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10724,1.24071,89.64,1149.96,1.26535,1.25607,,10:05:00
221,222,Flat_Cr,2025-05-10,11:30,7.9,36.8,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.20734,87.83,1145.42,1.46248,1.39162,"New Site, evidence of disturbance near creek a...",11:30:00
222,223,Bear_Cr,2025-05-10,12:00,8.8,49.9,7.15,NaN,"TSS, Nuts, DOC, Alk",NaN,"11,51",2.14767,2.41332,88.24,1150.55,3.30473,3.27641,"Very murky dark flows, very likely debris flow...",12:00:00

--- Data for Site: 2025-05-27 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
223,224,SFP_Alder_Cr,2025-05-27,18:05,11.8,18.6,7.52,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10701,1.23464,44.60,657.59,1.25933,1.25753,tss sample collected in gatorade bottle becuas...,18:05:00
224,225,SFP_DW,2025-05-27,17:30,11.8,24.8,7.50,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06626,1.19711,88.74,1125.86,1.24288,1.23997,,17:30:00
225,226,BJ_Cr,2025-05-27,15:45,10.7,33.3,7.28,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09184,1.22445,88.24,1125.74,1.22968,1.22819,,15:45:00
226,227,SFP_BJ,2025-05-27,16:00,11.5,31.3,7.39,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08499,1.21597,87.89,1111.25,1.31336,1.31050,,16:00:00
227,228,Warm_Sp,2025-05-27,15:30,12.0,40.6,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09473,1.22604,88.36,1112.69,1.31552,1.31479,,15:30:00
228,229,SFP_Chap,2025-05-27,15:10,10.9,23.7,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08587,1.21625,88.43,1114.39,1.25804,1.25597,,15:10:00
229,230,Fox_Cr,2025-05-27,14:40,13.3,109.8,7.24,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10658,1.23748,88.74,1116.93,1.24144,1.24035,,14:40:00
230,231,SFP_Wolf_Cr,2025-05-27,14:55,10.6,30.1,7.44,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06438,1.19591,88.47,1134.29,1.23299,1.23082,,14:55:00
231,232,Canyon_Cr_SFP,2025-05-27,14:10,10.1,48.9,7.04,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.07899,1.21092,87.47,1118.96,1.31931,1.31456,,14:10:00
232,233,SFP_Canyon_Cr,2025-05-27,14:20,10.0,24.4,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11147,1.24295,87.84,1123.47,1.26972,1.26789,,14:20:00
233,234,Camp_Cr,2025-05-27,13:50,12.8,46.4,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07629,1.20979,88.55,1101.16,1.21441,1.21391,,13:50:00
234,235,SH_Cr,2025-05-27,11:20,10.0,37.9,7.38,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10418,1.23593,88.67,1115.32,1.23861,1.23830,,11:20:00
235,236,HP,2025-05-27,10:00,5.7,47.2,7.33,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10127,1.23357,87.49,1092.76,1.24801,1.24594,,10:00:00
236,237,Avalanche_Cr,2025-05-27,10:20,6.3,53.1,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10445,1.23638,89.01,1075.05,1.26565,1.26253,,10:20:00
237,238,GO_Cr,2025-05-27,10:40,9.0,47.6,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09838,1.23027,87.65,1114.95,1.24574,1.24239,,10:40:00
238,239,SFP_Wapiti,2025-05-27,13:20,9.3,11.2,7.59,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.10181,1.23364,88.38,1089.84,1.24797,1.24680,,13:20:00
239,240,Wapiti_Cr,2025-05-27,12:50,7.8,49.5,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08535,1.21751,88.51,1131.93,1.23264,1.22865,,12:50:00
240,241,Flat_Cr,2025-05-27,11:55,10.8,37.6,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08773,1.21961,88.40,1079.38,1.27446,1.26386,,11:55:00
241,242,Bear_Cr,2025-05-27,13:30,11.4,40.8,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11116,1.24172,88.45,1074.04,1.36588,1.36237,"Lid lost during sampling, lid from bottle 19 u...",13:30:00

--- Data for Site: 2025-06-08 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
242,243,SFP_Alder_Cr,2025-06-08,13:55,14.3,14.7,7.73,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09836,1.22576,88.39,1127.21,1.25754,1.25497,,13:55:00
243,244,SFP_DW,2025-06-08,13:20,12.7,29.4,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10665,1.23319,89.00,1145.50,1.25015,1.24864,,13:20:00
244,245,BJ_Cr,2025-06-08,12:45,10.4,26.8,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11138,1.23955,88.54,1122.57,1.24461,1.24183,,12:45:00
245,246,SFP_BJ,2025-06-08,12:35,11.4,25.3,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08511,1.21321,88.19,1124.24,1.22617,1.22471,,12:35:00
246,247,Warm_Sp,2025-06-08,12:20,11.7,7.8,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10142,1.22823,87.69,1140.38,1.23560,1.23275,,12:20:00
247,248,SFP_Chap,2025-06-08,12:10,10.4,11.1,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08587,1.21298,88.36,1140.05,1.22463,1.22338,,12:10:00
248,249,Fox_Cr,2025-06-08,10:55,11.2,81.9,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10467,1.23251,88.50,1156.60,1.23621,1.23426,,10:55:00
249,250,SFP_Wolf_Cr,2025-06-08,11:05,9.4,17.1,7.52,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11139,1.23829,88.33,1058.05,1.24964,1.24793,,11:05:00
250,251,Canyon_Cr_SFP,2025-06-08,10:40,9.0,31.8,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10423,1.23137,88.72,1148.24,1.23923,1.23747,,10:40:00
251,252,SFP_Canyon_Cr,2025-06-08,10:50,8.8,9.1,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06406,1.19121,88.21,1146.64,1.20562,1.20363,,10:50:00
252,253,Camp_Cr,2025-06-08,09:55,9.6,22.8,7.53,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08532,1.21226,88.41,1136.40,1.21471,1.21369,,09:55:00
253,254,SH_Cr,2025-06-08,09:50,10.2,12.3,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08291,1.21023,89.59,1058.81,1.21349,1.21217,,09:50:00
254,255,HP,2025-06-08,11:30,9.6,36.8,7.64,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07668,1.20401,87.45,1058.47,1.20674,1.20547,,11:30:00
255,256,Avalanche_Cr,2025-06-08,11:40,10.4,47.8,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10694,1.23303,88.50,1164.14,1.23886,1.23728,,11:40:00
256,257,GO_Cr,2025-06-08,11:55,12.4,48.2,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09193,1.21785,87.59,1145.26,1.22247,1.22084,,11:55:00
257,258,SFP_Wapiti,2025-06-08,09:30,8.7,7.6,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.10216,1.22946,87.89,1123.58,1.23689,1.21576,,09:30:00
258,259,Wapiti_Cr,2025-06-08,08:50,6.4,10.8,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08794,1.21544,88.59,1149.98,1.22131,1.21936,,08:50:00
259,260,Flat_Cr,2025-06-08,09:00,9.8,82.7,7.54,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09477,1.22109,88.44,1155.38,1.22435,1.22288,,09:00:00
260,261,Bear_Cr,2025-06-08,09:40,9.5,8.2,7.31,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.07951,1.20683,87.84,1134.04,1.22348,1.22207,,09:40:00

--- Data for Site: 2025-06-22 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
261,262,SFP_Alder_Cr,2025-06-22,14:40,14.9,57.8,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,31,1.09428,1.22096,88.40,1146.14,1.231680,1.229890,Rained/snowed late 6/21 through 13:30 on 6/22,14:40:00
262,263,SFP_DW,2025-06-22,13:40,12.2,58.4,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06421,1.19139,88.55,1152.43,1.195790,1.194720,Rained/snowed late 6/21 through 13:30 on 6/22,13:40:00
263,264,BJ_Cr,2025-06-22,13:10,8.1,47.5,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10433,1.23068,88.20,1116.12,1.233230,1.231720,Rained/snowed late 6/21 through 13:30 on 6/22,13:10:00
264,265,SFP_BJ,2025-06-22,12:55,9.0,54.1,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10703,1.23373,87.64,1135.51,1.236910,1.236040,Rained/snowed late 6/21 through 13:30 on 6/22,12:55:00
265,266,Warm_Sp,2025-06-22,12:40,10.4,80.1,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09208,1.21857,88.38,1142.61,1.219990,1.219430,Rained/snowed late 6/21 through 13:30 on 6/22,12:40:00
266,267,SFP_Chap,2025-06-22,12:30,9.0,47.3,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10765,1.23207,87.47,1113.61,1.236820,1.235470,Rained/snowed late 6/21 through 13:30 on 6/22,12:30:00
267,268,Fox_Cr,2025-06-22,10:25,8.7,152.0,7.23,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10667,1.23361,88.45,1131.32,1.235370,1.234260,Rained/snowed late 6/21 through 13:30 on 6/22,10:25:00
268,269,SFP_Wolf_Cr,2025-06-22,10:35,7.4,44.8,7.46,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07664,1.26318,88.58,1142.44,1.207040,1.206011,Rained/snowed late 6/21 through 13:30 on 6/22,10:35:00
269,270,Canyon_Cr_SFP,2025-06-22,10:05,6.2,77.6,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11164,1.23889,88.37,1148.08,1.244150,1.243460,Rained/snowed late 6/21 through 13:30 on 6/22,10:05:00
270,271,SFP_Canyon_Cr,2025-06-22,10:10,6.9,36.4,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08294,1.21068,87.87,1141.47,1.213150,1.212390,Rained/snowed late 6/21 through 13:30 on 6/22,10:10:00
271,272,Camp_Cr,2025-06-22,09:50,6.1,57.8,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09857,1.22493,88.52,1138.34,1.237750,1.235420,Rained/snowed late 6/21 through 13:30 on 6/22,09:50:00
272,273,SH_Cr,2025-06-22,09:40,5.9,49.1,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08601,1.21373,88.24,1151.27,1.263320,1.259450,Rained/snowed late 6/21 through 13:30 on 6/22,09:40:00
273,274,HP,2025-06-22,11:30,6.1,70.6,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06451,1.19078,88.51,1152.22,1.192540,1.191830,Rained/snowed late 6/21 through 13:30 on 6/22,11:30:00
274,275,Avalanche_Cr,2025-06-22,11:45,7.2,92.0,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07570,1.20167,89.01,1147.82,1.203320,1.202740,Rained/snowed late 6/21 through 13:30 on 6/22,11:45:00
275,276,GO_Cr,2025-06-22,11:15,7.7,99.1,7.31,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08511,1.21104,87.51,1104.42,1.212750,1.211670,Rained/snowed late 6/21 through 13:30 on 6/22,11:15:00
276,277,SFP_Wapiti,2025-06-22,09:20,6.8,36.2,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,10,1.08256,1.20896,88.73,1155.35,1.211420,1.210490,Rained/snowed late 6/21 through 13:30 on 6/22,09:20:00
277,278,Wapiti_Cr,2025-06-22,08:50,5.1,73.7,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08527,1.21230,87.95,1153.59,1.216470,1.215130,Rained/snowed late 6/21 through 13:30 on 6/22,08:50:00
278,279,Flat_Cr,2025-06-22,08:35,5.6,53.2,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11141,1.23853,89.61,1126.14,1.233997,1.239140,Rained/snowed late 6/21 through 13:30 on 6/22,08:35:00
279,280,Bear_Cr,2025-06-22,09:25,5.9,66.2,7.36,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06623,1.19338,88.46,1128.62,1.198440,1.197260,Rained/snowed late 6/21 through 13:30 on 6/22,09:25:00

--- Data for Site: 2025-07-07 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
280,281,SFP_Alder_Cr,2025-07-07,16:15,17.6,110.8,7.93,54.03,"TSS, Nuts, DOC, Alk",NaN,13,1.06448,1.19237,87.89,1156.1,1.21994,1.21607,Large rainstorm 7/4,16:15:00
281,282,SFP_DW,2025-07-07,15:45,17.5,117.7,7.50,52.63,"TSS, Nuts, DOC, Alk",NaN,19,1.07578,1.20219,88.38,1155.1,1.21849,1.21532,Large rainstorm 7/4,15:45:00
282,283,BJ_Cr,2025-07-07,14:50,11.4,78.9,6.94,35.38,"TSS, Nuts, DOC, Alk",NaN,7,1.08282,1.20964,88.57,1152.0,1.21334,1.21156,Large rainstorm 7/4,14:50:00
283,284,SFP_BJ,2025-07-07,14:30,16.0,106.7,7.75,49.15,"TSS, Nuts, DOC, Alk",NaN,46,1.10144,1.22874,88.40,1159.7,1.25283,1.24925,Large rainstorm 7/4,14:30:00
284,285,Warm_Sp,2025-07-07,14:15,16.9,153.6,7.35,70.49,"TSS, Nuts, DOC, Alk",NaN,11,1.08594,1.21253,87.65,1155.7,1.21803,1.21697,Large rainstorm 7/4,14:15:00
285,286,SFP_Chap,2025-07-07,13:10,14.8,94.3,7.55,43.29,"TSS, Nuts, DOC, Alk",NaN,50,1.08788,1.21594,87.50,1151.8,1.24049,1.23768,Large rainstorm 7/4,13:10:00
286,287,Chapman_Cr,2025-07-07,13:30,14.8,156.2,6.86,64.74,"TSS, Nuts, DOC, Alk",NaN,"18,22,3,14,12",5.47251,6.10803,88.21,1063.1,9.13658,8.99315,"Large rainstorm 7/4, Debris flow occurred and ...",13:30:00
287,288,Fox_Cr,2025-07-07,12:35,15.3,199.0,7.46,152.60,"TSS, Nuts, DOC, Alk",NaN,4,1.10483,1.23205,88.44,1128.8,1.27762,1.26813,Large rainstorm 7/4,12:35:00
288,289,SFP_Wolf_Cr,2025-07-07,12:45,14.2,96.1,7.53,43.27,"TSS, Nuts, DOC, Alk",NaN,17,1.09196,1.21837,88.58,1136.7,1.23367,1.23129,Large rainstorm 7/4,12:45:00
289,290,Canyon_Cr_SFP,2025-07-07,12:15,12.0,149.3,7.42,66.99,"TSS, Nuts, DOC, Alk",NaN,35,1.10221,1.22772,89.01,1109.7,1.25826,1.25398,Large rainstorm 7/4,12:15:00
290,291,SFP_Canyon_Cr,2025-07-07,12:20,13.6,78.3,7.58,35.87,"TSS, Nuts, DOC, Alk",NaN,59,1.09239,1.21851,87.45,1129.9,1.22646,1.22531,Large rainstorm 7/4,12:20:00
291,292,Camp_Cr,2025-07-07,12:00,13.3,107.6,7.74,46.44,"TSS, Nuts, DOC, Alk",NaN,9,1.06408,1.19144,88.36,1116.8,1.36117,1.35628,Large rainstorm 7/4,12:00:00
292,293,SH_Cr,2025-07-07,11:55,15.1,96.4,7.63,44.88,"TSS, Nuts, DOC, Alk",NaN,1,1.08515,1.21112,88.50,1126.0,1.57721,1.56832,Large rainstorm 7/4,11:55:00
293,294,HP,2025-07-07,09:45,9.4,130.7,7.80,60.29,"TSS, Nuts, DOC, Alk",NaN,25,1.09861,1.22470,89.61,1111.4,1.23748,1.23513,Large rainstorm 7/4,09:45:00
294,295,Avalanche_Cr,2025-07-07,09:55,10.3,183.6,7.85,84.20,"TSS, Nuts, DOC, Alk",NaN,51,1.06259,1.19076,87.84,1101.7,1.22199,1.21754,Large rainstorm 7/4,09:55:00
295,296,GO_Cr,2025-07-07,10:05,10.3,116.0,7.64,93.21,"TSS, Nuts, DOC, Alk",NaN,8,1.10708,1.23389,88.74,1107.5,1.32969,1.31897,Large rainstorm 7/4,10:05:00
296,297,SFP_Wapiti,2025-07-07,11:35,13.2,73.0,7.86,34.57,"TSS, Nuts, DOC, Alk",NaN,31,1.09438,1.22157,88.45,1123.0,1.22559,1.22385,Large rainstorm 7/4,11:35:00
297,298,Wapiti_Cr,2025-07-07,11:15,8.6,130.5,7.79,61.19,"TSS, Nuts, DOC, Alk",NaN,15,1.08534,1.21122,88.25,1020.3,1.21546,1.21391,Large rainstorm 7/4,11:15:00
298,299,Bear_Cr,2025-07-07,11:45,14.1,129.9,7.72,60.13,"TSS, Nuts, DOC, Alk",NaN,6,1.10428,1.23115,88.52,1058.8,1.24066,1.23929,Large rainstorm 7/4,11:45:00

--- Data for Site: 2025-07-21 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
299,300,SFP_Alder_Cr,2025-07-21,15:05,14.24,62.0,7.83,NaN,"TSS, Nuts, DOC, Alk",4.0,5,1.08908,1.21634,87.65,1132.09,1.22811,1.22575,used old YSI probe for temp and us,15:05:00
300,301,SFP_DW,2025-07-21,14:25,16.45,79.0,7.89,NaN,"TSS, Nuts, DOC, Alk",12.0,2,1.09774,1.22551,87.90,1152.45,1.22902,1.22756,used old YSI probe for temp and us,14:25:00
301,302,BJ_Cr,2025-07-21,13:50,9.70,46.0,7.95,NaN,"TSS, Nuts, DOC, Alk",8.0,33,1.10739,1.23581,88.79,1106.94,1.23861,1.23698,used old YSI probe for temp and us,13:50:00
302,303,SFP_BJ,2025-07-21,13:25,14.33,74.0,7.44,NaN,"TSS, Nuts, DOC, Alk",7.0,23,1.10267,1.23013,89.01,1143.23,1.23394,1.23301,used old YSI probe for temp and us,13:25:00
303,304,Warm_Sp,2025-07-21,13:25,15.03,97.0,7.79,NaN,"TSS, Nuts, DOC, Alk",13.0,9,1.06387,1.19159,88.36,1146.78,1.19519,1.19424,used old YSI probe for temp and us,13:25:00
304,305,SFP_Chap,2025-07-21,12:50,13.75,67.0,7.41,NaN,"TSS, Nuts, DOC, Alk",9.0,12,1.06649,1.19515,87.50,1142.76,1.19861,1.19758,used old YSI probe for temp and us,12:50:00
305,306,Chapman_Cr,2025-07-21,13:00,13.75,97.0,7.47,NaN,"TSS, Nuts, DOC, Alk",11.0,51,1.06251,1.18985,88.47,1026.57,1.21803,1.21578,used old YSI probe for temp and us,13:00:00
306,307,Fox_Cr,2025-07-21,11:25,12.58,191.0,7.79,NaN,"TSS, Nuts, DOC, Alk",1.0,1,1.08526,1.21293,88.40,1131.35,1.21856,1.21693,used old YSI probe for temp and us,11:25:00
307,308,SFP_Wolf_Cr,2025-07-21,11:35,12.36,68.0,7.53,NaN,"TSS, Nuts, DOC, Alk",16.0,25,1.09850,1.22471,88.48,1098.77,1.22818,1.22685,used old YSI probe for temp and us,11:35:00
308,309,Canyon_Cr_SFP,2025-07-21,10:45,9.53,92.0,7.73,NaN,"TSS, Nuts, DOC, Alk",3.0,20,1.06182,1.18911,89.00,1134.53,1.19946,1.19775,used old YSI probe for temp and us,10:45:00
309,310,SFP_Canyon_Cr,2025-07-21,11:00,12.01,56.0,8.02,NaN,"TSS, Nuts, DOC, Alk",2.0,34,1.06505,1.19284,89.38,1145.99,1.19494,1.19405,used old YSI probe for temp and us,11:00:00
310,311,Camp_Cr,2025-07-21,10:20,10.32,65.0,7.93,NaN,"TSS, Nuts, DOC, Alk",14.0,4,1.10493,1.23106,88.52,1130.43,1.23823,1.23706,used old YSI probe for temp and us,10:20:00
311,312,SH_Cr,2025-07-21,10:15,11.28,57.0,7.63,NaN,"TSS, Nuts, DOC, Alk",19.0,50,1.08789,1.21641,89.62,1093.83,1.23924,1.23677,used old YSI probe for temp and us,10:15:00
312,313,HP,2025-07-21,12:05,9.62,80.0,7.90,NaN,"TSS, Nuts, DOC, Alk",5.0,6,1.10436,1.23295,89.04,1122.45,1.23758,1.23627,used old YSI probe for temp and us,12:05:00
313,314,Avalanche_Cr,2025-07-21,12:20,12.25,112.0,7.81,NaN,"TSS, Nuts, DOC, Alk",6.0,19,1.07586,1.20409,87.47,1117.18,1.21155,1.20988,used old YSI probe for temp and us,12:20:00
314,315,GO_Cr,2025-07-21,12:30,15.01,127.0,7.56,NaN,"TSS, Nuts, DOC, Alk",10.0,60,1.09433,1.22138,88.57,1135.37,1.22659,1.22472,used old YSI probe for temp and us,12:30:00
315,316,SFP_Wapiti,2025-07-21,09:35,10.85,54.0,8.01,NaN,"TSS, Nuts, DOC, Alk",17.0,13,1.06473,1.19374,88.74,1159.68,1.19508,1.19452,used old YSI probe for temp and us,09:35:00
316,317,Wapiti_Cr,2025-07-21,09:04,7.08,76.0,7.39,NaN,"TSS, Nuts, DOC, Alk",15.0,14,1.07708,1.20592,89.06,1000.35,1.21112,1.20934,used old YSI probe for temp and us,09:04:00
317,318,Bear_Cr,2025-07-21,09:55,10.40,81.0,7.89,NaN,"TSS, Nuts, DOC, Alk",18.0,58,1.08356,1.21146,87.88,1141.35,1.21582,1.21449,used old YSI probe for temp and us,09:55:00

--- Data for Site: 2025-08-01 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
318,319,SFP_Alder_Cr,2025-08-01,12:55,14.62,100.0,8.08,65.82,"TSS, Nuts, DOC, Alk",4.0,13,1.063,1.191,87.63,1137.63,1.216,1.212,"rainstorm night of 7/31 before sampling, river...",12:55:00
319,320,SFP_DW,2025-08-01,13:07,13.89,80.0,8.03,84.93,"TSS, Nuts, DOC, Alk",1.0,23,1.101,1.230,88.40,1131.90,1.263,1.258,rainstorm night of 7/31 before sampling,13:07:00
320,321,BJ_Cr,2025-08-01,13:20,9.66,47.0,8.01,50.89,"TSS, Nuts, DOC, Alk",5.0,12,1.066,1.193,88.38,1090.53,1.202,1.193,rainstorm night of 7/31 before sampling,13:20:00
321,322,SFP_BJ,2025-08-01,13:55,17.17,83.0,8.09,81.43,"TSS, Nuts, DOC, Alk",3.0,4,1.106,1.231,88.21,1116.96,1.247,1.239,rainstorm night of 7/31 before sampling,13:55:00
322,323,Warm_Sp,2025-08-01,14:30,14.44,63.0,8.18,103.30,"TSS, Nuts, DOC, Alk",2.0,2,1.098,1.226,88.53,1116.34,1.226,1.225,rainstorm night of 7/31 before sampling,14:30:00
323,324,SFP_Chap,2025-08-01,12:30,13.30,73.0,8.11,84.19,"TSS, Nuts, DOC, Alk",9.0,19,1.075,1.207,87.49,NaN,NaN,NaN,"rainstorm night of 7/31 before sampling, TSS b...",12:30:00
324,325,Chapman_Cr,2025-08-01,12:40,13.04,77.0,8.02,102.80,"TSS, Nuts, DOC, Alk",6.0,14,1.076,1.208,87.45,1081.21,1.231,1.235,rainstorm night of 7/31 before sampling,12:40:00
325,326,Fox_Cr,2025-08-01,11:17,13.11,189.0,7.87,193.80,"TSS, Nuts, DOC, Alk",15.0,25,1.098,1.230,88.23,1119.00,1.244,1.232,rainstorm night of 7/31 before sampling,11:17:00
326,327,SFP_Wolf_Cr,2025-08-01,11:25,12.17,73.0,8.08,74.92,"TSS, Nuts, DOC, Alk",14.0,22,1.111,1.243,88.51,1140.91,1.244,1.247,rainstorm night of 7/31 before sampling,11:25:00
327,328,Canyon_Cr_SFP,2025-08-01,11:00,9.98,94.0,7.89,96.52,"TSS, Nuts, DOC, Alk",17.0,17,1.092,1.223,88.73,1143.55,1.241,1.231,rainstorm night of 7/31 before sampling,11:00:00
328,329,SFP_Canyon_Cr,2025-08-01,11:05,11.90,62.0,7.11,127.80,"TSS, Nuts, DOC, Alk",13.0,18,1.112,1.244,88.34,1084.70,1.244,1.247,rainstorm night of 7/31 before sampling,11:05:00
329,330,Camp_Cr,2025-08-01,10:48,11.25,67.0,7.99,86.97,"TSS, Nuts, DOC, Alk",12.0,8,1.107,1.238,87.89,1128.40,1.242,1.241,rainstorm night of 7/31 before sampling,10:48:00
330,331,SH_Cr,2025-08-01,10:45,12.56,58.0,8.12,62.18,"TSS, Nuts, DOC, Alk",11.0,15,1.085,1.215,88.07,1072.33,1.255,1.252,rainstorm night of 7/31 before sampling,10:45:00
331,332,HP,2025-08-01,11:50,9.41,84.0,8.03,86.55,"TSS, Nuts, DOC, Alk",10.0,7,1.082,1.214,88.57,1140.50,1.215,1.218,rainstorm night of 7/31 before sampling,11:50:00
332,333,Avalanche_Cr,2025-08-01,12:05,12.31,115.0,7.96,117.50,"TSS, Nuts, DOC, Alk",7.0,1,1.085,1.216,88.99,1131.08,1.234,1.224,rainstorm night of 7/31 before sampling,12:05:00
333,334,GO_Cr,2025-08-01,12:15,1562.00,109.0,8.02,134.10,"TSS, Nuts, DOC, Alk",8.0,6,1.105,1.237,88.49,1099.43,1.366,1.357,rainstorm night of 7/31 before sampling,12:15:00
334,335,SFP_Wapiti,2025-08-01,10:25,11.69,60.0,8.11,63.72,"TSS, Nuts, DOC, Alk",16.0,20,1.063,1.193,88.46,1144.32,1.205,1.196,rainstorm night of 7/31 before sampling,10:25:00
335,336,Wapiti_Cr,2025-08-01,10:00,7.69,79.0,7.98,83.49,"TSS, Nuts, DOC, Alk",19.0,5,1.089,1.221,89.61,1061.07,1.222,1.221,rainstorm night of 7/31 before sampling,10:00:00
336,337,Bear_Cr,2025-08-01,10:35,11.78,82.0,8.05,88.08,"TSS, Nuts, DOC, Alk",18.0,9,1.065,1.197,87.85,1081.82,1.211,1.199,rainstorm night of 7/31 before sampling,10:35:00

--- Data for Site: 2025-08-14 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
337,338,SFP_Alder_Cr,2025-08-14,08:43,13.17,44.0,7.49,61.59,"TSS, Nuts, DOC, Alk",9.0,32,1.080,1.212,88.34,1155.71,1.225,1.2238,,08:43:00
338,339,SFP_DW,2025-08-14,09:24,14.64,73.0,7.27,100.10,"TSS, Nuts, DOC, Alk",5.0,33,1.107,1.239,88.87,1126.54,1.243,1.2431,,09:24:00
339,340,BJ_Cr,2025-08-14,10:20,8.17,33.0,7.29,55.45,"TSS, Nuts, DOC, Alk",13.0,58,1.083,1.212,88.57,1116.33,1.219,1.2180,,10:20:00
340,341,SFP_BJ,2025-08-14,10:35,11.41,63.0,7.16,95.34,"TSS, Nuts, DOC, Alk",12.0,68,1.095,1.225,88.22,1099.53,1.226,1.2261,,10:35:00
341,342,Warm_Sp,2025-08-14,10:45,12.03,79.0,7.11,116.80,"TSS, Nuts, DOC, Alk",7.0,50,1.092,1.219,89.54,1121.45,1.220,1.2206,,10:45:00
342,343,SFP_Chap,2025-08-14,10:55,12.12,60.0,7.14,87.09,"TSS, Nuts, DOC, Alk",18.0,59,1.094,1.226,88.03,1097.46,1.226,1.2262,,10:55:00
343,344,Chapman_Cr,2025-08-14,16:25,13.07,79.0,6.93,112.50,"TSS, Nuts, DOC, Alk",3.0,34,1.067,1.198,88.75,1128.46,1.211,1.2099,,16:25:00
344,345,Fox_Cr,2025-08-14,16:30,16.99,162.0,7.20,207.50,"TSS, Nuts, DOC, Alk",14.0,51,1.063,1.196,88.91,1120.25,1.199,1.1983,,16:30:00
345,346,SFP_Wolf_Cr,2025-08-14,16:40,18.03,62.0,6.56,83.96,"TSS, Nuts, DOC, Alk",1.0,31,1.094,1.228,88.67,1151.42,1.233,1.2313,,16:40:00
346,347,Canyon_Cr_SFP,2025-08-14,16:15,14.75,78.0,6.27,106.70,"TSS, Nuts, DOC, Alk",19.0,53,1.086,1.217,89.83,1149.43,1.221,1.2207,,16:15:00
347,348,SFP_Canyon_Cr,2025-08-14,16:20,17.86,59.0,7.16,75.64,"TSS, Nuts, DOC, Alk",8.0,54,1.081,1.209,88.59,1148.32,1.211,1.2100,,16:20:00
348,349,Camp_Cr,2025-08-14,12:40,13.45,52.0,7.16,75.33,"TSS, Nuts, DOC, Alk",16.0,56,1.089,1.222,88.78,1084.10,1.225,1.2231,,12:40:00
349,350,SH_Cr,2025-08-14,12:45,15.45,49.0,6.99,66.03,"TSS, Nuts, DOC, Alk",15.0,43,1.097,1.228,88.93,1104.76,1.243,1.2397,,12:45:00
350,351,HP,2025-08-14,11:35,9.36,60.0,7.16,95.11,"TSS, Nuts, DOC, Alk",4.0,29,1.115,1.247,88.07,1138.77,1.250,1.2503,,11:35:00
351,352,Avalanche_Cr,2025-08-14,11:45,11.98,88.0,7.12,128.00,"TSS, Nuts, DOC, Alk",11.0,27,1.101,1.234,88.21,1111.92,1.235,1.2370,,11:45:00
352,353,GO_Cr,2025-08-14,12:05,15.78,110.0,6.97,150.40,"TSS, Nuts, DOC, Alk",2.0,39,1.099,1.233,88.75,1082.22,1.247,1.2438,,12:05:00
353,354,SFP_Wapiti,2025-08-14,14:50,16.93,56.0,7.23,71.61,"TSS, Nuts, DOC, Alk",17.0,28,1.107,1.240,89.13,1140.71,1.242,1.2420,,14:50:00
354,355,Wapiti_Cr,2025-08-14,14:30,10.00,54.0,6.91,88.38,"TSS, Nuts, DOC, Alk",10.0,30,1.096,1.231,88.65,1088.75,1.235,1.2325,,14:30:00
355,356,Bear_Cr,2025-08-14,15:00,18.33,76.0,7.20,94.82,"TSS, Nuts, DOC, Alk",6.0,37,1.801,1.214,87.93,1126.56,1.215,1.2146,,15:00:00

--- Data for Site: 2025-08-27 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
356,357,MainPayette_Gauge,2025-08-27,12:30,19.1,47.0,7.07,55.33,"TSS, Nuts, DOC, Alk",16.0,25,1.0984,1.2314,58.144,591.81,1.2751,1.2673,non-regular sampling after rain. 500ml bottle ...,12:30:00
357,358,SFP_Staircase,2025-08-27,13:00,17.1,79.0,6.94,95.10,"TSS, Nuts, DOC, Alk",19.0,"16,32,27,41",4.3401,4.8741,57.940,597.88,5.7575,5.5978,non-regular sampling after rain. 500ml bottle ...,13:00:00
358,359,MFP_Crouch,2025-08-27,13:15,18.3,68.0,7.07,75.63,"TSS, Nuts, DOC, Alk",10.0,58,1.0852,1.2177,58.031,579.85,1.2268,1.2237,non-regular sampling after rain. 500ml bottle ...,13:15:00
359,360,SFP_Wapiti,2025-08-27,14:35,14.5,60.0,7.08,70.89,"TSS, Nuts, DOC, Alk",11.0,11,1.0863,1.2180,58.190,576.71,1.2795,1.2717,non-regular sampling after rain. 500ml bottle ...,14:35:00
360,361,SH_Cr,2025-08-27,14:50,15.6,54.0,6.92,67.08,"TSS, Nuts, DOC, Alk",12.0,49,1.0885,1.2228,57.887,573.18,1.2398,1.2361,non-regular sampling after rain. 500ml bottle ...,14:50:00
361,362,Canyon_Cr_SFP,2025-08-27,15:00,12.6,90.0,6.98,102.40,"TSS, Nuts, DOC, Alk",20.0,"4,40,39",3.3143,3.7159,57.980,607.70,3.8732,3.8484,non-regular sampling after rain. 500ml bottle ...,15:00:00
362,363,SFP_Canyon_Cr,2025-08-27,15:05,12.5,67.0,7.05,73.65,"TSS, Nuts, DOC, Alk",13.0,59,1.0922,1.2264,57.780,604.07,1.3054,1.2959,non-regular sampling after rain. 500ml bottle ...,15:05:00
363,364,Fox_Cr,2025-08-27,15:20,15.1,177.0,6.81,195.60,"TSS, Nuts, DOC, Alk",7.0,46,1.1008,1.2336,58.498,566.91,1.2496,1.2450,non-regular sampling after rain. 500ml bottle ...,15:20:00
364,365,SFP_Wolf_Cr,2025-08-27,15:30,14.2,74.0,6.95,111.20,"TSS, Nuts, DOC, Alk",1.0,45,1.1007,1.2322,57.091,594.95,1.3744,1.3576,non-regular sampling after rain. 500ml bottle ...,15:30:00
365,366,SFP_Chap,2025-08-27,15:45,14.3,73.0,6.89,84.05,"TSS, Nuts, DOC, Alk",17.0,48,1.0994,1.2329,58.260,588.59,1.3687,1.3521,non-regular sampling after rain. 500ml bottle ...,15:45:00
366,367,Warm_Sp,2025-08-27,15:55,14.6,90.0,7.03,103.20,"TSS, Nuts, DOC, Alk",18.0,"28,47,20",3.2673,3.6684,58.189,590.95,4.0679,4.0315,non-regular sampling after rain. 500ml bottle ...,15:55:00
367,368,SFP_BJ,2025-08-27,16:05,14.4,77.0,6.68,90.74,"TSS, Nuts, DOC, Alk",5.0,"37,8,13,29,31,36",6.5471,7.3453,58.078,603.64,8.7442,8.5935,non-regular sampling after rain. 500ml bottle ...,16:05:00
368,369,BJ_Cr,2025-08-27,16:20,12.8,46.0,7.13,58.14,"TSS, Nuts, DOC, Alk",15.0,34,1.0653,1.1976,58.168,591.10,1.1993,1.1968,non-regular sampling after rain. 500ml bottle ...,16:20:00
369,370,SFP_DW,2025-08-27,16:50,16.1,79.0,6.74,90.87,"TSS, Nuts, DOC, Alk",6.0,"40,6,30,68",3.2981,3.6979,57.163,592.81,4.3957,4.3131,non-regular sampling after rain. 500ml bottle ...,16:50:00
370,371,SFP_Alder_Cr,2025-08-27,17:20,16.8,59.0,6.96,75.36,"TSS, Nuts, DOC, Alk",9.0,"1,HZ,FC20,55,51,44,50,14,17,7,18",11.9665,13.4337,58.226,594.02,17.5004,16.7906,non-regular sampling after rain. 500ml bottle ...,17:20:00

--- Data for Site: 2025-08-29 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
371,372,SFP_Alder_Cr,2025-08-29,12:05,15.26,65.0,7.16,65.66,"TSS, Nuts, DOC, Alk",2.0,45,1.1008,1.2338,88.56,1142.10,1.2937,1.2849,,12:05:00
372,373,SFP_DW,2025-08-29,11:30,14.06,91.0,6.76,92.74,"TSS, Nuts, DOC, Alk",4.0,1,1.0840,1.2171,87.64,1130.54,1.2959,1.2845,,11:30:00
373,374,BJ_Cr,2025-08-29,10:45,8.13,51.0,7.13,52.19,"TSS, Nuts, DOC, Alk",6.0,FC11,1.0792,1.2128,87.45,1057.64,1.2148,1.2125,,10:45:00
374,375,SFP_BJ,2025-08-29,10:30,10.47,86.0,6.92,87.35,"TSS, Nuts, DOC, Alk",3.0,23,1.1025,1.2343,88.19,1158.74,1.2981,1.2911,,10:30:00
375,376,Warm_Sp,2025-08-29,10:10,10.91,102.0,6.79,102.30,"TSS, Nuts, DOC, Alk",5.0,32,1.0790,1.2125,88.39,1147.76,1.2909,1.2825,,10:10:00
376,377,SFP_Chap,2025-08-29,10:00,9.99,80.0,6.61,82.00,"TSS, Nuts, DOC, Alk",7.0,10,1.0827,1.2146,89.00,1144.90,1.2663,1.2597,,10:00:00
377,378,Fox_Cr,2025-08-29,12:35,13.54,190.0,6.85,192.50,"TSS, Nuts, DOC, Alk",13.0,58,1.0831,1.2157,88.36,1030.99,1.2216,1.2191,,12:35:00
378,379,SFP_Wolf_Cr,2025-08-29,12:45,13.14,79.0,6.90,79.97,"TSS, Nuts, DOC, Alk",12.0,2,1.0981,1.2310,87.88,1104.77,1.2915,1.2828,,12:45:00
379,380,Canyon_Cr_SFP,2025-08-29,12:15,10.29,99.0,6.92,100.40,"TSS, Nuts, DOC, Alk",15.0,4,1.1051,1.2377,88.24,1149.05,1.3929,1.3696,,12:15:00
380,381,SFP_Canyon_Cr,2025-08-29,12:20,12.79,69.0,6.58,66.98,"TSS, Nuts, DOC, Alk",14.0,43,1.0967,1.2298,88.51,1146.87,1.2599,1.2561,,12:20:00
381,382,Camp_Cr,2025-08-29,11:45,11.78,72.0,7.14,73.22,"TSS, Nuts, DOC, Alk",16.0,33,1.1073,1.2397,88.45,1140.78,1.2457,1.2436,,11:45:00
382,383,SH_Cr,2025-08-29,11:35,12.95,61.0,6.94,61.85,"TSS, Nuts, DOC, Alk",17.0,27,1.1006,1.2335,88.73,1152.67,1.2418,1.2398,,11:35:00
383,384,HP,2025-08-29,13:10,10.92,93.0,6.89,93.42,"TSS, Nuts, DOC, Alk",11.0,51,1.0628,1.1960,88.08,1152.99,1.4160,1.3946,,13:10:00
384,385,Avalanche_Cr,2025-08-29,16:26,14.50,119.0,6.62,119.30,"TSS, Nuts, DOC, Alk",10.0,12,1.0663,1.1994,88.57,1137.31,1.4141,1.2723,,16:26:00
385,386,GO_Cr,2025-08-29,16:45,10.56,133.0,6.85,134.30,"TSS, Nuts, DOC, Alk",8.0,31,1.0942,1.2278,88.50,1078.62,1.2482,1.2456,,16:45:00
386,387,SFP_Wapiti,2025-08-29,11:15,11.34,66.0,6.64,68.09,"TSS, Nuts, DOC, Alk",18.0,29,1.1171,1.2510,87.84,1148.58,1.2789,1.2752,,11:15:00
387,388,Wapiti_Cr,2025-08-29,18:28,9.86,82.0,6.92,82.51,"TSS, Nuts, DOC, Alk",9.0,39,1.1009,1.2344,88.35,1157.55,1.2411,1.2371,,18:28:00
388,389,Bear_Cr,2025-08-29,11:25,11.97,90.0,6.65,90.08,"TSS, Nuts, DOC, Alk",19.0,5,1.0894,1.2221,89.61,1145.66,1.2232,1.2223,,11:25:00
389,390,Canyon_Cr_Banner,2025-08-29,13:41,11.39,98.0,6.69,98.72,TSS,20.0,16,1.0960,1.2290,87.72,1075.40,1.2376,1.2357,site added 8/29.,13:41:00
390,391,Canyon_Cr_DF_1,2025-08-29,14:05,12.04,106.0,6.72,106.70,TSS,21.0,38,1.0982,1.2297,105.86,1109.75,1.2820,1.3885,site added 8/29. TSS in brown bottles,14:05:00
391,392,Canyon_Cr_DF_3,2025-08-29,14:45,12.79,119.0,6.77,115.80,TSS,22.0,25,1.0984,1.2311,104.35,1133.14,1.5372,1.4835,site added 8/29. TSS in brown bottles. This mi...,14:45:00

--- Data for Site: 2025-09-12 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
392,393,Wapiti_Cr,2025-09-12,11:40,6.68,81.0,6.40,84.08,"TSS, Nuts, DOC, Alk",4.0,11,1.0851,1.2160,102.53,1032.60,1.2217,1.2183,,11:40:00
393,394,SFP_Wapiti,2025-09-12,12:00,10.01,72.0,7.14,72.43,"TSS, Nuts, DOC, Alk",7.0,20,1.0613,1.1940,104.97,1138.68,1.1971,1.1964,,12:00:00
394,395,Bear_Cr,2025-09-12,12:10,9.39,91.0,6.85,91.52,"TSS, Nuts, DOC, Alk",8.0,40,1.1056,1.2374,101.89,1152.41,1.2396,1.2380,,12:10:00
395,396,SH_Cr,2025-09-12,12:20,10.64,60.0,6.61,60.84,"TSS, Nuts, DOC, Alk",3.0,28,1.1077,1.2394,103.18,1089.71,1.2460,1.2444,,12:20:00
396,397,Camp_Cr,2025-09-12,12:30,9.98,72.0,6.50,72.18,"TSS, Nuts, DOC, Alk",15.0,53,1.0851,1.2182,106.69,1128.06,1.2243,1.2226,,12:30:00
397,398,Canyon_Cr_SFP,2025-09-12,12:45,8.70,102.0,6.63,103.00,"TSS, Nuts, DOC, Alk",2.0,1,1.0758,1.2072,106.05,1119.50,1.2259,1.2233,,12:45:00
398,399,SFP_Canyon_Cr,2025-09-12,12:50,10.86,74.0,7.02,73.89,"TSS, Nuts, DOC, Alk",14.0,59,1.0919,1.2238,101.51,1158.76,1.2277,1.2261,,12:50:00
399,400,Fox_Cr,2025-09-12,13:05,11.29,184.0,6.60,186.80,"TSS, Nuts, DOC, Alk",11.0,47,1.0967,1.2289,102.55,1136.36,1.2352,1.2329,,13:05:00
400,401,SFP_Wolf_Cr,2025-09-12,13:20,11.66,85.0,6.72,84.45,"TSS, Nuts, DOC, Alk",12.0,9,1.0635,1.1972,101.56,1081.57,1.2026,1.2011,,13:20:00
401,402,GO_Cr,2025-09-12,13:40,13.14,132.0,6.80,132.80,"TSS, Nuts, DOC, Alk",16.0,37,1.0809,1.2135,102.63,1111.06,1.2235,1.2208,,13:40:00
402,403,Avalanche_Cr,2025-09-12,14:00,12.62,129.0,6.58,131.90,"TSS, Nuts, DOC, Alk",5.0,57,1.0785,1.2117,88.38,NaN,1.2612,1.2587,forgot to weigh full bottle.,14:00:00
403,404,HP,2025-09-12,14:15,9.03,96.0,6.46,98.32,"TSS, Nuts, DOC, Alk",19.0,34,1.0647,1.1973,89.62,NaN,1.2256,1.2167,forgot to weigh full bottle.,14:15:00
404,405,SFP_Chap,2025-09-12,17:15,13.40,84.0,6.25,86.68,"TSS, Nuts, DOC, Alk",13.0,18,1.1108,1.2421,88.34,NaN,1.2478,1.2468,forgot to weigh full bottle.,17:15:00
405,406,Warm_Sp,2025-09-12,17:25,14.53,103.0,6.53,104.20,"TSS, Nuts, DOC, Alk",17.0,46,1.1005,1.2333,88.73,1157.88,1.2437,1.2410,,17:25:00
406,407,SFP_BJ,2025-09-12,17:40,13.66,91.0,6.43,93.16,"TSS, Nuts, DOC, Alk",10.0,13,1.0640,1.1954,87.57,1153.48,1.2036,1.2021,,17:40:00
407,408,BJ_Cr,2025-09-12,17:50,9.14,51.0,6.32,53.56,"TSS, Nuts, DOC, Alk",6.0,49,1.0879,1.2194,87.45,NaN,1.2222,1.2205,forgot to weigh full bottle.,17:50:00
408,409,SFP_DW,2025-09-12,18:26,14.22,96.0,6.30,96.69,"TSS, Nuts, DOC, Alk",9.0,48,1.0988,1.2314,88.34,1146.89,1.2381,1.2365,the tin number label looks like H8,18:26:00
409,410,SFP_Alder_Cr,2025-09-12,18:55,14.72,102.0,6.65,103.50,"TSS, Nuts, DOC, Alk",1.0,14,1.0762,1.2090,88.38,1153.68,1.2136,1.2125,,18:55:00
410,411,Canyon_Cr_Banner,2025-09-12,16:15,9.18,96.0,6.93,97.46,TSS,20.0,2,1.0974,1.2301,102.85,1090.46,NaN,1.2323,Forgot to weigh sed before ashing. Furthest up...,16:15:00
411,412,Canyon_Cr_DF2,2025-09-12,16:25,9.63,103.0,6.82,101.50,TSS,24.0,32,1.0786,1.2118,102.82,1034.33,NaN,1.2427,Forgot to weigh sed before ashing.,16:25:00
412,413,Canyon_Cr_DF8,2025-09-12,14:55,9.29,107.0,6.89,110.70,TSS,21.0,FC11,1.0786,1.2111,102.41,1091.29,NaN,1.3273,Forgot to weigh sed before ashing. site first ...,14:55:00
413,414,Canyon_Cr_DF5,2025-09-12,15:35,9.94,105.0,7.00,86.98,TSS,22.0,5,1.0887,1.2218,105.10,1039.92,NaN,1.2378,Forgot to weigh sed before ashing. site first ...,15:35:00
414,415,Canyon_Cr_DF4,2025-09-12,15:50,10.78,114.0,6.97,112.20,TSS,23.0,39,1.1011,1.2349,102.79,1146.36,NaN,1.2475,Forgot to weigh sed before ashing. site first ...,15:50:00
415,416,Canyon_Cr_slump1,2025-09-12,14:45,9.78,115.0,6.94,113.40,TSS,25.0,31,1.0939,1.2258,102.87,1142.19,NaN,1.2773,Forgot to weigh sed before ashing. site first ...,14:45:00

--- Data for Site: 2025-09-26 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
416,417,SFP_Wapiti,2025-09-26,15:25,13.00,75.0,7.23,69.31,"TSS, Nuts, DOC, Alk",12.0,1,1.0846,1.2175,87.88,1119.34,1.2207,1.2202,,15:25:00
417,418,Bear_Cr,2025-09-26,15:10,13.80,92.0,6.48,89.31,"TSS, Nuts, DOC, Alk",6.0,17,1.0912,1.2254,87.46,1133.43,1.2273,1.2262,,15:10:00
418,419,SH_Cr,2025-09-26,15:45,14.55,61.0,6.60,60.72,"TSS, Nuts, DOC, Alk",20.0,6,1.1035,1.2371,88.28,1048.12,1.2443,1.2425,,15:45:00
419,420,Camp_Cr,2025-09-26,15:55,12.90,72.0,6.47,68.03,"TSS, Nuts, DOC, Alk",24.0,58,1.0833,1.2164,87.73,1118.11,1.2267,1.2247,,15:55:00
420,421,Canyon_Cr_SFP,2025-09-26,16:10,10.98,104.0,6.50,102.10,"TSS, Nuts, DOC, Alk",2.0,45,1.1012,1.2346,88.81,1101.35,1.2422,1.2403,,16:10:00
421,422,SFP_Canyon_Cr,2025-09-26,16:20,13.31,77.0,6.45,75.82,"TSS, Nuts, DOC, Alk",19.0,27,1.1009,1.2356,87.47,1081.66,1.2383,1.2367,,16:20:00
422,423,Fox_Cr,2025-09-26,16:35,12.25,188.0,6.98,184.60,"TSS, Nuts, DOC, Alk",1.0,44,1.0914,1.2247,88.40,1080.69,1.2335,1.2304,,16:35:00
423,424,SFP_Wolf_Cr,2025-09-26,16:45,13.35,87.0,6.68,83.95,"TSS, Nuts, DOC, Alk",13.0,23,1.1024,1.2349,88.36,1092.88,1.2384,1.2378,,16:45:00
424,425,GO_Cr,2025-09-26,14:20,11.06,131.0,6.88,128.60,"TSS, Nuts, DOC, Alk",17.0,51,1.0620,1.1954,88.74,1069.60,1.2043,1.2017,,14:20:00
425,426,Avalanche_Cr,2025-09-26,14:05,11.88,129.0,6.55,125.90,"TSS, Nuts, DOC, Alk",15.0,29,1.1163,1.2492,88.50,1136.80,1.2561,1.2546,,14:05:00
426,427,HP,2025-09-26,13:40,9.50,97.0,6.57,96.27,"TSS, Nuts, DOC, Alk",3.0,FC20,1.1174,1.2494,88.20,1111.12,1.2557,1.2550,,13:40:00
427,428,SFP_Chap,2025-09-26,17:10,13.14,87.0,6.63,84.98,"TSS, Nuts, DOC, Alk",8.0,55,1.0942,1.2267,88.51,1090.22,1.2302,1.2284,,17:10:00
428,429,Warm_Sp,2025-09-26,17:25,14.47,110.0,6.57,107.50,"TSS, Nuts, DOC, Alk",9.0,10,1.0821,1.2152,88.36,1108.05,1.2202,1.2189,,17:25:00
429,430,SFP_BJ,2025-09-26,17:40,13.21,94.0,6.63,92.57,"TSS, Nuts, DOC, Alk",14.0,7,1.0826,1.2154,88.52,1119.17,1.2190,1.2183,,17:40:00
430,431,BJ_Cr,2025-09-26,17:50,8.52,52.0,6.38,48.37,"TSS, Nuts, DOC, Alk",18.0,36,1.0804,1.2146,87.84,1103.23,1.2176,1.2160,,17:50:00
431,432,SFP_DW,2025-09-26,18:30,12.77,99.0,6.27,97.29,"TSS, Nuts, DOC, Alk",16.0,12,1.0664,1.1994,88.46,1083.70,1.2035,1.2026,,18:30:00
432,433,SFP_Alder_Cr,2025-09-26,19:00,13.70,105.0,6.58,104.20,"TSS, Nuts, DOC, Alk",5.0,41,1.0622,1.1954,88.38,1123.35,1.1985,1.1969,,19:00:00
433,434,Canyon_Cr_Banner,2025-09-26,11:15,5.75,95.0,6.50,94.60,"TSS, Nuts, DOC, Alk",10.0,38,1.0942,1.2267,87.58,1076.76,1.2337,1.2329,,11:15:00
434,435,Canyon_Cr_DF2,2025-09-26,11:30,6.58,101.0,6.61,101.20,"TSS, Nuts, DOC, Alk",4.0,HZ,1.0691,1.2011,87.91,1099.57,1.2064,1.2046,,11:30:00
435,436,Canyon_Cr_DF8,2025-09-26,13:05,10.77,116.0,6.46,113.90,"TSS, Nuts, DOC, Alk",21.0,43,1.0959,1.2296,88.83,1106.01,1.2375,1.2360,,13:05:00
436,437,Canyon_Cr_DF5,2025-09-26,12:20,8.46,107.0,6.54,105.80,"TSS, Nuts, DOC, Alk",23.0,16,1.0965,1.2291,88.81,1084.96,1.2327,1.2320,,12:20:00
437,438,Canyon_Cr_DF4,2025-09-26,11:50,8.58,114.0,6.98,111.00,"TSS, Nuts, DOC, Alk",11.0,33,1.1071,1.2400,88.07,1061.91,1.2444,1.2434,,11:50:00
438,439,Canyon_Cr_slump1,2025-09-26,13:30,10.98,116.0,6.55,114.50,"TSS, Nuts, DOC, Alk",22.0,8,1.1067,1.2392,89.61,1105.27,1.2467,1.2458,,13:30:00

--- Data for Site: 2025-10-04 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
439,440,SFP_DW,2025-10-04,09:10,10.42,92.0,7.76,93.92,TSS,1.0,47,1.0972,1.2298,88.40,1107.13,1.3175,1.3074,non-regular sampling after 10/03 rain.,09:10:00
440,441,BJ_Cr,2025-10-04,09:40,7.00,53.0,7.98,48.67,TSS,17.0,5,1.0895,1.2219,88.73,1093.84,1.2236,1.2223,non-regular sampling after 10/03 rain.,09:40:00
441,442,SFP_BJ,2025-10-04,09:50,8.99,88.0,7.95,89.91,TSS,11.0,48,1.0992,1.2314,88.73,1081.82,1.2977,1.2915,non-regular sampling after 10/03 rain.,09:50:00
442,443,Warm_Sp,2025-10-04,10:05,9.86,103.0,8.31,105.10,TSS,16.0,20,1.0620,1.1950,88.46,1116.93,1.2588,1.2549,non-regular sampling after 10/03 rain.,10:05:00
443,444,SFP_Chap,2025-10-04,10:15,8.53,82.0,7.45,82.90,TSS,3.0,59,1.0927,1.2262,88.20,1120.05,1.2764,1.2706,non-regular sampling after 10/03 rain.,10:15:00
444,445,Fox_Cr,2025-10-04,10:30,8.99,186.0,7.93,187.40,TSS,10.0,25,1.0983,1.2313,87.58,1090.86,1.2420,1.2391,non-regular sampling after 10/03 rain.,10:30:00
445,446,SFP_Wolf_Cr,2025-10-04,10:35,8.71,82.0,8.22,84.34,TSS,18.0,4,1.1053,1.2381,87.83,1118.06,1.2863,1.2808,non-regular sampling after 10/03 rain.,10:35:00
446,447,Canyon_Cr_SFP,2025-10-04,10:50,7.36,106.0,7.73,112.30,TSS,5.0,11,1.0857,1.2195,88.39,1107.52,1.4080,1.3886,non-regular sampling after 10/03 rain.,10:50:00
447,448,SFP_Canyon_Cr,2025-10-04,10:55,9.12,71.0,8.04,72.54,TSS,22.0,40,1.1066,1.2403,89.61,1115.18,1.2507,1.2491,non-regular sampling after 10/03 rain.,10:55:00
448,449,SH_Cr,2025-10-04,11:05,8.55,62.0,8.03,65.05,TSS,21.0,39,1.1019,1.2347,88.83,1088.59,1.3290,1.3231,non-regular sampling after 10/03 rain.,11:05:00
449,450,Camp_Cr,2025-10-04,11:10,8.27,75.0,7.85,83.38,TSS,2.0,68,1.0944,1.2264,88.80,1091.00,1.2308,1.2286,non-regular sampling after 10/03 rain.,11:10:00
450,451,Bear_Cr,2025-10-04,11:20,8.94,94.0,7.79,112.40,TSS,24.0,34,1.0655,1.1982,87.73,1099.97,1.2006,1.1995,non-regular sampling after 10/03 rain.,11:20:00
451,452,SFP_Wapiti,2025-10-04,11:25,9.46,68.0,7.40,69.70,TSS,13.0,18,1.1117,1.2445,88.35,1106.54,1.2537,1.2524,non-regular sampling after 10/03 rain.,11:25:00
452,453,Wapiti_Cr,2025-10-04,16:40,7.53,67.0,7.91,83.07,TSS,19.0,13,1.0649,1.1979,87.47,1114.14,1.2112,1.2089,non-regular sampling after 10/03 rain.,16:40:00
453,454,SFP_Alder_Cr,2025-10-04,09:30,NaN,NaN,7.39,79.53,TSS,25.0,"57,FC11",2.1578,2.4245,102.86,1080.07,2.7736,2.7305,non-regular sampling after 10/03 rain.,09:30:00

--- Data for Site: 2025-10-05 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
454,455,Chapman_Cr,2025-10-05,12:40,6.49,106.0,7.67,89.74,TSS,20.0,53,1.0857,1.2195,88.28,1038.67,1.2725,1.2665,non-regular sampling after 10/03 rain.,12:40:00

--- Data for Site: 2025-10-10 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
455,456,SFP_DW,2025-10-10,11:00,8.46,97.0,8.20,98.03,"TSS, Nuts, DOC, Alk",19.0,FC10,1.1065,1.2387,87.46,1091.11,1.2497,1.2475,,11:00:00
456,457,SFP_Wapiti,2025-10-10,12:20,9.15,73.0,8.09,78.54,"TSS, Nuts, DOC, Alk",5.0,FC13,1.0695,1.2020,88.38,1068.99,1.2048,1.2048,,12:20:00
457,458,Bear_Cr,2025-10-10,12:30,9.96,93.0,7.85,91.83,"TSS, Nuts, DOC, Alk",9.0,FC4,1.0584,1.1915,88.34,1033.75,1.1934,1.1934,,12:30:00
458,459,SH_Cr,2025-10-10,12:45,10.48,61.0,7.79,60.22,"TSS, Nuts, DOC, Alk",11.0,FC12,1.0878,1.2205,88.06,1096.30,1.2605,1.2572,,12:45:00
459,460,Camp_Cr,2025-10-10,12:50,10.17,75.0,7.49,77.56,"TSS, Nuts, DOC, Alk",2.0,FC14,1.0817,1.2144,88.80,1119.55,1.2241,1.2221,,12:50:00
460,461,Canyon_Cr_SFP,2025-10-10,13:05,8.64,105.0,7.62,106.30,"TSS, Nuts, DOC, Alk",12.0,FC16,1.0704,1.2020,87.88,1113.98,1.2580,1.2529,,13:05:00
461,462,SFP_Canyon_Cr,2025-10-10,13:15,9.61,76.0,7.45,80.83,"TSS, Nuts, DOC, Alk",3.0,FC18,1.0527,1.1849,88.20,1114.13,1.1882,1.1885,,13:15:00
462,463,Fox_Cr,2025-10-10,13:30,10.31,180.0,7.79,183.60,"TSS, Nuts, DOC, Alk",1.0,1,1.0760,1.2094,88.39,1112.15,1.2150,1.2135,,13:30:00
463,464,SFP_Wolf_Cr,2025-10-10,13:45,10.55,86.0,8.11,86.46,"TSS, Nuts, DOC, Alk",16.0,49,1.0874,1.2215,88.46,1114.79,1.2337,1.2329,,13:45:00
464,465,Canyon_Cr_Banner,2025-10-10,14:25,8.39,90.0,7.47,97.86,TSS,21.0,R21,1.1077,1.2385,88.83,1101.57,1.2424,1.2426,,14:25:00
465,466,Canyon_Cr_DF5,2025-10-10,14:45,11.01,108.0,7.87,109.00,TSS,22.0,FC19,1.0682,1.2003,89.74,1117.40,1.2128,1.2110,,14:45:00
466,467,Canyon_Cr_slump1,2025-10-10,15:05,11.03,122.0,7.75,120.60,"TSS,DOC",15.0,2,1.0976,1.2298,88.49,1113.33,1.3056,1.2974,,15:05:00
467,468,HP,2025-10-10,15:15,9.73,97.0,7.97,96.05,"TSS, Nuts, DOC, Alk",6.0,9,1.0636,1.1962,87.45,1119.05,1.2576,1.2535,,15:15:00
468,469,Avalanche_Cr,2025-10-10,15:35,11.36,121.0,7.43,131.80,"TSS, Nuts, DOC, Alk",10.0,28,1.1078,1.2414,87.57,1119.22,1.3137,1.3125,,15:35:00
469,470,GO_Cr,2025-10-10,15:50,10.32,115.0,7.74,133.00,"TSS, Nuts, DOC, Alk",8.0,37,1.0808,1.2136,88.50,1081.19,1.2424,1.2404,,15:50:00
470,471,SFP_Chap,2025-10-10,16:10,11.45,85.0,7.35,86.47,"TSS, Nuts, DOC, Alk",7.0,46,1.1007,1.2326,89.00,1139.29,1.2434,1.2429,,16:10:00
471,472,Warm_Sp,2025-10-10,16:20,13.55,109.0,7.67,109.20,"TSS, Nuts, DOC, Alk",4.0,31,1.0939,1.2265,87.91,1112.58,1.2433,1.2419,,16:20:00
472,473,SFP_BJ,2025-10-10,16:40,11.71,93.0,7.77,92.99,"TSS, Nuts, DOC, Alk",18.0,32,1.0786,1.2102,87.83,1141.43,1.2267,1.2260,,16:40:00
473,474,BJ_Cr,2025-10-10,16:55,8.36,53.0,7.65,53.90,"TSS, Nuts, DOC, Alk",14.0,14,1.0761,1.2083,88.52,1091.57,1.2113,1.2099,,16:55:00
474,475,SFP_Alder_Cr,2025-10-10,18:15,11.60,104.0,8.26,104.30,"TSS, Nuts, DOC, Alk",17.0,FC17,1.0901,1.2220,88.73,1108.92,1.2311,1.2303,,18:15:00

--- Data for Site: 2025-12-04 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
475,476,SFP_Wapiti,2025-12-04,09:50,1.53,73.0,7.38,69.94,"TSS, Nuts, DOC, Alk",8.0,9,1.0634,1.1973,88.54,1121.15,1.2010,1.2001,,09:50:00
476,477,Bear_Cr,2025-12-04,10:10,-0.34,88.0,7.26,83.34,"TSS, Nuts, DOC, Alk",10.0,46,1.1008,1.2344,87.57,1023.01,1.2367,1.2358,,10:10:00
477,478,SH_Cr,2025-12-04,10:25,-0.34,58.0,7.70,56.91,"TSS, Nuts, DOC, Alk",2.0,FC10,1.1068,1.2387,88.85,1077.43,1.2426,1.2419,,10:25:00
478,479,Camp_Cr,2025-12-04,10:40,0.35,73.0,7.54,70.37,"TSS, Nuts, DOC, Alk",17.0,FC4,1.0586,1.1908,88.73,1057.00,1.1929,1.1925,,10:40:00
479,480,Canyon_Cr_SFP,2025-12-04,11:10,-0.29,104.0,7.31,7.16,"TSS, Nuts, DOC, Alk",11.0,FC19,1.0683,1.2004,88.09,1060.58,1.3088,1.3025,lots of coarse organic matter suspended in water.,11:10:00
480,481,SFP_Canyon_Cr,2025-12-04,11:20,1.01,76.0,7.65,71.11,"TSS, Nuts, DOC, Alk",16.0,68,1.0939,1.2276,88.46,1064.47,1.2297,1.2297,,11:20:00
481,482,Fox_Cr,2025-12-04,12:00,-0.33,178.0,7.18,150.30,"TSS, Nuts, DOC, Alk",7.0,18,1.1110,1.2438,89.07,1103.77,1.2552,1.2525,,12:00:00
482,483,SFP_Wolf_Cr,2025-12-04,12:10,0.79,87.0,7.32,79.20,"TSS, Nuts, DOC, Alk",18.0,11,1.0854,1.2169,87.84,1132.30,1.2218,1.2213,,12:10:00
483,484,SFP_Chap,2025-12-04,13:35,0.97,83.0,7.64,80.11,"TSS, Nuts, DOC, Alk",13.0,5,1.0891,1.2231,88.36,1093.40,1.2269,1.2260,slow water,13:35:00
484,485,Warm_Sp,2025-12-04,13:55,5.27,115.0,7.18,102.70,"TSS, Nuts, DOC, Alk",6.0,48,1.0990,1.2322,87.45,1091.36,1.2396,1.2389,,13:55:00
485,486,SFP_BJ,2025-12-04,14:05,1.80,92.0,7.29,87.99,"TSS, Nuts, DOC, Alk",14.0,20,1.0617,1.1938,88.52,1122.37,1.1989,1.1981,,14:05:00
486,487,BJ_Cr,2025-12-04,14:20,1.37,49.0,7.58,50.71,"TSS, Nuts, DOC, Alk",1.0,53,1.0852,1.2176,88.39,1083.29,1.2193,1.2173,,14:20:00
487,488,SFP_DW,2025-12-04,16:00,0.92,90.0,7.38,90.10,"TSS, Nuts, DOC, Alk",12.0,13,1.0644,1.1976,87.89,1114.74,1.2016,1.2009,,16:00:00
488,489,SFP_Alder_Cr,2025-12-04,16:20,1.60,109.0,7.02,94.19,"TSS, Nuts, DOC, Alk",9.0,FC11,1.0787,1.2117,88.34,1129.21,1.2137,1.2130,,16:20:00

--- Data for Site: 2026-02-07 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
489,490,SFP_Alder_Cr,2026-02-07,10:30,NaN,89.0,7.69,75.90,"TSS, Nuts, DOC, Alk",8.0,45,1.1005,1.2326,88.51,1162.78,1.2374,1.2361,Field EC CR800. Notebook values from Omega,10:30:00
490,491,SFP_DW,2026-02-07,11:15,NaN,82.0,6.27,88.67,"TSS, Nuts, DOC, Alk",16.0,43,1.0961,1.2275,88.44,1061.48,1.2305,1.2296,Still need temp,11:15:00
491,492,SH_Cr,2026-02-07,12:20,NaN,54.0,6.37,55.13,"TSS, Nuts, DOC, Alk",6.0,FC13,1.0694,1.2009,87.44,1113.19,1.2125,1.2113,,12:20:00
492,493,Camp_Cr,2026-02-07,12:40,NaN,74.0,6.37,72.53,"TSS, Nuts, DOC, Alk",7.0,FC12,1.0879,1.2206,88.99,1108.68,1.2271,1.2261,,12:40:00
493,494,Canyon_Cr_SFP,2026-02-07,13:35,NaN,101.0,6.39,93.85,"TSS, Nuts, DOC, Alk",10.0,1,1.0761,1.2086,87.56,1139.92,1.3002,1.2990,,13:35:00
494,495,SFP_Canyon_Cr,2026-02-07,13:45,NaN,71.0,6.41,68.38,"TSS, Nuts, DOC, Alk",9.0,HZ,1.0692,1.2023,88.33,1164.74,1.2039,1.2033,,13:45:00
495,496,SFP_Wolf_Cr,2026-02-07,14:30,NaN,84.0,6.37,82.66,"TSS, Nuts, DOC, Alk",3.0,31,1.0942,1.2275,88.18,1113.90,1.2309,1.2297,,14:30:00
496,497,Fox_Cr,2026-02-07,14:45,NaN,134.0,6.32,129.10,"TSS, Nuts, DOC, Alk",4.0,4,1.1045,1.2355,87.89,1086.22,1.2450,1.2423,omega read out as ms,14:45:00
497,498,SFP_Chap,2026-02-07,15:20,NaN,81.0,6.38,78.26,"TSS, Nuts, DOC, Alk",1.0,38,1.0980,1.2285,88.38,1138.92,1.2314,1.2306,,15:20:00
498,499,Warm_Sp,2026-02-07,15:35,NaN,106.0,6.33,103.50,"TSS, Nuts, DOC, Alk",12.0,58,1.0830,1.2172,87.87,1140.60,1.2235,1.2232,,15:35:00
499,500,SFP_BJ,2026-02-07,15:55,NaN,88.0,6.42,85.11,"TSS, Nuts, DOC, Alk",2.0,8,1.1071,1.2414,88.79,1143.46,1.2472,1.2460,,15:55:00
500,501,BJ_Cr,2026-02-07,16:20,NaN,44.0,6.44,47.08,"TSS, Nuts, DOC, Alk",5.0,FC16,1.0707,1.2042,88.36,1110.25,1.2056,1.2038,Not typical site. Sampled above the highway cu...,16:20:00

--- Data for Site: 2026-03-08 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
501,502,SH_Cr,2026-03-08,11:50,4.4,54.0,6.94,78.22,"TSS, Nuts, DOC, Alk",16.0,FC18,1.0533,1.1867,88.45,1089.31,1.1889,1.1880,Field temp and field EC from CRX800. Notebook ...,11:50:00
502,503,Camp_Cr,2026-03-08,12:05,4.7,76.0,NaN,NaN,"Nuts, DOC, Alk",11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no TSS lost lid,12:05:00
503,504,Canyon_Cr_SFP,2026-03-08,12:50,4.0,106.0,6.66,117.10,"TSS, Nuts, DOC, Alk",17.0,47,1.0968,1.2284,88.73,1085.64,1.2432,1.2420,,12:50:00
504,505,SFP_Canyon_Cr,2026-03-08,13:20,5.1,70.0,6.74,84.51,"TSS, Nuts, DOC, Alk",15.0,59,1.0922,1.2258,87.97,1057.31,1.2279,1.2270,,13:20:00
505,506,SFP_Wolf_Cr,2026-03-08,14:15,6.5,78.0,7.07,94.05,"TSS, Nuts, DOC, Alk",14.0,10,1.0828,1.2157,88.50,1088.90,1.2167,1.2162,,14:15:00
506,507,Fox_Cr,2026-03-08,13:55,6.1,124.0,7.14,144.60,"TSS, Nuts, DOC, Alk",13.0,49,1.0885,1.2215,88.33,1085.09,1.2273,1.2267,,13:55:00
507,508,SFP_Chap,2026-03-08,15:00,6.7,81.0,7.07,92.29,"TSS, Nuts, DOC, Alk",7.0,FC17,1.0896,1.2220,89.00,1129.72,1.2232,1.2224,,15:00:00
508,509,Warm_Sp,2026-03-08,15:45,10.2,104.0,7.10,119.40,"TSS, Nuts, DOC, Alk",19.0,14,1.0771,1.2093,87.46,1124.12,1.2126,1.2119,,15:45:00
509,510,SFP_BJ,2026-03-08,16:10,7.5,88.0,7.02,101.00,"TSS, Nuts, DOC, Alk",6.0,25,1.0984,1.2310,87.44,1131.04,1.2338,1.2334,,16:10:00
510,511,BJ_Cr,2026-03-08,16:40,4.7,51.0,7.37,58.85,"TSS, Nuts, Alk",1.0,2,1.0982,1.2308,88.39,1117.64,1.2321,1.2306,DOC bottle leaked during transport,16:40:00
511,512,SFP_DW,2026-03-08,17:35,6.7,87.0,6.83,99.27,"TSS, Nuts, DOC, Alk",18.0,R21,1.1080,1.2397,87.84,1116.28,1.2424,1.2420,,17:35:00
512,513,SFP_Alder_Cr,2026-03-08,18:25,6.5,86.0,7.15,97.88,"TSS, Nuts, DOC, Alk",9.0,28,1.1087,1.2404,88.33,1138.94,1.2436,1.2427,,18:25:00

--- Data for Site: 2026-04-11 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
513,514,HP,2026-04-11,12:45,4.6,74.0,6.87,82.14,"TSS, Nuts, DOC, Alk",4.0,29,1.1165,1.2493,87.89,1136.69,1.5245,1.4969,,12:45:00
514,515,Avalanche_Cr,2026-04-11,13:03,5.7,81.5,6.97,84.60,"TSS, Nuts, DOC, Alk",10.0,FC14,1.0814,1.2143,87.56,1100.03,1.7847,1.7527,,13:03:00
515,516,SFP_Wapiti,2026-04-11,13:40,6.8,52.1,7.42,55.49,"TSS, Nuts, DOC, Alk",3.0,FC20,1.1177,1.2507,88.19,1113.59,1.3184,1.3121,,13:40:00
516,517,Bear_Cr,2026-04-11,13:50,7.0,70.5,7.02,72.15,"TSS, Nuts, DOC, Alk",2.0,16,1.0959,1.2281,89.58,1146.36,1.2586,1.2559,,13:50:00
517,518,SH_Cr,2026-04-11,14:05,6.9,51.7,7.30,53.22,"TSS, Nuts, DOC, Alk",7.0,6,1.1038,1.2356,88.99,1133.58,1.2962,1.2890,,14:05:00
518,519,Camp_Cr,2026-04-11,14:10,6.8,67.5,6.80,67.36,"TSS, Nuts, DOC, Alk",6.0,33,1.1070,1.2388,87.44,1014.60,1.2810,1.2764,,14:10:00
519,520,Canyon_Cr_SFP,2026-04-11,14:30,6.1,84.5,7.72,92.65,"TSS, Nuts, DOC, Alk",11.0,55,1.0944,1.2252,88.87,1077.76,1.5036,1.4796,,14:30:00
520,521,SFP_Canyon_Cr,2026-04-11,14:40,7.1,52.4,7.40,53.81,"TSS, Nuts, DOC, Alk",1.0,7,1.0825,1.2129,88.38,1165.60,1.2906,1.2827,,14:40:00
521,522,Fox_Cr,2026-04-11,14:55,7.7,119.8,6.92,126.50,"TSS, Nuts, DOC, Alk",9.0,51,1.0624,1.1953,88.34,1124.04,1.2249,1.2189,,14:55:00
522,523,SFP_Wolf_Cr,2026-04-11,15:15,7.7,61.1,7.00,68.29,"TSS, Nuts, DOC, Alk",19.0,23,1.1024,1.2356,87.46,1153.40,1.3803,1.3635,,15:15:00
523,524,SFP_Chap,2026-04-11,15:40,7.6,63.6,7.24,65.81,"TSS, Nuts, DOC, Alk",17.0,32,1.0786,1.2103,88.72,1158.18,1.3247,1.3141,,15:40:00
524,525,Warm_Sp,2026-04-11,16:00,7.9,74.8,6.99,78.61,"TSS, Nuts, DOC, Alk",14.0,1,1.0848,1.2170,88.50,1138.09,1.4366,1.4272,,16:00:00
525,526,SFP_BJ,2026-04-11,16:15,7.8,67.8,6.97,69.84,"TSS, Nuts, DOC, Alk",12.0,39,1.1014,1.2348,87.87,1122.36,1.4093,1.3950,,16:15:00
526,527,BJ_Cr,2026-04-11,16:20,6.7,51.2,6.92,52.94,"TSS, Nuts, DOC, Alk",20.0,34,1.0652,1.1972,88.27,1122.96,1.2001,1.1979,,16:20:00
527,528,SFP_DW,2026-04-11,17:10,8.3,66.6,6.91,68.06,"TSS, Nuts, DOC, Alk",13.0,37,1.0808,1.2144,88.34,1133.67,1.3378,1.3242,1 of 2 SFP_DW samples collected from this site...,17:10:00
528,529,SFP_Alder_Cr,2026-04-11,17:45,9.0,64.2,6.95,66.87,"TSS, Nuts, DOC, Alk",15.0,40,1.1063,1.2384,87.97,1128.68,1.3420,1.3284,1 of 2 SFP_Alder samples collected from this s...,17:45:00
529,530,SFP_Alder_Cr_AM,2026-04-11,11:00,9.3,64.9,7.13,68.31,TSS,18.0,27,1.1008,1.2342,87.83,1148.56,1.3014,1.2933,2 of 2 SFP_Alder samples collected to compare ...,11:00:00
530,531,SFP_DW_AM,2026-04-11,11:45,7.5,67.4,7.14,70.58,TSS,8.0,17,1.0917,1.2229,88.51,1153.49,1.3333,1.3199,2 of 2 SFP_DW samples collected compare AM and...,11:45:00

--- Data for Site: 2026-05-11 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
531,532,HP,2026-05-11,12:30,7.8,59.7,6.99,61.99,"TSS, Nuts, DOC, Alk",13.0,FC19,1.0684,1.2008,88.34,1147.86,1.3904,1.3747,lab ec constant 0.911/cm,12:30:00
532,533,Avalanche_Cr,2026-05-11,12:50,9.7,64.7,7.12,67.96,"TSS, Nuts, DOC, Alk",2.0,68,1.0941,1.2286,89.61,1096.01,1.5087,1.4974,,12:50:00
533,534,GO_Cr,2026-05-11,13:05,11.1,58.1,6.87,61.93,"TSS, Nuts, DOC, Alk",11.0,20,1.0617,1.1955,88.85,1089.65,1.4523,1.4307,,13:05:00
534,535,SFP_Wapiti,2026-05-11,13:40,9.2,34.5,7.00,36.33,"TSS, Nuts, DOC, Alk",6.0,FC10,1.1070,1.2397,87.45,1142.85,1.2848,1.2810,,13:40:00
535,536,Bear_Cr,2026-05-11,13:50,12.1,46.6,6.89,54.13,"TSS, Nuts, DOC, Alk",3.0,18,1.1113,1.2436,88.19,1129.71,1.3347,1.3293,,13:50:00
536,537,SH_Cr,2026-05-11,14:05,13.9,39.3,6.91,45.16,"TSS, Nuts, DOC, Alk",8.0,5,1.0890,1.2219,88.53,1074.72,1.4934,1.4806,,14:05:00
537,538,Camp_Cr,2026-05-11,14:15,13.3,61.9,6.90,65.47,"TSS, Nuts, DOC, Alk",1.0,FC11,1.0788,1.2125,88.39,1133.81,1.2270,1.2246,,14:15:00
538,539,Canyon_Cr_SFP,2026-05-11,14:30,10.7,65.8,6.86,68.93,"TSS, Nuts, DOC, Alk",10.0,9,1.0637,1.1960,87.56,1084.02,1.5002,1.4860,,14:30:00
539,540,SFP_Canyon_Cr,2026-05-11,14:35,10.2,27.0,7.06,37.87,"TSS, Nuts, DOC, Alk",7.0,11,1.0857,1.2191,88.99,1139.21,1.2829,1.2788,,14:35:00
540,541,Fox_Cr,2026-05-11,14:55,15.0,126.2,6.73,129.90,"TSS, Nuts, DOC, Alk",4.0,13,1.0646,1.1983,87.89,1120.47,1.2119,1.2094,,14:55:00
541,542,SFP_Wolf_Cr,2026-05-11,15:10,11.0,44.8,6.75,46.64,"TSS, Nuts, DOC, Alk",9.0,53,1.0854,1.2179,88.33,1159.34,1.3328,1.3247,,15:10:00
542,543,SFP_Chap,2026-05-11,15:35,11.2,44.2,7.15,46.49,"TSS, Nuts, DOC, Alk",12.0,FC4,1.0588,1.1917,87.87,1132.07,1.2846,1.2769,,15:35:00
543,544,Warm_Sp,2026-05-11,15:50,11.7,54.4,7.79,57.30,"TSS, Nuts, DOC, Alk",15.0,48,1.0991,1.2317,87.97,1139.53,1.5240,1.5176,,15:50:00
544,545,SFP_BJ,2026-05-11,16:00,11.5,47.6,7.06,50.53,"TSS, Nuts, DOC, Alk",16.0,46,1.1010,1.2336,88.45,1143.06,1.3712,1.3632,,16:00:00
545,546,BJ_Cr,2026-05-11,16:20,10.6,47.9,7.08,50.28,"TSS, Nuts, DOC, Alk",17.0,12,1.0663,1.2000,88.72,1067.11,1.2027,1.2009,,16:20:00
546,547,SFP_DW,2026-05-11,17:40,11.5,48.5,9.26,45.96,"TSS, Nuts, DOC, Alk",14.0,44,1.0917,1.2252,88.51,1137.62,1.3338,1.3266,,17:40:00
547,548,SFP_Alder_Cr,2026-05-11,18:20,11.1,49.9,7.15,53.00,"TSS, Nuts, DOC, Alk",18.0,36,1.0802,1.2127,87.83,1129.44,1.3106,1.3040,,18:20:00

--- Data for Site: 2026-06-13 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
548,549,SFP_Wapiti,2026-06-13,06:45,7.7,39.8,9.29,41.75,"TSS, Nuts, DOC, Alk",12.0,1,1.0764,1.2094,87.87,1157.55,1.2149,1.2139,lab ec constant 0.917/cm,06:45:00
549,550,Bear_Cr,2026-06-13,06:55,6.6,67.7,7.92,71.39,"TSS, Nuts, DOC, Alk",9.0,HZ,1.0696,1.2027,88.33,1142.73,1.2096,1.2088,,06:55:00
550,551,SH_Cr,2026-06-13,07:10,6.6,50.7,6.73,53.83,"TSS, Nuts, DOC, Alk",10.0,38,1.0985,1.2306,87.56,1118.04,1.2342,1.2329,,07:10:00
551,552,Camp_Cr,2026-06-13,07:20,6.4,60.4,6.77,63.89,"TSS, Nuts, DOC, Alk",7.0,45,1.1011,1.2331,88.99,1084.82,1.2420,1.2408,,07:20:00
552,553,Canyon_Cr_SFP,2026-06-13,07:50,6.4,81.4,6.82,85.43,"TSS, Nuts, DOC, Alk",11.0,FC16,1.0711,1.2040,88.85,1122.14,1.2216,1.2198,,07:50:00
553,554,SFP_Canyon_Cr,2026-06-13,08:00,7.6,42.0,7.20,44.92,"TSS, Nuts, DOC, Alk",8.0,FC17,1.0895,1.2224,88.53,1130.53,1.2276,1.2265,,08:00:00
554,555,Fox_Cr,2026-06-13,08:25,8.0,161.9,7.11,172.70,"TSS, Nuts, DOC, Alk",1.0,14,1.0769,1.2100,88.39,1073.72,1.2147,1.2131,,08:25:00
555,556,SFP_Wolf_Cr,2026-06-13,08:35,7.6,52.0,7.29,55.46,"TSS, Nuts, DOC, Alk",6.0,49,1.0884,1.2195,87.45,1112.98,1.2271,1.2257,,08:35:00
556,557,HP,2026-06-13,09:10,5.8,72.7,7.12,76.09,"TSS, Nuts, DOC, Alk",13.0,2,1.0979,1.2308,88.34,1085.25,1.2333,1.2326,,09:10:00
557,558,Avalanche_Cr,2026-06-13,09:25,6.9,93.3,7.00,97.93,"TSS, Nuts, DOC, Alk",17.0,25,1.0984,1.2317,88.72,1136.42,1.2331,1.2323,,09:25:00
558,559,GO_Cr,2026-06-13,09:45,9.2,104.7,7.19,110.10,"TSS, Nuts, DOC, Alk",3.0,4,1.1050,1.2388,88.19,989.96,1.2406,1.2396,,09:45:00
559,560,SFP_Chap,2026-06-13,10:15,8.3,50.8,6.62,53.84,"TSS, Nuts, DOC, Alk",18.0,FC12,1.0885,1.2218,87.83,1133.33,1.2278,1.2265,,10:15:00
560,561,Warm_Sp,2026-06-13,10:30,8.8,71.5,6.75,87.97,"TSS, Nuts, DOC, Alk",2.0,FC13,1.0698,1.2018,89.61,1139.92,1.2057,1.2053,,10:30:00
561,562,SFP_BJ,2026-06-13,10:40,8.7,58.4,7.41,61.88,"TSS, Nuts, DOC, Alk",14.0,47,1.0969,1.2300,88.51,1116.70,1.2380,1.2370,,10:40:00
562,563,BJ_Cr,2026-06-13,11:00,7.0,48.9,7.22,51.67,"TSS, Nuts, DOC, Alk",4.0,8,1.1073,1.2399,87.89,1102.14,1.2420,1.2400,,11:00:00
563,564,SFP_DW,2026-06-13,11:30,10.8,63.8,7.52,67.44,"TSS, Nuts, DOC, Alk",15.0,R21,1.1079,1.2410,87.97,1140.07,1.2508,1.2495,,11:30:00
564,565,SFP_Alder_Cr,2026-06-13,12:05,13.3,64.5,7.18,68.01,"TSS, Nuts, DOC, Alk",16.0,31,1.0946,1.2273,88.45,1136.51,1.2391,1.2375,,12:05:00

--- Data for Site: 2026-07-10 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
565,566,SFP_Wapiti,2026-07-10,08:10,10.1,41.9,7.48,51.34,"TSS, Nuts, DOC, Alk",12.0,RC15,1.1023,1.2354,87.88,1090.31,1.2379,1.2364,lab ec constant 0.947/cm,08:10:00
566,567,Bear_Cr,2026-07-10,08:20,9.4,78.6,7.29,84.71,"TSS, Nuts, DOC, Alk",19.0,32,1.0790,1.1959,87.47,1070.79,1.1984,1.1980,Whatman GF/F 934-AH used for TSS,08:20:00
567,568,SH_Cr,2026-07-10,08:35,10.9,55.3,7.26,60.33,"TSS, Nuts, DOC, Alk",8.0,41,1.0622,1.1952,88.54,1073.92,1.1985,1.1975,,08:35:00
568,569,Camp_Cr,2026-07-10,08:45,9.2,64.6,7.48,69.85,"TSS, Nuts, DOC, Alk",11.0,RC8,1.0730,1.2062,88.86,1102.53,1.2120,1.2105,,08:45:00
569,570,Canyon_Cr_SFP,2026-07-10,09:00,8.5,84.5,7.08,97.83,"TSS, Nuts, DOC, Alk",16.0,FC9,1.0899,1.2231,88.47,1131.77,1.2334,1.2315,,09:00:00
570,571,SFP_Canyon_Cr,2026-07-10,09:05,10.5,49.0,7.54,53.30,"TSS, Nuts, DOC, Alk",6.0,FC15,1.1078,1.2419,87.46,1138.26,1.2449,1.2439,,09:05:00
571,572,Fox_Cr,2026-07-10,09:25,11.3,178.3,7.24,192.10,"TSS, Nuts, DOC, Alk",2.0,FC29,0.9507,1.0847,89.62,1097.08,1.0885,1.0873,,09:25:00
572,573,SFP_Wolf_Cr,2026-07-10,09:40,10.7,59.7,7.45,64.87,"TSS, Nuts, DOC, Alk",20.0,FC18,1.0528,1.1851,88.29,1140.23,1.1890,1.1883,,09:40:00
573,574,HP,2026-07-10,10:15,8.5,80.4,7.37,86.55,"TSS, Nuts, DOC, Alk",15.0,59,1.0921,1.2242,87.99,1126.26,1.2276,1.2264,,10:15:00
574,575,Avalanche_Cr,2026-07-10,10:35,10.4,105.8,7.43,115.50,"TSS, Nuts, DOC, Alk",4.0,4,1.0820,1.2142,87.91,1117.66,1.2158,1.2151,,10:35:00
575,576,GO_Cr,2026-07-10,10:55,13.7,117.9,6.91,127.90,"TSS, Nuts, DOC, Alk",1.0,FC27,1.1118,1.2441,88.40,1074.02,1.2464,1.2452,,10:55:00
576,577,SFP_Chap,2026-07-10,11:20,11.7,55.2,7.54,64.03,"TSS, Nuts, DOC, Alk",3.0,43,1.0964,1.2288,88.21,1110.36,1.2333,1.2321,,11:20:00
577,578,Warm_Sp,2026-07-10,11:35,12.6,87.4,7.36,103.70,"TSS, Nuts, DOC, Alk",9.0,10,1.0823,1.2150,88.36,1142.65,1.2210,1.2202,,11:35:00
578,579,SFP_BJ,2026-07-10,11:45,12.2,66.9,7.49,72.38,"TSS, Nuts, DOC, Alk",7.0,58,1.0832,1.2160,89.02,1126.49,1.2221,1.2209,,11:45:00
579,580,BJ_Cr,2026-07-10,12:00,9.0,50.2,7.58,54.50,"TSS, Nuts, DOC, Alk",10.0,7,1.0829,1.2000,87.57,1008.27,1.2014,1.2002,Whatman GF/F 934-AH used for TSS,12:00:00
580,581,SFP_DW,2026-07-10,12:35,15.6,73.0,7.21,78.21,"TSS, Nuts, DOC, Alk",18.0,FC26,1.0796,1.2120,87.85,1120.90,1.2176,1.2158,,12:35:00
581,582,SFP_Alder_Cr,2026-07-10,13:10,17.3,69.8,7.19,75.18,"TSS, Nuts, DOC, Alk",14.0,28,1.1083,1.2417,88.52,1136.94,1.2797,1.2755,,13:10:00

--- Data for Site: 2026-07-31 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
582,583,SFP_Wapiti,2026-07-31,08:50,11.4,46.1,6.85,66.04,"TSS, Nuts, Alk",15.0,HZ,1.0700,1.1874,87.95,1124.17,1.3474,1.3412,non-regular sampling following 07/22 debris fl...,08:50:00
583,584,Bear_Cr,2026-07-31,09:00,10.6,88.6,7.15,92.61,"TSS, Nuts, Alk",12.0,FC20,1.1183,1.2352,87.89,1111.53,1.3253,1.3233,Whatman GF/F 934-AH used for TSS,09:00:00
584,585,SH_Cr,2026-07-31,09:40,12.5,54.9,6.92,60.65,"TSS, Nuts, DOC, Alk",17.0,FC14,1.0819,1.1995,88.33,1081.08,1.2013,1.2005,Whatman GF/F 934-AH used for DOC/TSS,09:40:00
585,586,Camp_Cr,2026-07-31,09:55,10.6,67.1,6.97,70.39,"TSS, Nuts, DOC, Alk",4.0,27,1.1011,1.2195,87.91,1112.95,1.2223,1.2216,Whatman GF/F 934-AH used for DOC/TSS,09:55:00
586,587,Canyon_Cr_SFP,2026-07-31,10:10,9.6,98.1,5.90,102.90,"TSS, Nuts, DOC, Alk",1.0,47,1.0971,1.2147,88.38,1128.62,1.3356,1.3293,Whatman GF/F 934-AH used for DOC/TSS,10:10:00
587,588,SFP_Canyon_Cr,2026-07-31,10:15,12.3,66.0,6.90,69.41,"TSS, Nuts, Alk",8.0,34,1.0656,1.1827,88.53,1116.02,2.0069,1.9983,Whatman GF/F 934-AH used for TSS,10:15:00
588,589,Fox_Cr,2026-07-31,10:30,13.2,186.2,6.40,194.80,"TSS, Nuts, Alk",9.0,37,1.0813,1.1982,88.35,1092.37,1.1996,1.1990,Whatman GF/F 934-AH used for TSS,10:30:00
589,590,SFP_Wolf_Cr,2026-07-31,10:40,12.5,76.2,6.70,80.94,"TSS, Nuts, DOC, Alk",6.0,6,1.1045,1.2221,87.43,1126.54,1.6601,1.6520,Whatman GF/F 934-AH used for DOC/TSS,10:40:00
590,591,HP,2026-07-31,11:10,11.0,90.1,6.18,94.80,"TSS, Nuts, Alk",18.0,51,1.0628,1.1792,87.84,1132.66,1.3256,1.3218,Whatman GF/F 934-AH used for TSS,11:10:00
591,592,Avalanche_Cr,2026-07-31,11:30,12.6,114.7,6.83,120.00,"TSS, Nuts, Alk",20.0,16,1.0968,1.2136,88.27,1140.21,1.2139,1.2137,Whatman GF/F 934-AH used for TSS,11:30:00
592,593,GO_Cr,2026-07-31,11:45,15.4,124.0,7.02,130.40,"TSS, Nuts, Alk",13.0,17,1.0920,1.2084,88.71,1069.70,1.2104,1.2098,Whatman GF/F 934-AH used for TSS,11:45:00
593,594,SFP_Chap,2026-07-31,12:05,13.9,61.3,7.11,79.13,"TSS, Nuts, Alk",19.0,23,1.1028,1.2193,87.45,1107.85,1.4712,1.4635,Whatman GF/F 934-AH used for TSS,12:05:00
594,595,Warm_Sp,2026-07-31,12:20,14.8,105.0,6.74,109.00,"TSS, Nuts, Alk",16.0,39,1.1017,1.2184,88.44,1098.37,1.2198,1.2196,Whatman GF/F 934-AH used for TSS,12:20:00
595,596,SFP_BJ,2026-07-31,12:30,14.2,83.7,6.81,87.37,"TSS, Nuts, Alk",10.0,29,1.1171,1.2347,87.53,1106.06,2.5702,2.5598,Whatman GF/F 934-AH used for TSS,12:30:00
596,597,BJ_Cr,2026-07-31,13:00,10.8,50.3,7.21,53.60,"TSS, Nuts, DOC, Alk",7.0,1,1.0848,1.2008,88.99,1089.76,1.2033,1.2018,Whatman GF/F 934-AH used for DOC/TSS,13:00:00
597,598,SFP_DW,2026-07-31,13:35,18.0,88.9,7.00,92.43,"TSS, Nuts, DOC,Alk",11.0,55,1.0942,1.2101,88.86,1119.81,1.3147,1.3078,Whatman GF/F 934-AH used for DOC/TSS,13:35:00
598,599,SFP_Alder_Cr,2026-07-31,14:05,14.8,63.0,7.19,66.43,"TSS, Nuts, Alk",14.0,33,1.1068,1.2232,88.53,1108.81,1.2699,1.2660,Whatman GF/F 934-AH used for TSS,14:05:00

--- Data for Site: 2026-08-06 00:00:00 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
599,600,SFP_Wapiti,2026-08-06,07:50,10.2,66.1,7.44,70.10,"TSS, Nuts, Alk",7.0,25,1.0984,1.2248,89.01,1074.28,1.3017,1.3002,duplicate TSS bottle labled site 7. lab EC cel...,07:50:00
600,601,Bear_Cr,2026-08-06,08:05,8.7,87.5,7.42,95.30,"TSS, Nuts, Alk",18.0,FC12,1.0886,1.2146,87.84,1130.70,1.2367,1.2355,duplicate TSS bottle labled site 18,08:05:00
601,602,SH_Cr,2026-08-06,08:20,10.6,58.1,7.35,61.72,"TSS, Nuts, Alk",13.0,FC17,1.0896,1.2162,88.73,1100.74,1.2174,1.2170,duplicate TSS bottle labled site 13,08:20:00
602,603,Camp_Cr,2026-08-06,08:30,9.2,67.8,7.31,71.39,"TSS, Nuts, Alk",10.0,FC26,1.0796,1.2072,87.53,1112.36,1.2102,1.2093,no duplicate TSS,08:30:00
603,604,Canyon_Cr_SFP,2026-08-06,08:45,8.2,93.0,7.33,106.90,"TSS, Nuts, Alk",6.0,2,1.0979,1.2243,87.45,1060.33,1.2941,1.2907,duplicate TSS bottle labeled site 6,08:45:00
604,605,SFP_Canyon_Cr,2026-08-06,08:50,10.1,67.8,7.14,75.31,"TSS, Nuts, Alk",2.0,38,1.0985,1.2257,89.61,1137.21,1.4605,1.4571,duplicate TSS bottle labeled site 2,08:50:00
605,606,Fox_Cr,2026-08-06,09:10,11.1,180.1,7.35,196.20,"TSS, Nuts, Alk",17.0,RC8,1.0725,1.1983,88.33,1099.74,1.1994,1.1986,no duplicate TSS,09:10:00
606,607,SFP_Wolf_Cr,2026-08-06,09:20,10.1,80.1,7.04,85.49,"TSS, Nuts, Alk",1.0,32,1.0791,1.2056,88.34,1136.23,1.3860,1.3829,no duplicate TSS,09:20:00
607,608,HP,2026-08-06,09:50,8.2,92.4,7.11,96.88,"TSS, Nuts, Alk",11.0,41,1.0625,1.1886,88.87,1133.05,1.2093,1.2081,no duplicate TSS,09:50:00
608,609,Avalanche_Cr,2026-08-06,10:05,10.2,116.6,6.84,122.90,"TSS, Nuts, Alk",4.0,4,1.0826,1.2096,87.90,1104.40,1.2106,1.2099,no duplicate TSS,10:05:00
609,610,GO_Cr,2026-08-06,10:20,12.2,125.6,6.92,131.40,"TSS, Nuts, Alk",16.0,58,1.0835,1.2090,88.44,1095.88,1.2101,1.2095,no duplicate TSS,10:20:00
610,611,SFP_Chap,2026-08-06,10:40,10.9,79.8,6.84,84.86,"TSS, Nuts, Alk",9.0,43,1.0968,1.2247,88.36,1137.59,1.3837,1.3799,no duplicate TSS,10:40:00
611,612,Warm_Sp,2026-08-06,11:00,12.0,107.3,7.53,114.90,"TSS, Nuts, Alk",3.0,31,1.0947,1.2208,88.21,1139.28,1.2217,1.2216,duplicate TSS bottle labeled site 12,11:00:00
612,613,SFP_BJ,2026-08-06,11:10,11.2,87.3,7.07,93.65,"TSS, Nuts, Alk",19.0,FC16,1.1080,1.2329,87.47,1135.19,1.7347,1.7291,no duplicate TSS,11:10:00
613,614,BJ_Cr,2026-08-06,11:25,8.8,51.4,8.91,56.12,"TSS, Nuts, Alk",8.0,FC9,1.0901,1.2168,88.55,1083.60,1.2182,1.2163,no duplicate TSS,11:25:00
614,615,SFP_DW,2026-08-06,12:05,14.9,91.1,7.15,96.99,"TSS, Nuts, Alk",15.0,FC27,1.1117,1.2377,87.98,1116.23,1.2803,1.2748,no duplicate TSS,12:05:00
615,616,SFP_Alder_Cr,2026-08-06,12:40,12.9,61.7,7.24,66.86,"TSS, Nuts, Alk",20.0,49,1.0883,1.2156,88.28,1136.24,1.2362,1.2341,duplicate TSS bottle labeled site 14,12:40:00

## Group by site

In [20]:
for site, group in df.groupby("site"):
    print(f"--- Data for Site: {site} ---")
    display(group)
    print("\n")

--- Data for Site: Avalanche_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
30,31,Avalanche_Cr,2024-10-19,17:40,9.60,130.5,8.13,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10000,1.23000,101.45,1110.23,1.24000,1.23700,,17:40:00
37,38,Avalanche_Cr,2024-11-03,13:15,4.00,123.2,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,31,1.09400,1.21700,87.64,1123.76,1.26950,1.26391,,13:15:00
57,58,Avalanche_Cr,2024-11-09,11:15,NaN,127.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06200,1.18500,88.77,1125.45,1.18642,1.18574,,11:15:00
74,75,Avalanche_Cr,2024-11-24,11:55,NaN,126.9,8.11,NaN,"TSS, Nuts, DOC, Alk",NaN,16,1.09612,1.21856,88.49,1124.38,1.22548,1.22249,,11:55:00
89,90,Avalanche_Cr,2025-01-17,11:45,1.70,116.8,7.38,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06185,1.19312,88.34,1063.49,1.19561,1.19490,Lab(omega) EC = 145.3 @7.2C,11:45:00
104,105,Avalanche_Cr,2025-01-30,09:08,0.60,124.3,7.75,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11063,1.24091,88.43,644.80,1.24326,1.24241,Lab(metrohm) EC = 127.8 @5.9C,09:08:00
119,120,Avalanche_Cr,NaT,0n:an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Road Closed, could not sample",NaT
135,136,Avalanche_Cr,2025-03-02,11:26,3.20,115.3,7.60,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08899,1.21565,88.71,1142.03,1.27106,1.26811,,11:26:00
182,183,Avalanche_Cr,2025-04-15,13:45,5.80,74.8,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09805,1.22438,88.55,1152.61,1.43208,1.33420,,13:45:00
200,201,Avalanche_Cr,2025-04-28,11:25,5.70,64.2,7.77,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10662,1.23833,88.46,1143.78,1.76401,1.74821,relatively large sandy grains,11:25:00
217,218,Avalanche_Cr,2025-05-10,13:45,7.80,51.6,7.06,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09147,1.22702,89.00,1130.46,1.60014,1.56489,,13:45:00
236,237,Avalanche_Cr,2025-05-27,10:20,6.30,53.1,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10445,1.23638,89.01,1075.05,1.26565,1.26253,,10:20:00
255,256,Avalanche_Cr,2025-06-08,11:40,10.40,47.8,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10694,1.23303,88.50,1164.14,1.23886,1.23728,,11:40:00
274,275,Avalanche_Cr,2025-06-22,11:45,7.20,92.0,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07570,1.20167,89.01,1147.82,1.20332,1.20274,Rained/snowed late 6/21 through 13:30 on 6/22,11:45:00
294,295,Avalanche_Cr,2025-07-07,09:55,10.30,183.6,7.85,84.20,"TSS, Nuts, DOC, Alk",NaN,51,1.06259,1.19076,87.84,1101.70,1.22199,1.21754,Large rainstorm 7/4,09:55:00
313,314,Avalanche_Cr,2025-07-21,12:20,12.25,112.0,7.81,NaN,"TSS, Nuts, DOC, Alk",6.0,19,1.07586,1.20409,87.47,1117.18,1.21155,1.20988,used old YSI probe for temp and us,12:20:00
332,333,Avalanche_Cr,2025-08-01,12:05,12.31,115.0,7.96,117.50,"TSS, Nuts, DOC, Alk",7.0,1,1.08500,1.21600,88.99,1131.08,1.23400,1.22400,rainstorm night of 7/31 before sampling,12:05:00
351,352,Avalanche_Cr,2025-08-14,11:45,11.98,88.0,7.12,128.00,"TSS, Nuts, DOC, Alk",11.0,27,1.10100,1.23400,88.21,1111.92,1.23500,1.23700,,11:45:00
384,385,Avalanche_Cr,2025-08-29,16:26,14.50,119.0,6.62,119.30,"TSS, Nuts, DOC, Alk",10.0,12,1.06630,1.19940,88.57,1137.31,1.41410,1.27230,,16:26:00
402,403,Avalanche_Cr,2025-09-12,14:00,12.62,129.0,6.58,131.90,"TSS, Nuts, DOC, Alk",5.0,57,1.07850,1.21170,88.38,NaN,1.26120,1.25870,forgot to weigh full bottle.,14:00:00
425,426,Avalanche_Cr,2025-09-26,14:05,11.88,129.0,6.55,125.90,"TSS, Nuts, DOC, Alk",15.0,29,1.11630,1.24920,88.50,1136.80,1.25610,1.25460,,14:05:00
468,469,Avalanche_Cr,2025-10-10,15:35,11.36,121.0,7.43,131.80,"TSS, Nuts, DOC, Alk",10.0,28,1.10780,1.24140,87.57,1119.22,1.31370,1.31250,,15:35:00
514,515,Avalanche_Cr,2026-04-11,13:03,5.70,81.5,6.97,84.60,"TSS, Nuts, DOC, Alk",10.0,FC14,1.08140,1.21430,87.56,1100.03,1.78470,1.75270,,13:03:00
532,533,Avalanche_Cr,2026-05-11,12:50,9.70,64.7,7.12,67.96,"TSS, Nuts, DOC, Alk",2.0,68,1.09410,1.22860,89.61,1096.01,1.50870,1.49740,,12:50:00
557,558,Avalanche_Cr,2026-06-13,09:25,6.90,93.3,7.00,97.93,"TSS, Nuts, DOC, Alk",17.0,25,1.09840,1.23170,88.72,1136.42,1.23310,1.23230,,09:25:00
574,575,Avalanche_Cr,2026-07-10,10:35,10.40,105.8,7.43,115.50,"TSS, Nuts, DOC, Alk",4.0,4,1.08200,1.21420,87.91,1117.66,1.21580,1.21510,,10:35:00
591,592,Avalanche_Cr,2026-07-31,11:30,12.60,114.7,6.83,120.00,"TSS, Nuts, Alk",20.0,16,1.09680,1.21360,88.27,1140.21,1.21390,1.21370,Whatman GF/F 934-AH used for TSS,11:30:00
608,609,Avalanche_Cr,2026-08-06,10:05,10.20,116.6,6.84,122.90,"TSS, Nuts, Alk",4.0,4,1.08260,1.20960,87.90,1104.40,1.21060,1.20990,no duplicate TSS,10:05:00

--- Data for Site: BJ_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
3,4,BJ_Cr,2024-10-11,15:27,NaN,NaN,7.79,NaN,"TSS, Nuts",NaN,21,1.08000,1.213000,87.430,1080.30,1.23800,NaN,,15:27:00
7,8,BJ_Cr,2024-10-12,12:30,8.00,54.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,12:30:00
20,21,BJ_Cr,2024-10-19,11:00,4.20,54.1,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.09000,1.230000,101.060,1082.96,1.24600,1.23700,"Glass vial broke, sample gone",11:00:00
48,49,BJ_Cr,2024-11-04,14:20,4.30,52.3,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,41,1.06200,1.186000,88.580,1075.83,1.19220,1.18744,,14:20:00
52,53,BJ_Cr,2024-11-09,10:15,NaN,61.6,8.12,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.20100,1.223000,88.560,1119.97,1.22534,1.22395,,10:15:00
69,70,BJ_Cr,2024-11-24,10:53,NaN,70.3,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08887,1.211970,88.250,1130.70,1.21413,1.21233,,10:53:00
84,85,BJ_Cr,2025-01-17,09:13,1.10,52.2,7.21,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06293,1.189689,87.460,1034.02,1.18888,1.18744,Lab(omega) EC = 64.67 @7.8C,09:13:00
99,100,BJ_Cr,2025-01-30,15:00,0.80,49.7,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06124,1.192530,88.370,511.10,1.19471,1.19341,"Had to break through ice for sample,Lab(metroh...",15:00:00
114,115,BJ_Cr,2025-02-15,14:00,2.20,64.2,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06219,1.193690,88.420,1092.78,1.19824,1.19601,Had to break through ice,14:00:00
130,131,BJ_Cr,2025-03-02,10:15,1.80,55.1,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09785,1.223710,88.380,1107.88,1.22524,1.22442,,10:15:00
145,146,BJ_Cr,2025-03-19,09:35,0.60,55.6,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07624,1.203910,89.200,1065.29,1.20717,1.20549,,09:35:00
157,158,BJ_Cr,2025-03-30,10:05,3.10,53.8,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09409,1.220860,88.700,1046.68,1.22345,1.22242,,10:05:00
170,171,BJ_Cr,2025-04-15,14:55,7.60,48.3,7.41,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.203690,87.440,1016.08,1.20812,1.20594,,14:55:00
188,189,BJ_Cr,2025-04-28,10:05,5.50,44.7,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09423,1.227110,88.340,1112.23,1.23377,1.23103,,10:05:00
206,207,BJ_Cr,2025-05-10,14:40,10.90,42.8,7.04,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09419,1.225540,88.380,1141.69,1.24912,1.24645,,14:40:00
225,226,BJ_Cr,2025-05-27,15:45,10.70,33.3,7.28,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09184,1.224450,88.240,1125.74,1.22968,1.22819,,15:45:00
244,245,BJ_Cr,2025-06-08,12:45,10.40,26.8,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11138,1.239550,88.540,1122.57,1.24461,1.24183,,12:45:00
263,264,BJ_Cr,2025-06-22,13:10,8.10,47.5,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10433,1.230680,88.200,1116.12,1.23323,1.23172,Rained/snowed late 6/21 through 13:30 on 6/22,13:10:00
282,283,BJ_Cr,2025-07-07,14:50,11.40,78.9,6.94,35.38,"TSS, Nuts, DOC, Alk",NaN,7,1.08282,1.209640,88.570,1152.00,1.21334,1.21156,Large rainstorm 7/4,14:50:00
301,302,BJ_Cr,2025-07-21,13:50,9.70,46.0,7.95,NaN,"TSS, Nuts, DOC, Alk",8.0,33,1.10739,1.235810,88.790,1106.94,1.23861,1.23698,used old YSI probe for temp and us,13:50:00
320,321,BJ_Cr,2025-08-01,13:20,9.66,47.0,8.01,50.89,"TSS, Nuts, DOC, Alk",5.0,12,1.06600,1.193000,88.380,1090.53,1.20200,1.19300,rainstorm night of 7/31 before sampling,13:20:00
339,340,BJ_Cr,2025-08-14,10:20,8.17,33.0,7.29,55.45,"TSS, Nuts, DOC, Alk",13.0,58,1.08300,1.212000,88.570,1116.33,1.21900,1.21800,,10:20:00
368,369,BJ_Cr,2025-08-27,16:20,12.80,46.0,7.13,58.14,"TSS, Nuts, DOC, Alk",15.0,34,1.06530,1.197600,58.168,591.10,1.19930,1.19680,non-regular sampling after rain. 500ml bottle ...,16:20:00
373,374,BJ_Cr,2025-08-29,10:45,8.13,51.0,7.13,52.19,"TSS, Nuts, DOC, Alk",6.0,FC11,1.07920,1.212800,87.450,1057.64,1.21480,1.21250,,10:45:00
407,408,BJ_Cr,2025-09-12,17:50,9.14,51.0,6.32,53.56,"TSS, Nuts, DOC, Alk",6.0,49,1.08790,1.219400,87.450,NaN,1.22220,1.22050,forgot to weigh full bottle.,17:50:00
430,431,BJ_Cr,2025-09-26,17:50,8.52,52.0,6.38,48.37,"TSS, Nuts, DOC, Alk",18.0,36,1.08040,1.214600,87.840,1103.23,1.21760,1.21600,,17:50:00
440,441,BJ_Cr,2025-10-04,09:40,7.00,53.0,7.98,48.67,TSS,17.0,5,1.08950,1.221900,88.730,1093.84,1.22360,1.22230,non-regular sampling after 10/03 rain.,09:40:00
473,474,BJ_Cr,2025-10-10,16:55,8.36,53.0,7.65,53.90,"TSS, Nuts, DOC, Alk",14.0,14,1.07610,1.208300,88.520,1091.57,1.21130,1.20990,,16:55:00
486,487,BJ_Cr,2025-12-04,14:20,1.37,49.0,7.58,50.71,"TSS, Nuts, DOC, Alk",1.0,53,1.08520,1.217600,88.390,1083.29,1.21930,1.21730,,14:20:00
500,501,BJ_Cr,2026-02-07,16:20,NaN,44.0,6.44,47.08,"TSS, Nuts, DOC, Alk",5.0,FC16,1.07070,1.204200,88.360,1110.25,1.20560,1.20380,Not typical site. Sampled above the highway cu...,16:20:00
510,511,BJ_Cr,2026-03-08,16:40,4.70,51.0,7.37,58.85,"TSS, Nuts, Alk",1.0,2,1.09820,1.230800,88.390,1117.64,1.23210,1.23060,DOC bottle leaked during transport,16:40:00
526,527,BJ_Cr,2026-04-11,16:20,6.70,51.2,6.92,52.94,"TSS, Nuts, DOC, Alk",20.0,34,1.06520,1.197200,88.270,1122.96,1.20010,1.19790,,16:20:00
545,546,BJ_Cr,2026-05-11,16:20,10.60,47.9,7.08,50.28,"TSS, Nuts, DOC, Alk",17.0,12,1.06630,1.200000,88.720,1067.11,1.20270,1.20090,,16:20:00
562,563,BJ_Cr,2026-06-13,11:00,7.00,48.9,7.22,51.67,"TSS, Nuts, DOC, Alk",4.0,8,1.10730,1.239900,87.890,1102.14,1.24200,1.24000,,11:00:00
579,580,BJ_Cr,2026-07-10,12:00,9.00,50.2,7.58,54.50,"TSS, Nuts, DOC, Alk",10.0,7,1.08290,1.200000,87.570,1008.27,1.20140,1.20020,Whatman GF/F 934-AH used for TSS,12:00:00
596,597,BJ_Cr,2026-07-31,13:00,10.80,50.3,7.21,53.60,"TSS, Nuts, DOC, Alk",7.0,1,1.08480,1.200800,88.990,1089.76,1.20330,1.20180,Whatman GF/F 934-AH used for DOC/TSS,13:00:00
613,614,BJ_Cr,2026-08-06,11:25,8.80,51.4,8.91,56.12,"TSS, Nuts, Alk",8.0,FC9,1.09010,1.216800,88.550,1083.60,1.21820,1.21630,no duplicate TSS,11:25:00

--- Data for Site: Bear_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
222,223,Bear_Cr,2025-05-10,12:00,8.80,49.9,7.15,NaN,"TSS, Nuts, DOC, Alk",NaN,"11,51",2.14767,2.41332,88.24,1150.55,3.30473,3.27641,"Very murky dark flows, very likely debris flow...",12:00:00
241,242,Bear_Cr,2025-05-27,13:30,11.40,40.8,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11116,1.24172,88.45,1074.04,1.36588,1.36237,"Lid lost during sampling, lid from bottle 19 u...",13:30:00
260,261,Bear_Cr,2025-06-08,09:40,9.50,8.2,7.31,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.07951,1.20683,87.84,1134.04,1.22348,1.22207,,09:40:00
279,280,Bear_Cr,2025-06-22,09:25,5.90,66.2,7.36,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06623,1.19338,88.46,1128.62,1.19844,1.19726,Rained/snowed late 6/21 through 13:30 on 6/22,09:25:00
298,299,Bear_Cr,2025-07-07,11:45,14.10,129.9,7.72,60.13,"TSS, Nuts, DOC, Alk",NaN,6,1.10428,1.23115,88.52,1058.80,1.24066,1.23929,Large rainstorm 7/4,11:45:00
317,318,Bear_Cr,2025-07-21,09:55,10.40,81.0,7.89,NaN,"TSS, Nuts, DOC, Alk",18.0,58,1.08356,1.21146,87.88,1141.35,1.21582,1.21449,used old YSI probe for temp and us,09:55:00
336,337,Bear_Cr,2025-08-01,10:35,11.78,82.0,8.05,88.08,"TSS, Nuts, DOC, Alk",18.0,9,1.06500,1.19700,87.85,1081.82,1.21100,1.19900,rainstorm night of 7/31 before sampling,10:35:00
355,356,Bear_Cr,2025-08-14,15:00,18.33,76.0,7.20,94.82,"TSS, Nuts, DOC, Alk",6.0,37,1.80100,1.21400,87.93,1126.56,1.21500,1.21460,,15:00:00
388,389,Bear_Cr,2025-08-29,11:25,11.97,90.0,6.65,90.08,"TSS, Nuts, DOC, Alk",19.0,5,1.08940,1.22210,89.61,1145.66,1.22320,1.22230,,11:25:00
394,395,Bear_Cr,2025-09-12,12:10,9.39,91.0,6.85,91.52,"TSS, Nuts, DOC, Alk",8.0,40,1.10560,1.23740,101.89,1152.41,1.23960,1.23800,,12:10:00
417,418,Bear_Cr,2025-09-26,15:10,13.80,92.0,6.48,89.31,"TSS, Nuts, DOC, Alk",6.0,17,1.09120,1.22540,87.46,1133.43,1.22730,1.22620,,15:10:00
450,451,Bear_Cr,2025-10-04,11:20,8.94,94.0,7.79,112.40,TSS,24.0,34,1.06550,1.19820,87.73,1099.97,1.20060,1.19950,non-regular sampling after 10/03 rain.,11:20:00
457,458,Bear_Cr,2025-10-10,12:30,9.96,93.0,7.85,91.83,"TSS, Nuts, DOC, Alk",9.0,FC4,1.05840,1.19150,88.34,1033.75,1.19340,1.19340,,12:30:00
476,477,Bear_Cr,2025-12-04,10:10,-0.34,88.0,7.26,83.34,"TSS, Nuts, DOC, Alk",10.0,46,1.10080,1.23440,87.57,1023.01,1.23670,1.23580,,10:10:00
516,517,Bear_Cr,2026-04-11,13:50,7.00,70.5,7.02,72.15,"TSS, Nuts, DOC, Alk",2.0,16,1.09590,1.22810,89.58,1146.36,1.25860,1.25590,,13:50:00
535,536,Bear_Cr,2026-05-11,13:50,12.10,46.6,6.89,54.13,"TSS, Nuts, DOC, Alk",3.0,18,1.11130,1.24360,88.19,1129.71,1.33470,1.32930,,13:50:00
549,550,Bear_Cr,2026-06-13,06:55,6.60,67.7,7.92,71.39,"TSS, Nuts, DOC, Alk",9.0,HZ,1.06960,1.20270,88.33,1142.73,1.20960,1.20880,,06:55:00
566,567,Bear_Cr,2026-07-10,08:20,9.40,78.6,7.29,84.71,"TSS, Nuts, DOC, Alk",19.0,32,1.07900,1.19590,87.47,1070.79,1.19840,1.19800,Whatman GF/F 934-AH used for TSS,08:20:00
583,584,Bear_Cr,2026-07-31,09:00,10.60,88.6,7.15,92.61,"TSS, Nuts, Alk",12.0,FC20,1.11830,1.23520,87.89,1111.53,1.32530,1.32330,Whatman GF/F 934-AH used for TSS,09:00:00
600,601,Bear_Cr,2026-08-06,08:05,8.70,87.5,7.42,95.30,"TSS, Nuts, Alk",18.0,FC12,1.08860,1.21460,87.84,1130.70,1.23670,1.23550,duplicate TSS bottle labled site 18,08:05:00

--- Data for Site: Camp_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
17,18,Camp_Cr,2024-10-13,16:30,12.40,84.6,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09100,1.22600,88.92,1139.68,1.25000,1.24800,,16:30:00
27,28,Camp_Cr,2024-10-19,13:45,8.10,79.8,7.97,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10700,1.23700,101.39,1113.49,1.24100,1.23900,"Glass vial broke, sample gone",13:45:00
34,35,Camp_Cr,2024-11-03,11:00,2.80,77.0,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,28,1.10800,1.23200,88.33,1129.93,1.23640,1.23461,,11:00:00
63,64,Camp_Cr,2024-11-09,12:20,NaN,79.6,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,56,1.08800,1.21300,88.95,1125.12,1.21643,1.21510,,12:20:00
80,81,Camp_Cr,2024-11-24,15:20,NaN,85.3,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10358,1.22630,87.42,1110.77,1.23685,1.23572,,15:20:00
95,96,Camp_Cr,2025-01-17,13:52,1.40,79.5,7.05,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11069,1.24128,88.54,634.51,1.24499,1.24419,Lab(omega) EC = 98.33 @11.9C,13:52:00
110,111,Camp_Cr,2025-01-30,11:35,1.00,81.9,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06383,1.19489,88.10,1093.60,1.19737,1.19661,Lab(metrohm) EC = 86.73 @5.2C,11:35:00
125,126,Camp_Cr,2025-02-15,14:35,2.70,82.4,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10411,1.23431,88.51,1072.96,1.23677,1.23586,,14:35:00
141,142,Camp_Cr,2025-03-02,15:20,5.40,86.2,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08295,1.21562,87.61,1147.96,1.53894,1.52569,,15:20:00
153,154,Camp_Cr,2025-03-19,13:10,2.80,79.5,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10655,1.23277,88.70,1092.33,1.23857,1.23781,,13:10:00
165,166,Camp_Cr,2025-03-30,14:20,6.10,71.4,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10384,1.23126,88.99,1020.61,1.23609,1.23547,,14:20:00
178,179,Camp_Cr,2025-04-15,10:50,5.40,57.8,7.60,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06160,1.18801,87.80,1051.64,1.24008,1.23792,,10:50:00
196,197,Camp_Cr,2025-04-28,13:00,8.20,51.2,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08759,1.21932,88.53,1121.14,1.23404,1.23288,,13:00:00
214,215,Camp_Cr,2025-05-10,12:20,11.30,52.3,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09147,1.22239,88.35,1136.59,1.31439,1.30763,,12:20:00
233,234,Camp_Cr,2025-05-27,13:50,12.80,46.4,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07629,1.20979,88.55,1101.16,1.21441,1.21391,,13:50:00
252,253,Camp_Cr,2025-06-08,09:55,9.60,22.8,7.53,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08532,1.21226,88.41,1136.40,1.21471,1.21369,,09:55:00
271,272,Camp_Cr,2025-06-22,09:50,6.10,57.8,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09857,1.22493,88.52,1138.34,1.23775,1.23542,Rained/snowed late 6/21 through 13:30 on 6/22,09:50:00
291,292,Camp_Cr,2025-07-07,12:00,13.30,107.6,7.74,46.44,"TSS, Nuts, DOC, Alk",NaN,9,1.06408,1.19144,88.36,1116.80,1.36117,1.35628,Large rainstorm 7/4,12:00:00
310,311,Camp_Cr,2025-07-21,10:20,10.32,65.0,7.93,NaN,"TSS, Nuts, DOC, Alk",14.0,4,1.10493,1.23106,88.52,1130.43,1.23823,1.23706,used old YSI probe for temp and us,10:20:00
329,330,Camp_Cr,2025-08-01,10:48,11.25,67.0,7.99,86.97,"TSS, Nuts, DOC, Alk",12.0,8,1.10700,1.23800,87.89,1128.40,1.24200,1.24100,rainstorm night of 7/31 before sampling,10:48:00
348,349,Camp_Cr,2025-08-14,12:40,13.45,52.0,7.16,75.33,"TSS, Nuts, DOC, Alk",16.0,56,1.08900,1.22200,88.78,1084.10,1.22500,1.22310,,12:40:00
381,382,Camp_Cr,2025-08-29,11:45,11.78,72.0,7.14,73.22,"TSS, Nuts, DOC, Alk",16.0,33,1.10730,1.23970,88.45,1140.78,1.24570,1.24360,,11:45:00
396,397,Camp_Cr,2025-09-12,12:30,9.98,72.0,6.50,72.18,"TSS, Nuts, DOC, Alk",15.0,53,1.08510,1.21820,106.69,1128.06,1.22430,1.22260,,12:30:00
419,420,Camp_Cr,2025-09-26,15:55,12.90,72.0,6.47,68.03,"TSS, Nuts, DOC, Alk",24.0,58,1.08330,1.21640,87.73,1118.11,1.22670,1.22470,,15:55:00
449,450,Camp_Cr,2025-10-04,11:10,8.27,75.0,7.85,83.38,TSS,2.0,68,1.09440,1.22640,88.80,1091.00,1.23080,1.22860,non-regular sampling after 10/03 rain.,11:10:00
459,460,Camp_Cr,2025-10-10,12:50,10.17,75.0,7.49,77.56,"TSS, Nuts, DOC, Alk",2.0,FC14,1.08170,1.21440,88.80,1119.55,1.22410,1.22210,,12:50:00
478,479,Camp_Cr,2025-12-04,10:40,0.35,73.0,7.54,70.37,"TSS, Nuts, DOC, Alk",17.0,FC4,1.05860,1.19080,88.73,1057.00,1.19290,1.19250,,10:40:00
492,493,Camp_Cr,2026-02-07,12:40,NaN,74.0,6.37,72.53,"TSS, Nuts, DOC, Alk",7.0,FC12,1.08790,1.22060,88.99,1108.68,1.22710,1.22610,,12:40:00
502,503,Camp_Cr,2026-03-08,12:05,4.70,76.0,NaN,NaN,"Nuts, DOC, Alk",11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no TSS lost lid,12:05:00
518,519,Camp_Cr,2026-04-11,14:10,6.80,67.5,6.80,67.36,"TSS, Nuts, DOC, Alk",6.0,33,1.10700,1.23880,87.44,1014.60,1.28100,1.27640,,14:10:00
537,538,Camp_Cr,2026-05-11,14:15,13.30,61.9,6.90,65.47,"TSS, Nuts, DOC, Alk",1.0,FC11,1.07880,1.21250,88.39,1133.81,1.22700,1.22460,,14:15:00
551,552,Camp_Cr,2026-06-13,07:20,6.40,60.4,6.77,63.89,"TSS, Nuts, DOC, Alk",7.0,45,1.10110,1.23310,88.99,1084.82,1.24200,1.24080,,07:20:00
568,569,Camp_Cr,2026-07-10,08:45,9.20,64.6,7.48,69.85,"TSS, Nuts, DOC, Alk",11.0,RC8,1.07300,1.20620,88.86,1102.53,1.21200,1.21050,,08:45:00
585,586,Camp_Cr,2026-07-31,09:55,10.60,67.1,6.97,70.39,"TSS, Nuts, DOC, Alk",4.0,27,1.10110,1.21950,87.91,1112.95,1.22230,1.22160,Whatman GF/F 934-AH used for DOC/TSS,09:55:00
602,603,Camp_Cr,2026-08-06,08:30,9.20,67.8,7.31,71.39,"TSS, Nuts, Alk",10.0,FC26,1.07960,1.20720,87.53,1112.36,1.21020,1.20930,no duplicate TSS,08:30:00

--- Data for Site: Canyon_Cr_Banner ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
389,390,Canyon_Cr_Banner,2025-08-29,13:41,11.39,98.0,6.69,98.72,TSS,20.0,16,1.0960,1.2290,87.72,1075.40,1.2376,1.2357,site added 8/29.,13:41:00
410,411,Canyon_Cr_Banner,2025-09-12,16:15,9.18,96.0,6.93,97.46,TSS,20.0,2,1.0974,1.2301,102.85,1090.46,NaN,1.2323,Forgot to weigh sed before ashing. Furthest up...,16:15:00
433,434,Canyon_Cr_Banner,2025-09-26,11:15,5.75,95.0,6.50,94.60,"TSS, Nuts, DOC, Alk",10.0,38,1.0942,1.2267,87.58,1076.76,1.2337,1.2329,,11:15:00
464,465,Canyon_Cr_Banner,2025-10-10,14:25,8.39,90.0,7.47,97.86,TSS,21.0,R21,1.1077,1.2385,88.83,1101.57,1.2424,1.2426,,14:25:00

--- Data for Site: Canyon_Cr_DF2 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
411,412,Canyon_Cr_DF2,2025-09-12,16:25,9.63,103.0,6.82,101.5,TSS,24.0,32,1.0786,1.2118,102.82,1034.33,NaN,1.2427,Forgot to weigh sed before ashing.,16:25:00
434,435,Canyon_Cr_DF2,2025-09-26,11:30,6.58,101.0,6.61,101.2,"TSS, Nuts, DOC, Alk",4.0,HZ,1.0691,1.2011,87.91,1099.57,1.2064,1.2046,,11:30:00

--- Data for Site: Canyon_Cr_DF4 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
414,415,Canyon_Cr_DF4,2025-09-12,15:50,10.78,114.0,6.97,112.2,TSS,23.0,39,1.1011,1.2349,102.79,1146.36,NaN,1.2475,Forgot to weigh sed before ashing. site first ...,15:50:00
437,438,Canyon_Cr_DF4,2025-09-26,11:50,8.58,114.0,6.98,111.0,"TSS, Nuts, DOC, Alk",11.0,33,1.1071,1.2400,88.07,1061.91,1.2444,1.2434,,11:50:00

--- Data for Site: Canyon_Cr_DF5 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
413,414,Canyon_Cr_DF5,2025-09-12,15:35,9.94,105.0,7.00,86.98,TSS,22.0,5,1.0887,1.2218,105.10,1039.92,NaN,1.2378,Forgot to weigh sed before ashing. site first ...,15:35:00
436,437,Canyon_Cr_DF5,2025-09-26,12:20,8.46,107.0,6.54,105.80,"TSS, Nuts, DOC, Alk",23.0,16,1.0965,1.2291,88.81,1084.96,1.2327,1.2320,,12:20:00
465,466,Canyon_Cr_DF5,2025-10-10,14:45,11.01,108.0,7.87,109.00,TSS,22.0,FC19,1.0682,1.2003,89.74,1117.40,1.2128,1.2110,,14:45:00

--- Data for Site: Canyon_Cr_DF8 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
412,413,Canyon_Cr_DF8,2025-09-12,14:55,9.29,107.0,6.89,110.7,TSS,21.0,FC11,1.0786,1.2111,102.41,1091.29,NaN,1.3273,Forgot to weigh sed before ashing. site first ...,14:55:00
435,436,Canyon_Cr_DF8,2025-09-26,13:05,10.77,116.0,6.46,113.9,"TSS, Nuts, DOC, Alk",21.0,43,1.0959,1.2296,88.83,1106.01,1.2375,1.2360,,13:05:00

--- Data for Site: Canyon_Cr_DF_1 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
390,391,Canyon_Cr_DF_1,2025-08-29,14:05,12.04,106.0,6.72,106.7,TSS,21.0,38,1.0982,1.2297,105.86,1109.75,1.282,1.3885,site added 8/29. TSS in brown bottles,14:05:00

--- Data for Site: Canyon_Cr_DF_3 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
391,392,Canyon_Cr_DF_3,2025-08-29,14:45,12.79,119.0,6.77,115.8,TSS,22.0,25,1.0984,1.2311,104.35,1133.14,1.5372,1.4835,site added 8/29. TSS in brown bottles. This mi...,14:45:00

--- Data for Site: Canyon_Cr_SFP ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
2,3,Canyon_Cr_SFP,2024-10-11,14:15,NaN,NaN,7.97,NaN,"TSS, Nuts",NaN,25,1.09800,1.23200,87.50,1117.52,1.24100,1.23600,,14:15:00
13,14,Canyon_Cr_SFP,2024-10-12,15:45,12.10,103.7,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,15:45:00
25,26,Canyon_Cr_SFP,2024-10-19,13:00,6.90,108.9,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08500,1.21500,101.63,1141.61,1.21900,1.21700,Glass bottle cracked but still held some water...,13:00:00
42,43,Canyon_Cr_SFP,2024-11-03,15:00,4.10,103.1,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,36,1.07800,1.20900,87.69,1078.19,1.21550,1.21401,,15:00:00
61,62,Canyon_Cr_SFP,2024-11-09,12:00,NaN,107.8,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09500,1.21800,87.69,1129.60,1.22278,1.22189,,12:00:00
78,79,Canyon_Cr_SFP,2024-11-24,14:05,NaN,108.1,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09381,1.21783,88.40,1137.76,1.22348,1.22174,,14:05:00
93,94,Canyon_Cr_SFP,2025-01-17,14:32,1.70,100.5,7.34,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08727,1.21728,87.82,1121.66,1.22062,1.21937,Lab(omega) EC = 124.5 @9.2C,14:32:00
108,109,Canyon_Cr_SFP,2025-01-30,10:27,0.30,68.3,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09359,1.22525,88.48,1108.00,1.22912,1.22815,Lab(metrohm) EC = 113.6 @5.2C,10:27:00
123,124,Canyon_Cr_SFP,2025-02-15,15:25,3.00,103.4,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09383,1.22452,88.36,1135.65,1.23561,1.23328,,15:25:00
139,140,Canyon_Cr_SFP,2025-03-02,16:00,4.60,106.9,7.39,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06321,1.18977,88.49,1146.88,1.19927,1.19713,,16:00:00
151,152,Canyon_Cr_SFP,2025-03-19,13:45,2.40,110.5,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10429,1.23124,88.36,1140.98,1.24274,1.23768,,13:45:00
163,164,Canyon_Cr_SFP,2025-03-30,14:50,5.90,110.2,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08321,1.20998,88.23,1135.60,1.23161,1.22774,,14:50:00
176,177,Canyon_Cr_SFP,2025-04-15,12:25,5.60,92.6,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06215,1.18917,89.20,1159.66,1.21881,1.21461,,12:25:00
194,195,Canyon_Cr_SFP,2025-04-28,13:20,7.70,70.9,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06605,1.19278,88.36,1114.68,1.23775,1.23330,,13:20:00
212,213,Canyon_Cr_SFP,2025-05-10,12:30,7.80,59.4,6.92,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.08322,1.21485,87.88,1139.71,1.34684,1.32987,,12:30:00
231,232,Canyon_Cr_SFP,2025-05-27,14:10,10.10,48.9,7.04,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.07899,1.21092,87.47,1118.96,1.31931,1.31456,,14:10:00
250,251,Canyon_Cr_SFP,2025-06-08,10:40,9.00,31.8,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10423,1.23137,88.72,1148.24,1.23923,1.23747,,10:40:00
269,270,Canyon_Cr_SFP,2025-06-22,10:05,6.20,77.6,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11164,1.23889,88.37,1148.08,1.24415,1.24346,Rained/snowed late 6/21 through 13:30 on 6/22,10:05:00
289,290,Canyon_Cr_SFP,2025-07-07,12:15,12.00,149.3,7.42,66.99,"TSS, Nuts, DOC, Alk",NaN,35,1.10221,1.22772,89.01,1109.70,1.25826,1.25398,Large rainstorm 7/4,12:15:00
308,309,Canyon_Cr_SFP,2025-07-21,10:45,9.53,92.0,7.73,NaN,"TSS, Nuts, DOC, Alk",3.0,20,1.06182,1.18911,89.00,1134.53,1.19946,1.19775,used old YSI probe for temp and us,10:45:00
327,328,Canyon_Cr_SFP,2025-08-01,11:00,9.98,94.0,7.89,96.52,"TSS, Nuts, DOC, Alk",17.0,17,1.09200,1.22300,88.73,1143.55,1.24100,1.23100,rainstorm night of 7/31 before sampling,11:00:00
346,347,Canyon_Cr_SFP,2025-08-14,16:15,14.75,78.0,6.27,106.70,"TSS, Nuts, DOC, Alk",19.0,53,1.08600,1.21700,89.83,1149.43,1.22100,1.22070,,16:15:00
361,362,Canyon_Cr_SFP,2025-08-27,15:00,12.60,90.0,6.98,102.40,"TSS, Nuts, DOC, Alk",20.0,"4,40,39",3.31430,3.71590,57.98,607.70,3.87320,3.84840,non-regular sampling after rain. 500ml bottle ...,15:00:00
379,380,Canyon_Cr_SFP,2025-08-29,12:15,10.29,99.0,6.92,100.40,"TSS, Nuts, DOC, Alk",15.0,4,1.10510,1.23770,88.24,1149.05,1.39290,1.36960,,12:15:00
397,398,Canyon_Cr_SFP,2025-09-12,12:45,8.70,102.0,6.63,103.00,"TSS, Nuts, DOC, Alk",2.0,1,1.07580,1.20720,106.05,1119.50,1.22590,1.22330,,12:45:00
420,421,Canyon_Cr_SFP,2025-09-26,16:10,10.98,104.0,6.50,102.10,"TSS, Nuts, DOC, Alk",2.0,45,1.10120,1.23460,88.81,1101.35,1.24220,1.24030,,16:10:00
446,447,Canyon_Cr_SFP,2025-10-04,10:50,7.36,106.0,7.73,112.30,TSS,5.0,11,1.08570,1.21950,88.39,1107.52,1.40800,1.38860,non-regular sampling after 10/03 rain.,10:50:00
460,461,Canyon_Cr_SFP,2025-10-10,13:05,8.64,105.0,7.62,106.30,"TSS, Nuts, DOC, Alk",12.0,FC16,1.07040,1.20200,87.88,1113.98,1.25800,1.25290,,13:05:00
479,480,Canyon_Cr_SFP,2025-12-04,11:10,-0.29,104.0,7.31,7.16,"TSS, Nuts, DOC, Alk",11.0,FC19,1.06830,1.20040,88.09,1060.58,1.30880,1.30250,lots of coarse organic matter suspended in water.,11:10:00
493,494,Canyon_Cr_SFP,2026-02-07,13:35,NaN,101.0,6.39,93.85,"TSS, Nuts, DOC, Alk",10.0,1,1.07610,1.20860,87.56,1139.92,1.30020,1.29900,,13:35:00
503,504,Canyon_Cr_SFP,2026-03-08,12:50,4.00,106.0,6.66,117.10,"TSS, Nuts, DOC, Alk",17.0,47,1.09680,1.22840,88.73,1085.64,1.24320,1.24200,,12:50:00
519,520,Canyon_Cr_SFP,2026-04-11,14:30,6.10,84.5,7.72,92.65,"TSS, Nuts, DOC, Alk",11.0,55,1.09440,1.22520,88.87,1077.76,1.50360,1.47960,,14:30:00
538,539,Canyon_Cr_SFP,2026-05-11,14:30,10.70,65.8,6.86,68.93,"TSS, Nuts, DOC, Alk",10.0,9,1.06370,1.19600,87.56,1084.02,1.50020,1.48600,,14:30:00
552,553,Canyon_Cr_SFP,2026-06-13,07:50,6.40,81.4,6.82,85.43,"TSS, Nuts, DOC, Alk",11.0,FC16,1.07110,1.20400,88.85,1122.14,1.22160,1.21980,,07:50:00
569,570,Canyon_Cr_SFP,2026-07-10,09:00,8.50,84.5,7.08,97.83,"TSS, Nuts, DOC, Alk",16.0,FC9,1.08990,1.22310,88.47,1131.77,1.23340,1.23150,,09:00:00
586,587,Canyon_Cr_SFP,2026-07-31,10:10,9.60,98.1,5.90,102.90,"TSS, Nuts, DOC, Alk",1.0,47,1.09710,1.21470,88.38,1128.62,1.33560,1.32930,Whatman GF/F 934-AH used for DOC/TSS,10:10:00
603,604,Canyon_Cr_SFP,2026-08-06,08:45,8.20,93.0,7.33,106.90,"TSS, Nuts, Alk",6.0,2,1.09790,1.22430,87.45,1060.33,1.29410,1.29070,duplicate TSS bottle labeled site 6,08:45:00

--- Data for Site: Canyon_Cr_slump1 ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
415,416,Canyon_Cr_slump1,2025-09-12,14:45,9.78,115.0,6.94,113.4,TSS,25.0,31,1.0939,1.2258,102.87,1142.19,NaN,1.2773,Forgot to weigh sed before ashing. site first ...,14:45:00
438,439,Canyon_Cr_slump1,2025-09-26,13:30,10.98,116.0,6.55,114.5,"TSS, Nuts, DOC, Alk",22.0,8,1.1067,1.2392,89.61,1105.27,1.2467,1.2458,,13:30:00
466,467,Canyon_Cr_slump1,2025-10-10,15:05,11.03,122.0,7.75,120.6,"TSS,DOC",15.0,2,1.0976,1.2298,88.49,1113.33,1.3056,1.2974,,15:05:00

--- Data for Site: Canyon_cr_avalanche (HP_old) ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
31,32,Canyon_cr_avalanche (HP_old),2024-10-19,18:00,7.9,101.6,8.06,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.080,1.210,101.21,1153.17,1.2230,1.22,"Glass vial broke, sample gone",18:00:00
38,39,Canyon_cr_avalanche (HP_old),2024-11-03,13:20,4.0,95.6,7.84,NaN,"TSS, Nuts, DOC, Alk",NaN,32,1.098,1.211,88.13,1139.86,1.2202,NaN,,13:20:00

--- Data for Site: Chapman_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
10,11,Chapman_Cr,2024-10-12,13:30,8.70,110.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,13:30:00
45,46,Chapman_Cr,2024-11-04,13:20,5.10,105.9,8.03,NaN,"TSS, Nuts, DOC, Alk",NaN,38,1.09500,1.22700,88.42,1091.96,1.23600,1.22905,,13:20:00
286,287,Chapman_Cr,2025-07-07,13:30,14.80,156.2,6.86,64.74,"TSS, Nuts, DOC, Alk",NaN,"18,22,3,14,12",5.47251,6.10803,88.21,1063.10,9.13658,8.99315,"Large rainstorm 7/4, Debris flow occurred and ...",13:30:00
305,306,Chapman_Cr,2025-07-21,13:00,13.75,97.0,7.47,NaN,"TSS, Nuts, DOC, Alk",11.0,51,1.06251,1.18985,88.47,1026.57,1.21803,1.21578,used old YSI probe for temp and us,13:00:00
324,325,Chapman_Cr,2025-08-01,12:40,13.04,77.0,8.02,102.80,"TSS, Nuts, DOC, Alk",6.0,14,1.07600,1.20800,87.45,1081.21,1.23100,1.23500,rainstorm night of 7/31 before sampling,12:40:00
343,344,Chapman_Cr,2025-08-14,16:25,13.07,79.0,6.93,112.50,"TSS, Nuts, DOC, Alk",3.0,34,1.06700,1.19800,88.75,1128.46,1.21100,1.20990,,16:25:00
454,455,Chapman_Cr,2025-10-05,12:40,6.49,106.0,7.67,89.74,TSS,20.0,53,1.08570,1.21950,88.28,1038.67,1.27250,1.26650,non-regular sampling after 10/03 rain.,12:40:00

--- Data for Site: Flat_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
221,222,Flat_Cr,2025-05-10,11:30,7.9,36.8,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.20734,87.83,1145.42,1.462480,1.39162,"New Site, evidence of disturbance near creek a...",11:30:00
240,241,Flat_Cr,2025-05-27,11:55,10.8,37.6,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08773,1.21961,88.40,1079.38,1.274460,1.26386,,11:55:00
259,260,Flat_Cr,2025-06-08,09:00,9.8,82.7,7.54,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09477,1.22109,88.44,1155.38,1.224350,1.22288,,09:00:00
278,279,Flat_Cr,2025-06-22,08:35,5.6,53.2,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11141,1.23853,89.61,1126.14,1.233997,1.23914,Rained/snowed late 6/21 through 13:30 on 6/22,08:35:00

--- Data for Site: Fox_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
12,13,Fox_Cr,2024-10-12,15:00,11.50,185.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,15:00:00
23,24,Fox_Cr,2024-10-19,12:20,6.50,187.4,7.64,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06200,1.19300,101.270,1153.79,1.19400,1.19200,"Glass vial broke, sample gone",12:20:00
40,41,Fox_Cr,2024-11-03,14:00,4.50,173.6,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,34,1.06500,1.19700,88.550,1148.14,1.20190,1.19760,,14:00:00
59,60,Fox_Cr,2024-11-09,11:40,NaN,175.2,8.51,NaN,"Nuts, DOC, Alk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TSS bottle leaked in cooler,11:40:00
76,77,Fox_Cr,2024-11-24,13:30,NaN,188.9,8.03,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08234,1.20739,87.460,1127.14,1.20993,1.20851,,13:30:00
91,92,Fox_Cr,2025-01-17,15:21,1.20,160.4,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08876,1.21864,88.460,1034.95,1.23582,1.22010,Lab EC(omega) = 199.8 @8.9C,15:21:00
106,107,Fox_Cr,2025-01-30,12:50,0.90,88.0,7.73,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08727,1.21984,88.320,1138.20,1.22171,1.22084,"Had to break through ice for sample,Lab(metroh...",12:50:00
121,122,Fox_Cr,2025-02-15,16:35,1.90,170.5,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11074,1.24235,88.200,1121.89,1.24343,1.24254,,16:35:00
137,138,Fox_Cr,2025-03-02,17:20,4.20,135.0,7.49,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10362,1.22975,88.440,1128.95,1.24023,1.23667,,17:20:00
149,150,Fox_Cr,2025-03-19,14:30,3.00,134.9,7.59,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08901,1.21797,88.500,1105.05,1.21977,1.21875,,14:30:00
161,162,Fox_Cr,2025-03-30,15:45,5.30,103.2,7.49,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10101,1.22627,87.440,1112.12,1.23878,1.23499,,15:45:00
174,175,Fox_Cr,2025-04-15,12:50,6.50,86.3,7.23,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06582,1.19321,88.330,1161.69,1.21205,1.20693,,12:50:00
192,193,Fox_Cr,2025-04-28,13:40,8.40,74.2,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06186,1.19313,88.560,1142.09,1.20863,1.20434,,13:40:00
210,211,Fox_Cr,2025-05-10,12:50,11.20,85.3,7.11,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08761,1.21878,88.570,1150.82,1.23162,1.22601,,12:50:00
229,230,Fox_Cr,2025-05-27,14:40,13.30,109.8,7.24,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10658,1.23748,88.740,1116.93,1.24144,1.24035,,14:40:00
248,249,Fox_Cr,2025-06-08,10:55,11.20,81.9,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10467,1.23251,88.500,1156.60,1.23621,1.23426,,10:55:00
267,268,Fox_Cr,2025-06-22,10:25,8.70,152.0,7.23,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10667,1.23361,88.450,1131.32,1.23537,1.23426,Rained/snowed late 6/21 through 13:30 on 6/22,10:25:00
287,288,Fox_Cr,2025-07-07,12:35,15.30,199.0,7.46,152.6,"TSS, Nuts, DOC, Alk",NaN,4,1.10483,1.23205,88.440,1128.80,1.27762,1.26813,Large rainstorm 7/4,12:35:00
306,307,Fox_Cr,2025-07-21,11:25,12.58,191.0,7.79,NaN,"TSS, Nuts, DOC, Alk",1.0,1,1.08526,1.21293,88.400,1131.35,1.21856,1.21693,used old YSI probe for temp and us,11:25:00
325,326,Fox_Cr,2025-08-01,11:17,13.11,189.0,7.87,193.8,"TSS, Nuts, DOC, Alk",15.0,25,1.09800,1.23000,88.230,1119.00,1.24400,1.23200,rainstorm night of 7/31 before sampling,11:17:00
344,345,Fox_Cr,2025-08-14,16:30,16.99,162.0,7.20,207.5,"TSS, Nuts, DOC, Alk",14.0,51,1.06300,1.19600,88.910,1120.25,1.19900,1.19830,,16:30:00
363,364,Fox_Cr,2025-08-27,15:20,15.10,177.0,6.81,195.6,"TSS, Nuts, DOC, Alk",7.0,46,1.10080,1.23360,58.498,566.91,1.24960,1.24500,non-regular sampling after rain. 500ml bottle ...,15:20:00
377,378,Fox_Cr,2025-08-29,12:35,13.54,190.0,6.85,192.5,"TSS, Nuts, DOC, Alk",13.0,58,1.08310,1.21570,88.360,1030.99,1.22160,1.21910,,12:35:00
399,400,Fox_Cr,2025-09-12,13:05,11.29,184.0,6.60,186.8,"TSS, Nuts, DOC, Alk",11.0,47,1.09670,1.22890,102.550,1136.36,1.23520,1.23290,,13:05:00
422,423,Fox_Cr,2025-09-26,16:35,12.25,188.0,6.98,184.6,"TSS, Nuts, DOC, Alk",1.0,44,1.09140,1.22470,88.400,1080.69,1.23350,1.23040,,16:35:00
444,445,Fox_Cr,2025-10-04,10:30,8.99,186.0,7.93,187.4,TSS,10.0,25,1.09830,1.23130,87.580,1090.86,1.24200,1.23910,non-regular sampling after 10/03 rain.,10:30:00
462,463,Fox_Cr,2025-10-10,13:30,10.31,180.0,7.79,183.6,"TSS, Nuts, DOC, Alk",1.0,1,1.07600,1.20940,88.390,1112.15,1.21500,1.21350,,13:30:00
481,482,Fox_Cr,2025-12-04,12:00,-0.33,178.0,7.18,150.3,"TSS, Nuts, DOC, Alk",7.0,18,1.11100,1.24380,89.070,1103.77,1.25520,1.25250,,12:00:00
496,497,Fox_Cr,2026-02-07,14:45,NaN,134.0,6.32,129.1,"TSS, Nuts, DOC, Alk",4.0,4,1.10450,1.23550,87.890,1086.22,1.24500,1.24230,omega read out as ms,14:45:00
506,507,Fox_Cr,2026-03-08,13:55,6.10,124.0,7.14,144.6,"TSS, Nuts, DOC, Alk",13.0,49,1.08850,1.22150,88.330,1085.09,1.22730,1.22670,,13:55:00
521,522,Fox_Cr,2026-04-11,14:55,7.70,119.8,6.92,126.5,"TSS, Nuts, DOC, Alk",9.0,51,1.06240,1.19530,88.340,1124.04,1.22490,1.21890,,14:55:00
540,541,Fox_Cr,2026-05-11,14:55,15.00,126.2,6.73,129.9,"TSS, Nuts, DOC, Alk",4.0,13,1.06460,1.19830,87.890,1120.47,1.21190,1.20940,,14:55:00
554,555,Fox_Cr,2026-06-13,08:25,8.00,161.9,7.11,172.7,"TSS, Nuts, DOC, Alk",1.0,14,1.07690,1.21000,88.390,1073.72,1.21470,1.21310,,08:25:00
571,572,Fox_Cr,2026-07-10,09:25,11.30,178.3,7.24,192.1,"TSS, Nuts, DOC, Alk",2.0,FC29,0.95070,1.08470,89.620,1097.08,1.08850,1.08730,,09:25:00
588,589,Fox_Cr,2026-07-31,10:30,13.20,186.2,6.40,194.8,"TSS, Nuts, Alk",9.0,37,1.08130,1.19820,88.350,1092.37,1.19960,1.19900,Whatman GF/F 934-AH used for TSS,10:30:00
605,606,Fox_Cr,2026-08-06,09:10,11.10,180.1,7.35,196.2,"TSS, Nuts, Alk",17.0,RC8,1.07250,1.19830,88.330,1099.74,1.19940,1.19860,no duplicate TSS,09:10:00

--- Data for Site: GO_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
39,40,GO_Cr,2024-11-03,13:30,3.70,132.8,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,33,1.10600,1.23700,88.55,1055.63,1.24360,1.23988,,13:30:00
58,59,GO_Cr,2024-11-09,11:30,NaN,136.5,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,52,1.05500,1.17900,88.75,939.39,1.18053,1.17979,,11:30:00
75,76,GO_Cr,2024-11-24,12:11,NaN,135.9,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09748,1.22225,88.49,837.95,1.22509,1.22367,TSS bottle not completely filled,12:11:00
90,91,GO_Cr,2025-01-17,11:57,1.50,121.0,7.06,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10344,1.23579,87.63,824.64,1.24951,1.24705,Lab(omega) EC = 130.9 @9.2C,11:57:00
105,106,GO_Cr,NaT,0n:an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Creek frozen over, couldn't get sample",NaT
120,121,GO_Cr,NaT,0n:an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Road Closed, could not sample",NaT
136,137,GO_Cr,2025-03-02,12:00,3.70,119.4,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10647,1.23326,87.82,1137.83,1.24189,1.23959,,12:00:00
183,184,GO_Cr,2025-04-15,14:00,5.40,81.0,7.45,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06438,1.19094,88.35,1134.45,1.22039,1.21249,,14:00:00
201,202,GO_Cr,2025-04-28,11:35,5.90,68.3,7.78,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08501,1.21681,88.48,1084.39,1.25479,1.24834,,11:35:00
218,219,GO_Cr,2025-05-10,13:55,8.80,45.6,7.17,NaN,"TSS, Nuts, DOC, Alk",NaN,"19,46",2.17692,2.44051,88.39,1140.98,2.77911,2.70147,Two filters used due to high volume of sedimen...,13:55:00
237,238,GO_Cr,2025-05-27,10:40,9.00,47.6,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09838,1.23027,87.65,1114.95,1.24574,1.24239,,10:40:00
256,257,GO_Cr,2025-06-08,11:55,12.40,48.2,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09193,1.21785,87.59,1145.26,1.22247,1.22084,,11:55:00
275,276,GO_Cr,2025-06-22,11:15,7.70,99.1,7.31,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08511,1.21104,87.51,1104.42,1.21275,1.21167,Rained/snowed late 6/21 through 13:30 on 6/22,11:15:00
295,296,GO_Cr,2025-07-07,10:05,10.30,116.0,7.64,93.21,"TSS, Nuts, DOC, Alk",NaN,8,1.10708,1.23389,88.74,1107.50,1.32969,1.31897,Large rainstorm 7/4,10:05:00
314,315,GO_Cr,2025-07-21,12:30,15.01,127.0,7.56,NaN,"TSS, Nuts, DOC, Alk",10.0,60,1.09433,1.22138,88.57,1135.37,1.22659,1.22472,used old YSI probe for temp and us,12:30:00
333,334,GO_Cr,2025-08-01,12:15,1562.00,109.0,8.02,134.10,"TSS, Nuts, DOC, Alk",8.0,6,1.10500,1.23700,88.49,1099.43,1.36600,1.35700,rainstorm night of 7/31 before sampling,12:15:00
352,353,GO_Cr,2025-08-14,12:05,15.78,110.0,6.97,150.40,"TSS, Nuts, DOC, Alk",2.0,39,1.09900,1.23300,88.75,1082.22,1.24700,1.24380,,12:05:00
385,386,GO_Cr,2025-08-29,16:45,10.56,133.0,6.85,134.30,"TSS, Nuts, DOC, Alk",8.0,31,1.09420,1.22780,88.50,1078.62,1.24820,1.24560,,16:45:00
401,402,GO_Cr,2025-09-12,13:40,13.14,132.0,6.80,132.80,"TSS, Nuts, DOC, Alk",16.0,37,1.08090,1.21350,102.63,1111.06,1.22350,1.22080,,13:40:00
424,425,GO_Cr,2025-09-26,14:20,11.06,131.0,6.88,128.60,"TSS, Nuts, DOC, Alk",17.0,51,1.06200,1.19540,88.74,1069.60,1.20430,1.20170,,14:20:00
469,470,GO_Cr,2025-10-10,15:50,10.32,115.0,7.74,133.00,"TSS, Nuts, DOC, Alk",8.0,37,1.08080,1.21360,88.50,1081.19,1.24240,1.24040,,15:50:00
533,534,GO_Cr,2026-05-11,13:05,11.10,58.1,6.87,61.93,"TSS, Nuts, DOC, Alk",11.0,20,1.06170,1.19550,88.85,1089.65,1.45230,1.43070,,13:05:00
558,559,GO_Cr,2026-06-13,09:45,9.20,104.7,7.19,110.10,"TSS, Nuts, DOC, Alk",3.0,4,1.10500,1.23880,88.19,989.96,1.24060,1.23960,,09:45:00
575,576,GO_Cr,2026-07-10,10:55,13.70,117.9,6.91,127.90,"TSS, Nuts, DOC, Alk",1.0,FC27,1.11180,1.24410,88.40,1074.02,1.24640,1.24520,,10:55:00
592,593,GO_Cr,2026-07-31,11:45,15.40,124.0,7.02,130.40,"TSS, Nuts, Alk",13.0,17,1.09200,1.20840,88.71,1069.70,1.21040,1.20980,Whatman GF/F 934-AH used for TSS,11:45:00
609,610,GO_Cr,2026-08-06,10:20,12.20,125.6,6.92,131.40,"TSS, Nuts, Alk",16.0,58,1.08350,1.20900,88.44,1095.88,1.21010,1.20950,no duplicate TSS,10:20:00

--- Data for Site: HP ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
36,37,HP,2024-11-03,12:30,3.00,96.6,7.74,NaN,"TSS, Nuts, DOC, Alk",NaN,30,1.09600,1.22000,88.64,1136.18,1.22400,1.22213,,12:30:00
56,57,HP,2024-11-09,11:00,NaN,100.3,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08800,1.21000,88.73,1133.81,1.21524,1.21425,,11:00:00
73,74,HP,2024-11-24,11:42,NaN,109.9,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10604,1.23191,87.83,1128.19,1.23412,1.23288,,11:42:00
88,89,HP,2025-01-17,11:25,1.30,92.4,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09364,1.22496,88.71,1121.81,1.22545,1.22479,Lab(omega) EC = 114.3 @8.5C,11:25:00
103,104,HP,2025-01-30,08:51,3.70,98.6,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08219,1.21282,88.71,1103.50,1.21434,1.21434,Lab(metrohm) EC = 101.0 @7.5C,08:51:00
118,119,HP,NaT,0n:an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Road Closed, could not sample",NaT
134,135,HP,2025-03-02,11:00,2.70,96.0,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08246,1.20842,88.52,1082.60,1.30633,1.30441,,11:00:00
181,182,HP,2025-04-15,13:30,5.10,90.8,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11092,1.23741,87.86,1122.84,1.26152,1.25643,,13:30:00
199,200,HP,2025-04-28,11:00,4.70,73.7,7.80,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06437,1.19664,88.51,1147.04,1.22149,1.21752,,11:00:00
216,217,HP,2025-05-10,13:30,7.20,55.4,7.03,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09812,1.22966,87.49,1147.26,1.29725,1.28673,,13:30:00
235,236,HP,2025-05-27,10:00,5.70,47.2,7.33,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10127,1.23357,87.49,1092.76,1.24801,1.24594,,10:00:00
254,255,HP,2025-06-08,11:30,9.60,36.8,7.64,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07668,1.20401,87.45,1058.47,1.20674,1.20547,,11:30:00
273,274,HP,2025-06-22,11:30,6.10,70.6,7.26,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06451,1.19078,88.51,1152.22,1.19254,1.19183,Rained/snowed late 6/21 through 13:30 on 6/22,11:30:00
293,294,HP,2025-07-07,09:45,9.40,130.7,7.80,60.29,"TSS, Nuts, DOC, Alk",NaN,25,1.09861,1.22470,89.61,1111.40,1.23748,1.23513,Large rainstorm 7/4,09:45:00
312,313,HP,2025-07-21,12:05,9.62,80.0,7.90,NaN,"TSS, Nuts, DOC, Alk",5.0,6,1.10436,1.23295,89.04,1122.45,1.23758,1.23627,used old YSI probe for temp and us,12:05:00
331,332,HP,2025-08-01,11:50,9.41,84.0,8.03,86.55,"TSS, Nuts, DOC, Alk",10.0,7,1.08200,1.21400,88.57,1140.50,1.21500,1.21800,rainstorm night of 7/31 before sampling,11:50:00
350,351,HP,2025-08-14,11:35,9.36,60.0,7.16,95.11,"TSS, Nuts, DOC, Alk",4.0,29,1.11500,1.24700,88.07,1138.77,1.25000,1.25030,,11:35:00
383,384,HP,2025-08-29,13:10,10.92,93.0,6.89,93.42,"TSS, Nuts, DOC, Alk",11.0,51,1.06280,1.19600,88.08,1152.99,1.41600,1.39460,,13:10:00
403,404,HP,2025-09-12,14:15,9.03,96.0,6.46,98.32,"TSS, Nuts, DOC, Alk",19.0,34,1.06470,1.19730,89.62,NaN,1.22560,1.21670,forgot to weigh full bottle.,14:15:00
426,427,HP,2025-09-26,13:40,9.50,97.0,6.57,96.27,"TSS, Nuts, DOC, Alk",3.0,FC20,1.11740,1.24940,88.20,1111.12,1.25570,1.25500,,13:40:00
467,468,HP,2025-10-10,15:15,9.73,97.0,7.97,96.05,"TSS, Nuts, DOC, Alk",6.0,9,1.06360,1.19620,87.45,1119.05,1.25760,1.25350,,15:15:00
513,514,HP,2026-04-11,12:45,4.60,74.0,6.87,82.14,"TSS, Nuts, DOC, Alk",4.0,29,1.11650,1.24930,87.89,1136.69,1.52450,1.49690,,12:45:00
531,532,HP,2026-05-11,12:30,7.80,59.7,6.99,61.99,"TSS, Nuts, DOC, Alk",13.0,FC19,1.06840,1.20080,88.34,1147.86,1.39040,1.37470,lab ec constant 0.911/cm,12:30:00
556,557,HP,2026-06-13,09:10,5.80,72.7,7.12,76.09,"TSS, Nuts, DOC, Alk",13.0,2,1.09790,1.23080,88.34,1085.25,1.23330,1.23260,,09:10:00
573,574,HP,2026-07-10,10:15,8.50,80.4,7.37,86.55,"TSS, Nuts, DOC, Alk",15.0,59,1.09210,1.22420,87.99,1126.26,1.22760,1.22640,,10:15:00
590,591,HP,2026-07-31,11:10,11.00,90.1,6.18,94.80,"TSS, Nuts, Alk",18.0,51,1.06280,1.17920,87.84,1132.66,1.32560,1.32180,Whatman GF/F 934-AH used for TSS,11:10:00
607,608,HP,2026-08-06,09:50,8.20,92.4,7.11,96.88,"TSS, Nuts, Alk",11.0,41,1.06250,1.18860,88.87,1133.05,1.20930,1.20810,no duplicate TSS,09:50:00

--- Data for Site: MFP_Crouch ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
358,359,MFP_Crouch,2025-08-27,13:15,18.3,68.0,7.07,75.63,"TSS, Nuts, DOC, Alk",10.0,58,1.0852,1.2177,58.031,579.85,1.2268,1.2237,non-regular sampling after rain. 500ml bottle ...,13:15:00

--- Data for Site: MainPayette_Gauge ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
356,357,MainPayette_Gauge,2025-08-27,12:30,19.1,47.0,7.07,55.33,"TSS, Nuts, DOC, Alk",16.0,25,1.0984,1.2314,58.144,591.81,1.2751,1.2673,non-regular sampling after rain. 500ml bottle ...,12:30:00

--- Data for Site: Nutcracker_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
167,168,Nutcracker_Cr,2025-03-30,13:15,6.8,82.4,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06423,1.19138,88.35,1054.18,1.20208,1.20025,"New Site, small debris flow occured inbetween ...",13:15:00
180,181,Nutcracker_Cr,2025-04-15,12:15,9.9,100.5,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10430,1.23019,88.23,1103.09,1.23278,1.23224,,12:15:00
198,199,Nutcracker_Cr,2025-04-28,13:10,13.0,103.8,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08265,1.21078,89.00,1093.28,1.21468,1.21361,,13:10:00

--- Data for Site: SFP_Alder_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
4,5,SFP_Alder_Cr,2024-10-12,10:20,12.00,107.0,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,16,1.09500,1.22800,88.350,1159.42,1.23100,1.22800,,10:20:00
18,19,SFP_Alder_Cr,2024-10-19,09:45,7.10,106.8,7.88,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08000,1.21000,87.360,1155.33,1.21700,1.21300,,09:45:00
50,51,SFP_Alder_Cr,2024-11-09,08:30,NaN,111.9,8.41,NaN,"TSS, Nuts, DOC, Alk",NaN,44,1.09200,1.21400,88.070,1115.80,1.21681,1.21594,,08:30:00
67,68,SFP_Alder_Cr,2024-11-24,09:15,NaN,94.3,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10401,1.22797,88.510,1143.17,1.25297,1.24823,,09:15:00
82,83,SFP_Alder_Cr,2025-01-17,07:44,0.20,25.5,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09747,1.22760,88.430,1124.32,1.22865,1.22795,Lab(omega) EC = 127.5 @7.8C,07:44:00
97,98,SFP_Alder_Cr,2025-01-30,16:24,0.50,109.2,8.11,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06184,1.19256,87.450,1158.50,1.20222,1.20111,Lab(metrohm) EC = 111.5 @7.5C,16:24:00
112,113,SFP_Alder_Cr,2025-02-15,08:50,0.60,102.7,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08888,1.21926,87.430,1135.29,1.22298,1.22181,,08:50:00
128,129,SFP_Alder_Cr,2025-03-02,08:15,3.30,96.2,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09389,1.22051,87.840,1126.01,1.22893,1.22688,,08:15:00
143,144,SFP_Alder_Cr,2025-03-19,08:10,3.90,90.1,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09403,1.22094,88.350,1141.14,1.22874,1.22665,,08:10:00
155,156,SFP_Alder_Cr,2025-03-30,08:30,5.60,58.1,7.70,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09782,1.22538,87.800,1140.05,1.24697,1.24309,,08:30:00
168,169,SFP_Alder_Cr,2025-04-15,16:05,8.50,59.0,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,60,1.09413,1.22029,87.630,1121.48,1.24459,1.24034,,16:05:00
186,187,SFP_Alder_Cr,2025-04-28,09:00,6.90,52.9,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10124,1.23313,89.610,1124.44,1.30538,1.29695,,09:00:00
204,205,SFP_Alder_Cr,2025-05-10,15:45,10.40,41.7,7.21,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10429,1.23715,88.540,1150.84,1.33699,1.32745,,15:45:00
223,224,SFP_Alder_Cr,2025-05-27,18:05,11.80,18.6,7.52,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10701,1.23464,44.600,657.59,1.25933,1.25753,tss sample collected in gatorade bottle becuas...,18:05:00
242,243,SFP_Alder_Cr,2025-06-08,13:55,14.30,14.7,7.73,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09836,1.22576,88.390,1127.21,1.25754,1.25497,,13:55:00
261,262,SFP_Alder_Cr,2025-06-22,14:40,14.90,57.8,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,31,1.09428,1.22096,88.400,1146.14,1.23168,1.22989,Rained/snowed late 6/21 through 13:30 on 6/22,14:40:00
280,281,SFP_Alder_Cr,2025-07-07,16:15,17.60,110.8,7.93,54.03,"TSS, Nuts, DOC, Alk",NaN,13,1.06448,1.19237,87.890,1156.10,1.21994,1.21607,Large rainstorm 7/4,16:15:00
299,300,SFP_Alder_Cr,2025-07-21,15:05,14.24,62.0,7.83,NaN,"TSS, Nuts, DOC, Alk",4.0,5,1.08908,1.21634,87.650,1132.09,1.22811,1.22575,used old YSI probe for temp and us,15:05:00
318,319,SFP_Alder_Cr,2025-08-01,12:55,14.62,100.0,8.08,65.82,"TSS, Nuts, DOC, Alk",4.0,13,1.06300,1.19100,87.630,1137.63,1.21600,1.21200,"rainstorm night of 7/31 before sampling, river...",12:55:00
337,338,SFP_Alder_Cr,2025-08-14,08:43,13.17,44.0,7.49,61.59,"TSS, Nuts, DOC, Alk",9.0,32,1.08000,1.21200,88.340,1155.71,1.22500,1.22380,,08:43:00
370,371,SFP_Alder_Cr,2025-08-27,17:20,16.80,59.0,6.96,75.36,"TSS, Nuts, DOC, Alk",9.0,"1,HZ,FC20,55,51,44,50,14,17,7,18",11.96650,13.43370,58.226,594.02,17.50040,16.79060,non-regular sampling after rain. 500ml bottle ...,17:20:00
371,372,SFP_Alder_Cr,2025-08-29,12:05,15.26,65.0,7.16,65.66,"TSS, Nuts, DOC, Alk",2.0,45,1.10080,1.23380,88.560,1142.10,1.29370,1.28490,,12:05:00
409,410,SFP_Alder_Cr,2025-09-12,18:55,14.72,102.0,6.65,103.50,"TSS, Nuts, DOC, Alk",1.0,14,1.07620,1.20900,88.380,1153.68,1.21360,1.21250,,18:55:00
432,433,SFP_Alder_Cr,2025-09-26,19:00,13.70,105.0,6.58,104.20,"TSS, Nuts, DOC, Alk",5.0,41,1.06220,1.19540,88.380,1123.35,1.19850,1.19690,,19:00:00
453,454,SFP_Alder_Cr,2025-10-04,09:30,NaN,NaN,7.39,79.53,TSS,25.0,"57,FC11",2.15780,2.42450,102.860,1080.07,2.77360,2.73050,non-regular sampling after 10/03 rain.,09:30:00
474,475,SFP_Alder_Cr,2025-10-10,18:15,11.60,104.0,8.26,104.30,"TSS, Nuts, DOC, Alk",17.0,FC17,1.09010,1.22200,88.730,1108.92,1.23110,1.23030,,18:15:00
488,489,SFP_Alder_Cr,2025-12-04,16:20,1.60,109.0,7.02,94.19,"TSS, Nuts, DOC, Alk",9.0,FC11,1.07870,1.21170,88.340,1129.21,1.21370,1.21300,,16:20:00
489,490,SFP_Alder_Cr,2026-02-07,10:30,NaN,89.0,7.69,75.90,"TSS, Nuts, DOC, Alk",8.0,45,1.10050,1.23260,88.510,1162.78,1.23740,1.23610,Field EC CR800. Notebook values from Omega,10:30:00
512,513,SFP_Alder_Cr,2026-03-08,18:25,6.50,86.0,7.15,97.88,"TSS, Nuts, DOC, Alk",9.0,28,1.10870,1.24040,88.330,1138.94,1.24360,1.24270,,18:25:00
528,529,SFP_Alder_Cr,2026-04-11,17:45,9.00,64.2,6.95,66.87,"TSS, Nuts, DOC, Alk",15.0,40,1.10630,1.23840,87.970,1128.68,1.34200,1.32840,1 of 2 SFP_Alder samples collected from this s...,17:45:00
547,548,SFP_Alder_Cr,2026-05-11,18:20,11.10,49.9,7.15,53.00,"TSS, Nuts, DOC, Alk",18.0,36,1.08020,1.21270,87.830,1129.44,1.31060,1.30400,,18:20:00
564,565,SFP_Alder_Cr,2026-06-13,12:05,13.30,64.5,7.18,68.01,"TSS, Nuts, DOC, Alk",16.0,31,1.09460,1.22730,88.450,1136.51,1.23910,1.23750,,12:05:00
581,582,SFP_Alder_Cr,2026-07-10,13:10,17.30,69.8,7.19,75.18,"TSS, Nuts, DOC, Alk",14.0,28,1.10830,1.24170,88.520,1136.94,1.27970,1.27550,,13:10:00
598,599,SFP_Alder_Cr,2026-07-31,14:05,14.80,63.0,7.19,66.43,"TSS, Nuts, Alk",14.0,33,1.10680,1.22320,88.530,1108.81,1.26990,1.26600,Whatman GF/F 934-AH used for TSS,14:05:00
615,616,SFP_Alder_Cr,2026-08-06,12:40,12.90,61.7,7.24,66.86,"TSS, Nuts, Alk",20.0,49,1.08830,1.21560,88.280,1136.24,1.23620,1.23410,duplicate TSS bottle labeled site 14,12:40:00

--- Data for Site: SFP_Alder_Cr_AM ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
529,530,SFP_Alder_Cr_AM,2026-04-11,11:00,9.3,64.9,7.13,68.31,TSS,18.0,27,1.1008,1.2342,87.83,1148.56,1.3014,1.2933,2 of 2 SFP_Alder samples collected to compare ...,11:00:00

--- Data for Site: SFP_BJ ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
6,7,SFP_BJ,2024-10-12,12:30,9.40,98.4,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Glass vial broke, sample gone",12:30:00
32,33,SFP_BJ,2024-10-19,18:20,9.60,97.8,8.13,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.11000,1.23000,101.400,1143.84,1.23400,1.23000,"Glass vial broke, sample gone",18:20:00
47,48,SFP_BJ,2024-11-04,14:00,5.80,93.0,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,40,1.10400,1.23700,88.010,1105.42,1.24520,1.23789,,14:00:00
53,54,SFP_BJ,2024-11-09,10:30,NaN,101.5,8.22,NaN,"TSS, Nuts, DOC, Alk",NaN,47,1.09500,1.21800,88.110,1121.83,1.22115,1.22053,,10:30:00
70,71,SFP_BJ,2024-11-24,16:00,NaN,105.1,7.82,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06384,1.18838,87.790,1108.58,1.19682,1.19571,Bottle says SFP at warm springs,16:00:00
85,86,SFP_BJ,2025-01-17,09:58,1.20,92.5,7.14,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06119,1.19206,88.470,1103.92,1.19452,1.19363,Lab(omega) EC = 114.5 @8.3C,09:58:00
100,101,SFP_BJ,2025-01-30,14:10,NaN,98.8,7.77,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09178,1.22851,87.620,1108.60,1.23037,1.23037,Lab(metrohm) EC = 103.0 @4.4C,14:10:00
115,116,SFP_BJ,2025-02-15,14:50,3.30,92.4,8.04,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10355,1.23456,87.800,1112.77,1.24461,1.24045,,14:50:00
131,132,SFP_BJ,2025-03-02,18:40,6.10,93.1,7.40,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07619,1.20186,88.980,1150.60,1.20924,1.20818,,18:40:00
146,147,SFP_BJ,2025-03-19,10:15,1.10,93.6,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09785,1.22314,87.440,1118.01,1.22588,1.22503,,10:15:00
158,159,SFP_BJ,2025-03-30,10:55,4.50,81.1,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11092,1.23704,88.440,1122.86,1.26056,1.25819,,10:55:00
171,172,SFP_BJ,2025-04-15,14:40,9.40,75.9,7.66,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11310,1.23828,88.990,1152.88,1.26024,1.25817,,14:40:00
189,190,SFP_BJ,2025-04-28,10:20,5.70,63.9,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09453,1.22665,88.720,1142.14,1.27748,1.27417,,10:20:00
207,208,SFP_BJ,2025-05-10,14:30,10.40,45.6,7.18,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08271,1.21348,87.650,1157.67,1.35082,1.34374,,14:30:00
226,227,SFP_BJ,2025-05-27,16:00,11.50,31.3,7.39,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08499,1.21597,87.890,1111.25,1.31336,1.31050,,16:00:00
245,246,SFP_BJ,2025-06-08,12:35,11.40,25.3,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08511,1.21321,88.190,1124.24,1.22617,1.22471,,12:35:00
264,265,SFP_BJ,2025-06-22,12:55,9.00,54.1,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10703,1.23373,87.640,1135.51,1.23691,1.23604,Rained/snowed late 6/21 through 13:30 on 6/22,12:55:00
283,284,SFP_BJ,2025-07-07,14:30,16.00,106.7,7.75,49.15,"TSS, Nuts, DOC, Alk",NaN,46,1.10144,1.22874,88.400,1159.70,1.25283,1.24925,Large rainstorm 7/4,14:30:00
302,303,SFP_BJ,2025-07-21,13:25,14.33,74.0,7.44,NaN,"TSS, Nuts, DOC, Alk",7.0,23,1.10267,1.23013,89.010,1143.23,1.23394,1.23301,used old YSI probe for temp and us,13:25:00
321,322,SFP_BJ,2025-08-01,13:55,17.17,83.0,8.09,81.43,"TSS, Nuts, DOC, Alk",3.0,4,1.10600,1.23100,88.210,1116.96,1.24700,1.23900,rainstorm night of 7/31 before sampling,13:55:00
340,341,SFP_BJ,2025-08-14,10:35,11.41,63.0,7.16,95.34,"TSS, Nuts, DOC, Alk",12.0,68,1.09500,1.22500,88.220,1099.53,1.22600,1.22610,,10:35:00
367,368,SFP_BJ,2025-08-27,16:05,14.40,77.0,6.68,90.74,"TSS, Nuts, DOC, Alk",5.0,"37,8,13,29,31,36",6.54710,7.34530,58.078,603.64,8.74420,8.59350,non-regular sampling after rain. 500ml bottle ...,16:05:00
374,375,SFP_BJ,2025-08-29,10:30,10.47,86.0,6.92,87.35,"TSS, Nuts, DOC, Alk",3.0,23,1.10250,1.23430,88.190,1158.74,1.29810,1.29110,,10:30:00
406,407,SFP_BJ,2025-09-12,17:40,13.66,91.0,6.43,93.16,"TSS, Nuts, DOC, Alk",10.0,13,1.06400,1.19540,87.570,1153.48,1.20360,1.20210,,17:40:00
429,430,SFP_BJ,2025-09-26,17:40,13.21,94.0,6.63,92.57,"TSS, Nuts, DOC, Alk",14.0,7,1.08260,1.21540,88.520,1119.17,1.21900,1.21830,,17:40:00
441,442,SFP_BJ,2025-10-04,09:50,8.99,88.0,7.95,89.91,TSS,11.0,48,1.09920,1.23140,88.730,1081.82,1.29770,1.29150,non-regular sampling after 10/03 rain.,09:50:00
472,473,SFP_BJ,2025-10-10,16:40,11.71,93.0,7.77,92.99,"TSS, Nuts, DOC, Alk",18.0,32,1.07860,1.21020,87.830,1141.43,1.22670,1.22600,,16:40:00
485,486,SFP_BJ,2025-12-04,14:05,1.80,92.0,7.29,87.99,"TSS, Nuts, DOC, Alk",14.0,20,1.06170,1.19380,88.520,1122.37,1.19890,1.19810,,14:05:00
499,500,SFP_BJ,2026-02-07,15:55,NaN,88.0,6.42,85.11,"TSS, Nuts, DOC, Alk",2.0,8,1.10710,1.24140,88.790,1143.46,1.24720,1.24600,,15:55:00
509,510,SFP_BJ,2026-03-08,16:10,7.50,88.0,7.02,101.00,"TSS, Nuts, DOC, Alk",6.0,25,1.09840,1.23100,87.440,1131.04,1.23380,1.23340,,16:10:00
525,526,SFP_BJ,2026-04-11,16:15,7.80,67.8,6.97,69.84,"TSS, Nuts, DOC, Alk",12.0,39,1.10140,1.23480,87.870,1122.36,1.40930,1.39500,,16:15:00
544,545,SFP_BJ,2026-05-11,16:00,11.50,47.6,7.06,50.53,"TSS, Nuts, DOC, Alk",16.0,46,1.10100,1.23360,88.450,1143.06,1.37120,1.36320,,16:00:00
561,562,SFP_BJ,2026-06-13,10:40,8.70,58.4,7.41,61.88,"TSS, Nuts, DOC, Alk",14.0,47,1.09690,1.23000,88.510,1116.70,1.23800,1.23700,,10:40:00
578,579,SFP_BJ,2026-07-10,11:45,12.20,66.9,7.49,72.38,"TSS, Nuts, DOC, Alk",7.0,58,1.08320,1.21600,89.020,1126.49,1.22210,1.22090,,11:45:00
595,596,SFP_BJ,2026-07-31,12:30,14.20,83.7,6.81,87.37,"TSS, Nuts, Alk",10.0,29,1.11710,1.23470,87.530,1106.06,2.57020,2.55980,Whatman GF/F 934-AH used for TSS,12:30:00
612,613,SFP_BJ,2026-08-06,11:10,11.20,87.3,7.07,93.65,"TSS, Nuts, Alk",19.0,FC16,1.10800,1.23290,87.470,1135.19,1.73470,1.72910,no duplicate TSS,11:10:00

--- Data for Site: SFP_Canyon_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
14,15,SFP_Canyon_Cr,2024-10-12,16:00,11.80,83.7,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11000,1.24600,88.36,1152.62,1.24900,1.24800,,16:00:00
26,27,SFP_Canyon_Cr,2024-10-19,13:15,7.30,81.7,8.09,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08500,1.21400,103.07,1130.51,1.21700,1.21600,,13:15:00
43,44,SFP_Canyon_Cr,2024-11-03,15:10,5.70,78.4,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,42,1.06900,1.19300,101.22,1065.01,1.19930,1.19448,,15:10:00
62,63,SFP_Canyon_Cr,2024-11-09,12:10,NaN,82.1,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,53,1.08300,1.21100,88.91,1144.09,1.21080,1.21022,,12:10:00
79,80,SFP_Canyon_Cr,2024-11-24,14:15,NaN,77.5,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08550,1.20881,88.46,1137.13,1.21528,1.21436,,14:15:00
94,95,SFP_Canyon_Cr,2025-01-17,14:19,1.90,75.4,7.50,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08280,1.21334,88.36,1126.74,1.21895,1.21649,Lab(omega) EC = 93.70 @7.9C,14:19:00
109,110,SFP_Canyon_Cr,2025-01-30,10:35,0.30,48.2,8.14,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06288,1.19365,87.46,1115.20,1.19501,1.19404,Lab(metrohm) EC = 88.88 @5.3C,10:35:00
124,125,SFP_Canyon_Cr,2025-02-15,16:30,3.50,73.0,8.06,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08241,1.21369,88.36,1141.91,1.22480,1.22148,,16:30:00
140,141,SFP_Canyon_Cr,2025-03-02,16:20,5.10,75.4,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06128,1.18713,88.32,1148.42,1.22394,1.22004,,16:20:00
152,153,SFP_Canyon_Cr,2025-03-19,13:50,4.10,72.7,7.71,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10376,1.22966,88.44,1119.97,1.23447,1.23343,,13:50:00
164,165,SFP_Canyon_Cr,2025-03-30,15:00,7.30,69.1,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10659,1.23238,88.55,1113.29,1.25168,1.25051,,15:00:00
177,178,SFP_Canyon_Cr,2025-04-15,12:35,6.50,59.8,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,1,1.08497,1.21185,88.36,1151.81,1.23882,1.23741,,12:35:00
195,196,SFP_Canyon_Cr,2025-04-28,13:30,7.70,45.2,7.91,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10635,1.23833,88.44,1133.73,1.25607,1.25442,,13:30:00
213,214,SFP_Canyon_Cr,2025-05-10,12:35,7.80,35.9,7.12,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06432,1.19784,88.50,1137.44,1.25111,1.24572,,12:35:00
232,233,SFP_Canyon_Cr,2025-05-27,14:20,10.00,24.4,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11147,1.24295,87.84,1123.47,1.26972,1.26789,,14:20:00
251,252,SFP_Canyon_Cr,2025-06-08,10:50,8.80,9.1,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06406,1.19121,88.21,1146.64,1.20562,1.20363,,10:50:00
270,271,SFP_Canyon_Cr,2025-06-22,10:10,6.90,36.4,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08294,1.21068,87.87,1141.47,1.21315,1.21239,Rained/snowed late 6/21 through 13:30 on 6/22,10:10:00
290,291,SFP_Canyon_Cr,2025-07-07,12:20,13.60,78.3,7.58,35.87,"TSS, Nuts, DOC, Alk",NaN,59,1.09239,1.21851,87.45,1129.90,1.22646,1.22531,Large rainstorm 7/4,12:20:00
309,310,SFP_Canyon_Cr,2025-07-21,11:00,12.01,56.0,8.02,NaN,"TSS, Nuts, DOC, Alk",2.0,34,1.06505,1.19284,89.38,1145.99,1.19494,1.19405,used old YSI probe for temp and us,11:00:00
328,329,SFP_Canyon_Cr,2025-08-01,11:05,11.90,62.0,7.11,127.80,"TSS, Nuts, DOC, Alk",13.0,18,1.11200,1.24400,88.34,1084.70,1.24400,1.24700,rainstorm night of 7/31 before sampling,11:05:00
347,348,SFP_Canyon_Cr,2025-08-14,16:20,17.86,59.0,7.16,75.64,"TSS, Nuts, DOC, Alk",8.0,54,1.08100,1.20900,88.59,1148.32,1.21100,1.21000,,16:20:00
362,363,SFP_Canyon_Cr,2025-08-27,15:05,12.50,67.0,7.05,73.65,"TSS, Nuts, DOC, Alk",13.0,59,1.09220,1.22640,57.78,604.07,1.30540,1.29590,non-regular sampling after rain. 500ml bottle ...,15:05:00
380,381,SFP_Canyon_Cr,2025-08-29,12:20,12.79,69.0,6.58,66.98,"TSS, Nuts, DOC, Alk",14.0,43,1.09670,1.22980,88.51,1146.87,1.25990,1.25610,,12:20:00
398,399,SFP_Canyon_Cr,2025-09-12,12:50,10.86,74.0,7.02,73.89,"TSS, Nuts, DOC, Alk",14.0,59,1.09190,1.22380,101.51,1158.76,1.22770,1.22610,,12:50:00
421,422,SFP_Canyon_Cr,2025-09-26,16:20,13.31,77.0,6.45,75.82,"TSS, Nuts, DOC, Alk",19.0,27,1.10090,1.23560,87.47,1081.66,1.23830,1.23670,,16:20:00
447,448,SFP_Canyon_Cr,2025-10-04,10:55,9.12,71.0,8.04,72.54,TSS,22.0,40,1.10660,1.24030,89.61,1115.18,1.25070,1.24910,non-regular sampling after 10/03 rain.,10:55:00
461,462,SFP_Canyon_Cr,2025-10-10,13:15,9.61,76.0,7.45,80.83,"TSS, Nuts, DOC, Alk",3.0,FC18,1.05270,1.18490,88.20,1114.13,1.18820,1.18850,,13:15:00
480,481,SFP_Canyon_Cr,2025-12-04,11:20,1.01,76.0,7.65,71.11,"TSS, Nuts, DOC, Alk",16.0,68,1.09390,1.22760,88.46,1064.47,1.22970,1.22970,,11:20:00
494,495,SFP_Canyon_Cr,2026-02-07,13:45,NaN,71.0,6.41,68.38,"TSS, Nuts, DOC, Alk",9.0,HZ,1.06920,1.20230,88.33,1164.74,1.20390,1.20330,,13:45:00
504,505,SFP_Canyon_Cr,2026-03-08,13:20,5.10,70.0,6.74,84.51,"TSS, Nuts, DOC, Alk",15.0,59,1.09220,1.22580,87.97,1057.31,1.22790,1.22700,,13:20:00
520,521,SFP_Canyon_Cr,2026-04-11,14:40,7.10,52.4,7.40,53.81,"TSS, Nuts, DOC, Alk",1.0,7,1.08250,1.21290,88.38,1165.60,1.29060,1.28270,,14:40:00
539,540,SFP_Canyon_Cr,2026-05-11,14:35,10.20,27.0,7.06,37.87,"TSS, Nuts, DOC, Alk",7.0,11,1.08570,1.21910,88.99,1139.21,1.28290,1.27880,,14:35:00
553,554,SFP_Canyon_Cr,2026-06-13,08:00,7.60,42.0,7.20,44.92,"TSS, Nuts, DOC, Alk",8.0,FC17,1.08950,1.22240,88.53,1130.53,1.22760,1.22650,,08:00:00
570,571,SFP_Canyon_Cr,2026-07-10,09:05,10.50,49.0,7.54,53.30,"TSS, Nuts, DOC, Alk",6.0,FC15,1.10780,1.24190,87.46,1138.26,1.24490,1.24390,,09:05:00
587,588,SFP_Canyon_Cr,2026-07-31,10:15,12.30,66.0,6.90,69.41,"TSS, Nuts, Alk",8.0,34,1.06560,1.18270,88.53,1116.02,2.00690,1.99830,Whatman GF/F 934-AH used for TSS,10:15:00
604,605,SFP_Canyon_Cr,2026-08-06,08:50,10.10,67.8,7.14,75.31,"TSS, Nuts, Alk",2.0,38,1.09850,1.22570,89.61,1137.21,1.46050,1.45710,duplicate TSS bottle labeled site 2,08:50:00

--- Data for Site: SFP_Chap ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
9,10,SFP_Chap,2024-10-12,13:30,10.50,89.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Glass vial broke, sample gone",13:30:00
22,23,SFP_Chap,2024-10-19,12:00,5.50,90.4,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,10,1.08300,1.21200,103.19,1121.86,1.21500,1.21400,"Glass vial broke, sample gone",12:00:00
44,45,SFP_Chap,2024-11-04,13:00,5.10,86.7,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,37,1.08000,1.21000,88.64,1139.50,1.21880,1.21068,,13:00:00
55,56,SFP_Chap,2024-11-09,10:45,NaN,95.7,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,49,1.08800,1.21000,88.12,1130.00,1.21255,1.21184,,10:45:00
72,73,SFP_Chap,2024-11-24,11:20,NaN,91.0,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10635,1.22996,88.68,1136.98,1.23372,1.23261,,11:20:00
87,88,SFP_Chap,2025-01-17,16:04,NaN,NaN,7.03,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07589,1.20660,88.35,715.64,1.21031,1.20928,Lab(omega) EC = 101.6 @11.9C,16:04:00
102,103,SFP_Chap,2025-01-30,13:37,1.80,91.2,7.95,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10059,1.23101,87.83,920.00,1.23209,1.23167,Lab(metrohm) EC = 95.39 @5.1C,13:37:00
117,118,SFP_Chap,2025-02-15,16:05,3.90,83.9,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07609,1.20675,87.47,1089.64,1.21370,1.21233,,16:05:00
133,134,SFP_Chap,NaT,0n:an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dangerous conditions, could not sample",NaT
148,149,SFP_Chap,2025-03-19,11:25,1.10,87.2,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06326,1.19051,87.48,1124.43,1.19770,1.19595,,11:25:00
160,161,SFP_Chap,2025-03-30,11:45,4.60,82.4,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07632,1.20318,88.45,1143.75,1.21837,1.21578,,11:45:00
173,174,SFP_Chap,2025-04-15,14:15,8.50,75.6,7.54,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07538,1.20229,88.45,1151.89,1.21678,1.21457,,14:15:00
191,192,SFP_Chap,2025-04-28,10:40,6.20,61.5,7.83,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08333,1.21148,87.83,1138.43,1.25432,1.25067,,10:40:00
209,210,SFP_Chap,2025-05-10,14:10,10.90,44.8,7.33,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.10631,1.23682,88.44,1149.29,1.27844,1.25749,tss sample had small twig,14:10:00
228,229,SFP_Chap,2025-05-27,15:10,10.90,23.7,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08587,1.21625,88.43,1114.39,1.25804,1.25597,,15:10:00
247,248,SFP_Chap,2025-06-08,12:10,10.40,11.1,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08587,1.21298,88.36,1140.05,1.22463,1.22338,,12:10:00
266,267,SFP_Chap,2025-06-22,12:30,9.00,47.3,7.30,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10765,1.23207,87.47,1113.61,1.23682,1.23547,Rained/snowed late 6/21 through 13:30 on 6/22,12:30:00
285,286,SFP_Chap,2025-07-07,13:10,14.80,94.3,7.55,43.29,"TSS, Nuts, DOC, Alk",NaN,50,1.08788,1.21594,87.50,1151.80,1.24049,1.23768,Large rainstorm 7/4,13:10:00
304,305,SFP_Chap,2025-07-21,12:50,13.75,67.0,7.41,NaN,"TSS, Nuts, DOC, Alk",9.0,12,1.06649,1.19515,87.50,1142.76,1.19861,1.19758,used old YSI probe for temp and us,12:50:00
323,324,SFP_Chap,2025-08-01,12:30,13.30,73.0,8.11,84.19,"TSS, Nuts, DOC, Alk",9.0,19,1.07500,1.20700,87.49,NaN,NaN,NaN,"rainstorm night of 7/31 before sampling, TSS b...",12:30:00
342,343,SFP_Chap,2025-08-14,10:55,12.12,60.0,7.14,87.09,"TSS, Nuts, DOC, Alk",18.0,59,1.09400,1.22600,88.03,1097.46,1.22600,1.22620,,10:55:00
365,366,SFP_Chap,2025-08-27,15:45,14.30,73.0,6.89,84.05,"TSS, Nuts, DOC, Alk",17.0,48,1.09940,1.23290,58.26,588.59,1.36870,1.35210,non-regular sampling after rain. 500ml bottle ...,15:45:00
376,377,SFP_Chap,2025-08-29,10:00,9.99,80.0,6.61,82.00,"TSS, Nuts, DOC, Alk",7.0,10,1.08270,1.21460,89.00,1144.90,1.26630,1.25970,,10:00:00
404,405,SFP_Chap,2025-09-12,17:15,13.40,84.0,6.25,86.68,"TSS, Nuts, DOC, Alk",13.0,18,1.11080,1.24210,88.34,NaN,1.24780,1.24680,forgot to weigh full bottle.,17:15:00
427,428,SFP_Chap,2025-09-26,17:10,13.14,87.0,6.63,84.98,"TSS, Nuts, DOC, Alk",8.0,55,1.09420,1.22670,88.51,1090.22,1.23020,1.22840,,17:10:00
443,444,SFP_Chap,2025-10-04,10:15,8.53,82.0,7.45,82.90,TSS,3.0,59,1.09270,1.22620,88.20,1120.05,1.27640,1.27060,non-regular sampling after 10/03 rain.,10:15:00
470,471,SFP_Chap,2025-10-10,16:10,11.45,85.0,7.35,86.47,"TSS, Nuts, DOC, Alk",7.0,46,1.10070,1.23260,89.00,1139.29,1.24340,1.24290,,16:10:00
483,484,SFP_Chap,2025-12-04,13:35,0.97,83.0,7.64,80.11,"TSS, Nuts, DOC, Alk",13.0,5,1.08910,1.22310,88.36,1093.40,1.22690,1.22600,slow water,13:35:00
497,498,SFP_Chap,2026-02-07,15:20,NaN,81.0,6.38,78.26,"TSS, Nuts, DOC, Alk",1.0,38,1.09800,1.22850,88.38,1138.92,1.23140,1.23060,,15:20:00
507,508,SFP_Chap,2026-03-08,15:00,6.70,81.0,7.07,92.29,"TSS, Nuts, DOC, Alk",7.0,FC17,1.08960,1.22200,89.00,1129.72,1.22320,1.22240,,15:00:00
523,524,SFP_Chap,2026-04-11,15:40,7.60,63.6,7.24,65.81,"TSS, Nuts, DOC, Alk",17.0,32,1.07860,1.21030,88.72,1158.18,1.32470,1.31410,,15:40:00
542,543,SFP_Chap,2026-05-11,15:35,11.20,44.2,7.15,46.49,"TSS, Nuts, DOC, Alk",12.0,FC4,1.05880,1.19170,87.87,1132.07,1.28460,1.27690,,15:35:00
559,560,SFP_Chap,2026-06-13,10:15,8.30,50.8,6.62,53.84,"TSS, Nuts, DOC, Alk",18.0,FC12,1.08850,1.22180,87.83,1133.33,1.22780,1.22650,,10:15:00
576,577,SFP_Chap,2026-07-10,11:20,11.70,55.2,7.54,64.03,"TSS, Nuts, DOC, Alk",3.0,43,1.09640,1.22880,88.21,1110.36,1.23330,1.23210,,11:20:00
593,594,SFP_Chap,2026-07-31,12:05,13.90,61.3,7.11,79.13,"TSS, Nuts, Alk",19.0,23,1.10280,1.21930,87.45,1107.85,1.47120,1.46350,Whatman GF/F 934-AH used for TSS,12:05:00
610,611,SFP_Chap,2026-08-06,10:40,10.90,79.8,6.84,84.86,"TSS, Nuts, Alk",9.0,43,1.09680,1.22470,88.36,1137.59,1.38370,1.37990,no duplicate TSS,10:40:00

--- Data for Site: SFP_DW ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
5,6,SFP_DW,2024-10-12,11:15,9.80,103.0,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06000,1.19500,88.490,1156.48,1.19600,1.19400,,11:15:00
19,20,SFP_DW,2024-10-19,10:30,5.20,103.2,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07600,1.21200,102.420,1123.30,1.21500,1.21300,Glass bottle cracked but still held some water...,10:30:00
49,50,SFP_DW,2024-11-04,16:15,4.90,99.0,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,43,1.09600,1.22300,101.440,1091.72,1.23060,1.22174,,16:15:00
51,52,SFP_DW,2024-11-09,09:40,NaN,104.8,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,45,1.09900,1.22300,88.790,1115.61,1.22771,1.22673,,09:40:00
68,69,SFP_DW,2024-11-24,09:54,NaN,115.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11079,1.23411,88.350,1137.70,1.24575,1.24357,,09:54:00
83,84,SFP_DW,2025-01-17,08:22,0.30,5.3,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06382,1.18881,88.360,1124.99,1.18921,1.18879,Lab(omega) EC = 120.8 @8.0C,08:22:00
98,99,SFP_DW,2025-01-30,15:50,0.50,92.2,8.04,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10346,1.23338,88.520,1161.60,1.23482,1.23414,Lab(metrohm) EC = 106.3 @4.7C,15:50:00
113,114,SFP_DW,2025-02-15,13:00,0.30,99.3,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,25,1.09773,1.22826,88.410,1140.12,1.24042,1.23833,,13:00:00
129,130,SFP_DW,2025-03-02,08:55,2.20,98.7,7.34,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06467,1.19248,88.360,1138.82,1.20327,1.20161,,08:55:00
144,145,SFP_DW,2025-03-19,08:41,1.80,99.9,7.65,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06415,1.19247,88.520,1111.06,1.19563,1.19446,,08:41:00
156,157,SFP_DW,2025-03-30,09:05,4.80,81.9,7.61,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06159,1.18897,87.860,1129.93,1.21011,1.20605,,09:05:00
169,170,SFP_DW,2025-04-15,15:30,8.50,69.0,7.63,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08749,1.21478,88.520,1140.66,1.23038,1.22771,,15:30:00
187,188,SFP_DW,2025-04-28,09:30,6.00,58.9,7.93,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09152,1.22256,87.870,1124.32,1.28359,1.27662,,09:30:00
205,206,SFP_DW,2025-05-10,15:15,9.70,44.8,7.32,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11105,1.24201,87.450,1140.98,1.33674,1.32903,,15:15:00
224,225,SFP_DW,2025-05-27,17:30,11.80,24.8,7.50,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06626,1.19711,88.740,1125.86,1.24288,1.23997,,17:30:00
243,244,SFP_DW,2025-06-08,13:20,12.70,29.4,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,3,1.10665,1.23319,89.000,1145.50,1.25015,1.24864,,13:20:00
262,263,SFP_DW,2025-06-22,13:40,12.20,58.4,7.20,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06421,1.19139,88.550,1152.43,1.19579,1.19472,Rained/snowed late 6/21 through 13:30 on 6/22,13:40:00
281,282,SFP_DW,2025-07-07,15:45,17.50,117.7,7.50,52.63,"TSS, Nuts, DOC, Alk",NaN,19,1.07578,1.20219,88.380,1155.10,1.21849,1.21532,Large rainstorm 7/4,15:45:00
300,301,SFP_DW,2025-07-21,14:25,16.45,79.0,7.89,NaN,"TSS, Nuts, DOC, Alk",12.0,2,1.09774,1.22551,87.900,1152.45,1.22902,1.22756,used old YSI probe for temp and us,14:25:00
319,320,SFP_DW,2025-08-01,13:07,13.89,80.0,8.03,84.93,"TSS, Nuts, DOC, Alk",1.0,23,1.10100,1.23000,88.400,1131.90,1.26300,1.25800,rainstorm night of 7/31 before sampling,13:07:00
338,339,SFP_DW,2025-08-14,09:24,14.64,73.0,7.27,100.10,"TSS, Nuts, DOC, Alk",5.0,33,1.10700,1.23900,88.870,1126.54,1.24300,1.24310,,09:24:00
369,370,SFP_DW,2025-08-27,16:50,16.10,79.0,6.74,90.87,"TSS, Nuts, DOC, Alk",6.0,"40,6,30,68",3.29810,3.69790,57.163,592.81,4.39570,4.31310,non-regular sampling after rain. 500ml bottle ...,16:50:00
372,373,SFP_DW,2025-08-29,11:30,14.06,91.0,6.76,92.74,"TSS, Nuts, DOC, Alk",4.0,1,1.08400,1.21710,87.640,1130.54,1.29590,1.28450,,11:30:00
408,409,SFP_DW,2025-09-12,18:26,14.22,96.0,6.30,96.69,"TSS, Nuts, DOC, Alk",9.0,48,1.09880,1.23140,88.340,1146.89,1.23810,1.23650,the tin number label looks like H8,18:26:00
431,432,SFP_DW,2025-09-26,18:30,12.77,99.0,6.27,97.29,"TSS, Nuts, DOC, Alk",16.0,12,1.06640,1.19940,88.460,1083.70,1.20350,1.20260,,18:30:00
439,440,SFP_DW,2025-10-04,09:10,10.42,92.0,7.76,93.92,TSS,1.0,47,1.09720,1.22980,88.400,1107.13,1.31750,1.30740,non-regular sampling after 10/03 rain.,09:10:00
455,456,SFP_DW,2025-10-10,11:00,8.46,97.0,8.20,98.03,"TSS, Nuts, DOC, Alk",19.0,FC10,1.10650,1.23870,87.460,1091.11,1.24970,1.24750,,11:00:00
487,488,SFP_DW,2025-12-04,16:00,0.92,90.0,7.38,90.10,"TSS, Nuts, DOC, Alk",12.0,13,1.06440,1.19760,87.890,1114.74,1.20160,1.20090,,16:00:00
490,491,SFP_DW,2026-02-07,11:15,NaN,82.0,6.27,88.67,"TSS, Nuts, DOC, Alk",16.0,43,1.09610,1.22750,88.440,1061.48,1.23050,1.22960,Still need temp,11:15:00
511,512,SFP_DW,2026-03-08,17:35,6.70,87.0,6.83,99.27,"TSS, Nuts, DOC, Alk",18.0,R21,1.10800,1.23970,87.840,1116.28,1.24240,1.24200,,17:35:00
527,528,SFP_DW,2026-04-11,17:10,8.30,66.6,6.91,68.06,"TSS, Nuts, DOC, Alk",13.0,37,1.08080,1.21440,88.340,1133.67,1.33780,1.32420,1 of 2 SFP_DW samples collected from this site...,17:10:00
546,547,SFP_DW,2026-05-11,17:40,11.50,48.5,9.26,45.96,"TSS, Nuts, DOC, Alk",14.0,44,1.09170,1.22520,88.510,1137.62,1.33380,1.32660,,17:40:00
563,564,SFP_DW,2026-06-13,11:30,10.80,63.8,7.52,67.44,"TSS, Nuts, DOC, Alk",15.0,R21,1.10790,1.24100,87.970,1140.07,1.25080,1.24950,,11:30:00
580,581,SFP_DW,2026-07-10,12:35,15.60,73.0,7.21,78.21,"TSS, Nuts, DOC, Alk",18.0,FC26,1.07960,1.21200,87.850,1120.90,1.21760,1.21580,,12:35:00
597,598,SFP_DW,2026-07-31,13:35,18.00,88.9,7.00,92.43,"TSS, Nuts, DOC,Alk",11.0,55,1.09420,1.21010,88.860,1119.81,1.31470,1.30780,Whatman GF/F 934-AH used for DOC/TSS,13:35:00
614,615,SFP_DW,2026-08-06,12:05,14.90,91.1,7.15,96.99,"TSS, Nuts, Alk",15.0,FC27,1.11170,1.23770,87.980,1116.23,1.28030,1.27480,no duplicate TSS,12:05:00

--- Data for Site: SFP_DW_AM ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
530,531,SFP_DW_AM,2026-04-11,11:45,7.5,67.4,7.14,70.58,TSS,8.0,17,1.0917,1.2229,88.51,1153.49,1.3333,1.3199,2 of 2 SFP_DW samples collected compare AM and...,11:45:00

--- Data for Site: SFP_Staircase ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
357,358,SFP_Staircase,2025-08-27,13:00,17.1,79.0,6.94,95.1,"TSS, Nuts, DOC, Alk",19.0,"16,32,27,41",4.3401,4.8741,57.94,597.88,5.7575,5.5978,non-regular sampling after rain. 500ml bottle ...,13:00:00

--- Data for Site: SFP_Wapiti ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
29,30,SFP_Wapiti,2024-10-19,15:00,7.60,78.2,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,2,1.15000,1.27000,101.07,1152.46,1.22900,1.22829,"Glass vial broke, sample gone",15:00:00
33,34,SFP_Wapiti,2024-11-03,10:30,5.10,75.1,7.82,NaN,"TSS, Nuts, DOC, Alk",NaN,27,1.10100,1.22700,88.73,1142.95,1.23120,1.22705,,10:30:00
65,66,SFP_Wapiti,2024-11-09,12:40,NaN,86.6,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08300,1.20700,88.31,1117.76,1.21005,1.20902,,12:40:00
127,128,SFP_Wapiti,2025-02-15,12:45,3.20,71.9,7.98,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06310,1.19565,88.36,1132.84,1.19638,1.19598,,12:45:00
184,185,SFP_Wapiti,2025-04-15,09:55,4.70,73.2,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10662,1.23314,88.44,1022.68,1.23553,1.23472,,09:55:00
202,203,SFP_Wapiti,2025-04-28,12:40,7.20,54.9,7.89,NaN,"TSS, Nuts, DOC, Alk",NaN,19,1.07563,1.20614,88.39,1150.80,1.21133,1.21038,,12:40:00
219,220,SFP_Wapiti,2025-05-10,11:50,8.00,34.9,7.07,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06595,1.19851,88.46,1148.39,1.23501,1.23088,,11:50:00
238,239,SFP_Wapiti,2025-05-27,13:20,9.30,11.2,7.59,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.10181,1.23364,88.38,1089.84,1.24797,1.24680,,13:20:00
257,258,SFP_Wapiti,2025-06-08,09:30,8.70,7.6,7.56,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.10216,1.22946,87.89,1123.58,1.23689,1.21576,,09:30:00
276,277,SFP_Wapiti,2025-06-22,09:20,6.80,36.2,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,10,1.08256,1.20896,88.73,1155.35,1.21142,1.21049,Rained/snowed late 6/21 through 13:30 on 6/22,09:20:00
296,297,SFP_Wapiti,2025-07-07,11:35,13.20,73.0,7.86,34.57,"TSS, Nuts, DOC, Alk",NaN,31,1.09438,1.22157,88.45,1123.00,1.22559,1.22385,Large rainstorm 7/4,11:35:00
315,316,SFP_Wapiti,2025-07-21,09:35,10.85,54.0,8.01,NaN,"TSS, Nuts, DOC, Alk",17.0,13,1.06473,1.19374,88.74,1159.68,1.19508,1.19452,used old YSI probe for temp and us,09:35:00
334,335,SFP_Wapiti,2025-08-01,10:25,11.69,60.0,8.11,63.72,"TSS, Nuts, DOC, Alk",16.0,20,1.06300,1.19300,88.46,1144.32,1.20500,1.19600,rainstorm night of 7/31 before sampling,10:25:00
353,354,SFP_Wapiti,2025-08-14,14:50,16.93,56.0,7.23,71.61,"TSS, Nuts, DOC, Alk",17.0,28,1.10700,1.24000,89.13,1140.71,1.24200,1.24200,,14:50:00
359,360,SFP_Wapiti,2025-08-27,14:35,14.50,60.0,7.08,70.89,"TSS, Nuts, DOC, Alk",11.0,11,1.08630,1.21800,58.19,576.71,1.27950,1.27170,non-regular sampling after rain. 500ml bottle ...,14:35:00
386,387,SFP_Wapiti,2025-08-29,11:15,11.34,66.0,6.64,68.09,"TSS, Nuts, DOC, Alk",18.0,29,1.11710,1.25100,87.84,1148.58,1.27890,1.27520,,11:15:00
393,394,SFP_Wapiti,2025-09-12,12:00,10.01,72.0,7.14,72.43,"TSS, Nuts, DOC, Alk",7.0,20,1.06130,1.19400,104.97,1138.68,1.19710,1.19640,,12:00:00
416,417,SFP_Wapiti,2025-09-26,15:25,13.00,75.0,7.23,69.31,"TSS, Nuts, DOC, Alk",12.0,1,1.08460,1.21750,87.88,1119.34,1.22070,1.22020,,15:25:00
451,452,SFP_Wapiti,2025-10-04,11:25,9.46,68.0,7.40,69.70,TSS,13.0,18,1.11170,1.24450,88.35,1106.54,1.25370,1.25240,non-regular sampling after 10/03 rain.,11:25:00
456,457,SFP_Wapiti,2025-10-10,12:20,9.15,73.0,8.09,78.54,"TSS, Nuts, DOC, Alk",5.0,FC13,1.06950,1.20200,88.38,1068.99,1.20480,1.20480,,12:20:00
475,476,SFP_Wapiti,2025-12-04,09:50,1.53,73.0,7.38,69.94,"TSS, Nuts, DOC, Alk",8.0,9,1.06340,1.19730,88.54,1121.15,1.20100,1.20010,,09:50:00
515,516,SFP_Wapiti,2026-04-11,13:40,6.80,52.1,7.42,55.49,"TSS, Nuts, DOC, Alk",3.0,FC20,1.11770,1.25070,88.19,1113.59,1.31840,1.31210,,13:40:00
534,535,SFP_Wapiti,2026-05-11,13:40,9.20,34.5,7.00,36.33,"TSS, Nuts, DOC, Alk",6.0,FC10,1.10700,1.23970,87.45,1142.85,1.28480,1.28100,,13:40:00
548,549,SFP_Wapiti,2026-06-13,06:45,7.70,39.8,9.29,41.75,"TSS, Nuts, DOC, Alk",12.0,1,1.07640,1.20940,87.87,1157.55,1.21490,1.21390,lab ec constant 0.917/cm,06:45:00
565,566,SFP_Wapiti,2026-07-10,08:10,10.10,41.9,7.48,51.34,"TSS, Nuts, DOC, Alk",12.0,RC15,1.10230,1.23540,87.88,1090.31,1.23790,1.23640,lab ec constant 0.947/cm,08:10:00
582,583,SFP_Wapiti,2026-07-31,08:50,11.40,46.1,6.85,66.04,"TSS, Nuts, Alk",15.0,HZ,1.07000,1.18740,87.95,1124.17,1.34740,1.34120,non-regular sampling following 07/22 debris fl...,08:50:00
599,600,SFP_Wapiti,2026-08-06,07:50,10.20,66.1,7.44,70.10,"TSS, Nuts, Alk",7.0,25,1.09840,1.22480,89.01,1074.28,1.30170,1.30020,duplicate TSS bottle labled site 7. lab EC cel...,07:50:00

--- Data for Site: SFP_Wolf_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
11,12,SFP_Wolf_Cr,2024-10-12,14:45,15.40,84.2,8.22,NaN,"TSS, Nuts, DOC,Alk",NaN,18,1.11100,1.24300,88.230,1153.16,1.24400,1.243000,,14:45:00
24,25,SFP_Wolf_Cr,2024-10-19,12:40,6.80,91.2,8.15,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06300,1.19300,101.200,1140.83,1.19500,1.191000,"Glass vial broke, sample gone",12:40:00
41,42,SFP_Wolf_Cr,2024-11-03,14:40,5.40,86.5,8.08,NaN,"TSS, Nuts, DOC, Alk",NaN,35,1.10100,1.23000,88.710,1136.85,1.23560,1.232540,,14:40:00
60,61,SFP_Wolf_Cr,2024-11-09,11:50,NaN,93.3,7.99,NaN,"TSS, Nuts, DOC, Alk",NaN,54,1.07900,1.20400,88.750,1143.00,1.20588,1.205110,,11:50:00
77,78,SFP_Wolf_Cr,2024-11-24,13:14,NaN,88.4,7.86,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06125,1.18578,88.330,1126.42,1.18904,1.187840,,13:14:00
92,93,SFP_Wolf_Cr,2025-01-17,15:34,1.30,84.5,7.47,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08231,1.21231,88.070,920.59,1.21761,1.216580,Lab(omega) EC = 104.4 @7.6C,15:34:00
107,108,SFP_Wolf_Cr,2025-01-30,13:05,0.60,96.4,7.74,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07592,1.20942,88.490,1162.20,1.23606,1.232780,Lab(metrohm) EC = 94.81 @7.8C,13:05:00
122,123,SFP_Wolf_Cr,2025-02-15,17:10,3.20,84.9,7.94,NaN,"TSS, Nuts, DOC, Alk",NaN,13,1.06451,1.19522,88.480,1145.03,1.20021,1.198570,,17:10:00
138,139,SFP_Wolf_Cr,2025-03-02,17:30,5.20,90.7,7.48,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10414,1.23144,88.360,1146.14,1.24064,1.238330,,17:30:00
150,151,SFP_Wolf_Cr,2025-03-19,14:45,5.20,88.4,7.68,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11103,1.23731,87.800,1134.36,1.24189,1.240650,,14:45:00
162,163,SFP_Wolf_Cr,2025-03-30,16:05,7.50,82.4,7.67,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06213,1.18783,87.630,1134.69,1.20102,1.198990,,16:05:00
175,176,SFP_Wolf_Cr,2025-04-15,13:00,6.90,71.9,7.19,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08336,1.20979,88.380,1123.55,1.23004,1.226030,pine needle,13:00:00
193,194,SFP_Wolf_Cr,2025-04-28,13:50,8.20,57.5,7.87,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06344,1.19517,87.470,1136.03,1.24947,1.246210,,13:50:00
211,212,SFP_Wolf_Cr,2025-05-10,13:00,8.40,42.7,7.24,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06182,1.19346,88.490,1148.18,1.25481,1.247480,,13:00:00
230,231,SFP_Wolf_Cr,2025-05-27,14:55,10.60,30.1,7.44,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06438,1.19591,88.470,1134.29,1.23299,1.230820,,14:55:00
249,250,SFP_Wolf_Cr,2025-06-08,11:05,9.40,17.1,7.52,NaN,"TSS, Nuts, DOC, Alk",NaN,18,1.11139,1.23829,88.330,1058.05,1.24964,1.247930,,11:05:00
268,269,SFP_Wolf_Cr,2025-06-22,10:35,7.40,44.8,7.46,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07664,1.26318,88.580,1142.44,1.20704,1.206011,Rained/snowed late 6/21 through 13:30 on 6/22,10:35:00
288,289,SFP_Wolf_Cr,2025-07-07,12:45,14.20,96.1,7.53,43.27,"TSS, Nuts, DOC, Alk",NaN,17,1.09196,1.21837,88.580,1136.70,1.23367,1.231290,Large rainstorm 7/4,12:45:00
307,308,SFP_Wolf_Cr,2025-07-21,11:35,12.36,68.0,7.53,NaN,"TSS, Nuts, DOC, Alk",16.0,25,1.09850,1.22471,88.480,1098.77,1.22818,1.226850,used old YSI probe for temp and us,11:35:00
326,327,SFP_Wolf_Cr,2025-08-01,11:25,12.17,73.0,8.08,74.92,"TSS, Nuts, DOC, Alk",14.0,22,1.11100,1.24300,88.510,1140.91,1.24400,1.247000,rainstorm night of 7/31 before sampling,11:25:00
345,346,SFP_Wolf_Cr,2025-08-14,16:40,18.03,62.0,6.56,83.96,"TSS, Nuts, DOC, Alk",1.0,31,1.09400,1.22800,88.670,1151.42,1.23300,1.231300,,16:40:00
364,365,SFP_Wolf_Cr,2025-08-27,15:30,14.20,74.0,6.95,111.20,"TSS, Nuts, DOC, Alk",1.0,45,1.10070,1.23220,57.091,594.95,1.37440,1.357600,non-regular sampling after rain. 500ml bottle ...,15:30:00
378,379,SFP_Wolf_Cr,2025-08-29,12:45,13.14,79.0,6.90,79.97,"TSS, Nuts, DOC, Alk",12.0,2,1.09810,1.23100,87.880,1104.77,1.29150,1.282800,,12:45:00
400,401,SFP_Wolf_Cr,2025-09-12,13:20,11.66,85.0,6.72,84.45,"TSS, Nuts, DOC, Alk",12.0,9,1.06350,1.19720,101.560,1081.57,1.20260,1.201100,,13:20:00
423,424,SFP_Wolf_Cr,2025-09-26,16:45,13.35,87.0,6.68,83.95,"TSS, Nuts, DOC, Alk",13.0,23,1.10240,1.23490,88.360,1092.88,1.23840,1.237800,,16:45:00
445,446,SFP_Wolf_Cr,2025-10-04,10:35,8.71,82.0,8.22,84.34,TSS,18.0,4,1.10530,1.23810,87.830,1118.06,1.28630,1.280800,non-regular sampling after 10/03 rain.,10:35:00
463,464,SFP_Wolf_Cr,2025-10-10,13:45,10.55,86.0,8.11,86.46,"TSS, Nuts, DOC, Alk",16.0,49,1.08740,1.22150,88.460,1114.79,1.23370,1.232900,,13:45:00
482,483,SFP_Wolf_Cr,2025-12-04,12:10,0.79,87.0,7.32,79.20,"TSS, Nuts, DOC, Alk",18.0,11,1.08540,1.21690,87.840,1132.30,1.22180,1.221300,,12:10:00
495,496,SFP_Wolf_Cr,2026-02-07,14:30,NaN,84.0,6.37,82.66,"TSS, Nuts, DOC, Alk",3.0,31,1.09420,1.22750,88.180,1113.90,1.23090,1.229700,,14:30:00
505,506,SFP_Wolf_Cr,2026-03-08,14:15,6.50,78.0,7.07,94.05,"TSS, Nuts, DOC, Alk",14.0,10,1.08280,1.21570,88.500,1088.90,1.21670,1.216200,,14:15:00
522,523,SFP_Wolf_Cr,2026-04-11,15:15,7.70,61.1,7.00,68.29,"TSS, Nuts, DOC, Alk",19.0,23,1.10240,1.23560,87.460,1153.40,1.38030,1.363500,,15:15:00
541,542,SFP_Wolf_Cr,2026-05-11,15:10,11.00,44.8,6.75,46.64,"TSS, Nuts, DOC, Alk",9.0,53,1.08540,1.21790,88.330,1159.34,1.33280,1.324700,,15:10:00
555,556,SFP_Wolf_Cr,2026-06-13,08:35,7.60,52.0,7.29,55.46,"TSS, Nuts, DOC, Alk",6.0,49,1.08840,1.21950,87.450,1112.98,1.22710,1.225700,,08:35:00
572,573,SFP_Wolf_Cr,2026-07-10,09:40,10.70,59.7,7.45,64.87,"TSS, Nuts, DOC, Alk",20.0,FC18,1.05280,1.18510,88.290,1140.23,1.18900,1.188300,,09:40:00
589,590,SFP_Wolf_Cr,2026-07-31,10:40,12.50,76.2,6.70,80.94,"TSS, Nuts, DOC, Alk",6.0,6,1.10450,1.22210,87.430,1126.54,1.66010,1.652000,Whatman GF/F 934-AH used for DOC/TSS,10:40:00
606,607,SFP_Wolf_Cr,2026-08-06,09:20,10.10,80.1,7.04,85.49,"TSS, Nuts, Alk",1.0,32,1.07910,1.20560,88.340,1136.23,1.38600,1.382900,no duplicate TSS,09:20:00

--- Data for Site: SH_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
1,2,SH_Cr,2024-10-11,11:34,NaN,NaN,7.91,NaN,"TSS, Nuts",NaN,26,1.08300,1.21400,88.540,1133.87,1.23400,NaN,,11:34:00
15,16,SH_Cr,2024-10-12,16:30,13.00,98.3,8.05,NaN,"TSS, Nuts, DOC, Alk",NaN,23,1.11030,1.23700,87.630,1147.85,1.24000,1.23791,,16:30:00
16,17,SH_Cr,2024-10-13,16:00,13.30,100.2,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,24,1.06500,1.19900,88.810,1141.80,1.21800,NaN,"Glass vial broke, sample gone",16:00:00
28,29,SH_Cr,2024-10-19,14:10,8.10,89.5,7.90,NaN,"TSS, Nuts, DOC, Alk",NaN,12,1.06700,1.19600,101.430,1001.98,1.21400,1.21100,"Glass vial broke, sample gone",14:10:00
35,36,SH_Cr,2024-11-03,11:10,1.70,82.1,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,29,1.11700,1.24300,88.790,1120.02,1.25460,1.24751,,11:10:00
64,65,SH_Cr,2024-11-09,12:30,NaN,80.5,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,57,1.07400,1.20400,88.590,1067.57,1.20766,1.20682,,12:30:00
81,82,SH_Cr,2024-11-24,15:11,NaN,79.4,8.10,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06299,1.18718,887.590,1126.84,1.23012,1.22715,,15:11:00
96,97,SH_Cr,2025-01-17,13:41,1.30,65.0,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10626,1.23723,88.230,1053.98,1.41141,1.40853,"Lab(metrohm) EC = 81.43 @8.6C, **used both met...",13:41:00
111,112,SH_Cr,2025-01-30,11:22,0.30,20.9,7.96,NaN,"TSS, Nuts, DOC, Alk",NaN,5,1.08864,1.21926,88.220,1124.90,1.23974,1.23806,"Had to break through ice for sample,Lab(metroh...",11:22:00
126,127,SH_Cr,2025-02-15,14:20,1.50,67.9,NaN,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10091,1.23171,88.110,737.44,1.25185,1.25060,"1L Bottle not all the way full, had to break t...",14:20:00
142,143,SH_Cr,2025-03-02,15:00,5.80,54.0,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09429,1.22181,88.430,1140.23,1.43265,1.42028,,15:00:00
154,155,SH_Cr,2025-03-19,12:55,0.60,60.2,7.69,NaN,"TSS, Nuts, DOC, Alk",NaN,58,1.08315,1.20921,88.230,1133.60,1.22533,1.22314,,12:55:00
166,167,SH_Cr,2025-03-30,14:10,6.00,51.1,7.42,NaN,"TSS, Nuts, DOC, Alk",NaN,4,1.10439,1.23196,88.380,1109.36,1.25098,1.23938,,14:10:00
179,180,SH_Cr,2025-04-15,10:55,4.60,43.5,7.79,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10390,1.23156,87.480,1133.55,1.38447,1.37621,,10:55:00
197,198,SH_Cr,2025-04-28,12:50,8.50,40.5,7.85,NaN,"TSS, Nuts, DOC, Alk",NaN,51,1.06224,1.19431,87.450,1142.47,1.57037,1.55268,,12:50:00
215,216,SH_Cr,2025-05-10,12:15,11.20,35.5,7.29,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06334,1.19487,88.720,1162.66,2.18516,2.16329,tss had gravel sized rock,12:15:00
234,235,SH_Cr,2025-05-27,11:20,10.00,37.9,7.38,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.10418,1.23593,88.670,1115.32,1.23861,1.23830,,11:20:00
253,254,SH_Cr,2025-06-08,09:50,10.20,12.3,7.72,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08291,1.21023,89.590,1058.81,1.21349,1.21217,,09:50:00
272,273,SH_Cr,2025-06-22,09:40,5.90,49.1,7.55,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08601,1.21373,88.240,1151.27,1.26332,1.25945,Rained/snowed late 6/21 through 13:30 on 6/22,09:40:00
292,293,SH_Cr,2025-07-07,11:55,15.10,96.4,7.63,44.88,"TSS, Nuts, DOC, Alk",NaN,1,1.08515,1.21112,88.500,1126.00,1.57721,1.56832,Large rainstorm 7/4,11:55:00
311,312,SH_Cr,2025-07-21,10:15,11.28,57.0,7.63,NaN,"TSS, Nuts, DOC, Alk",19.0,50,1.08789,1.21641,89.620,1093.83,1.23924,1.23677,used old YSI probe for temp and us,10:15:00
330,331,SH_Cr,2025-08-01,10:45,12.56,58.0,8.12,62.18,"TSS, Nuts, DOC, Alk",11.0,15,1.08500,1.21500,88.070,1072.33,1.25500,1.25200,rainstorm night of 7/31 before sampling,10:45:00
349,350,SH_Cr,2025-08-14,12:45,15.45,49.0,6.99,66.03,"TSS, Nuts, DOC, Alk",15.0,43,1.09700,1.22800,88.930,1104.76,1.24300,1.23970,,12:45:00
360,361,SH_Cr,2025-08-27,14:50,15.60,54.0,6.92,67.08,"TSS, Nuts, DOC, Alk",12.0,49,1.08850,1.22280,57.887,573.18,1.23980,1.23610,non-regular sampling after rain. 500ml bottle ...,14:50:00
382,383,SH_Cr,2025-08-29,11:35,12.95,61.0,6.94,61.85,"TSS, Nuts, DOC, Alk",17.0,27,1.10060,1.23350,88.730,1152.67,1.24180,1.23980,,11:35:00
395,396,SH_Cr,2025-09-12,12:20,10.64,60.0,6.61,60.84,"TSS, Nuts, DOC, Alk",3.0,28,1.10770,1.23940,103.180,1089.71,1.24600,1.24440,,12:20:00
418,419,SH_Cr,2025-09-26,15:45,14.55,61.0,6.60,60.72,"TSS, Nuts, DOC, Alk",20.0,6,1.10350,1.23710,88.280,1048.12,1.24430,1.24250,,15:45:00
448,449,SH_Cr,2025-10-04,11:05,8.55,62.0,8.03,65.05,TSS,21.0,39,1.10190,1.23470,88.830,1088.59,1.32900,1.32310,non-regular sampling after 10/03 rain.,11:05:00
458,459,SH_Cr,2025-10-10,12:45,10.48,61.0,7.79,60.22,"TSS, Nuts, DOC, Alk",11.0,FC12,1.08780,1.22050,88.060,1096.30,1.26050,1.25720,,12:45:00
477,478,SH_Cr,2025-12-04,10:25,-0.34,58.0,7.70,56.91,"TSS, Nuts, DOC, Alk",2.0,FC10,1.10680,1.23870,88.850,1077.43,1.24260,1.24190,,10:25:00
491,492,SH_Cr,2026-02-07,12:20,NaN,54.0,6.37,55.13,"TSS, Nuts, DOC, Alk",6.0,FC13,1.06940,1.20090,87.440,1113.19,1.21250,1.21130,,12:20:00
501,502,SH_Cr,2026-03-08,11:50,4.40,54.0,6.94,78.22,"TSS, Nuts, DOC, Alk",16.0,FC18,1.05330,1.18670,88.450,1089.31,1.18890,1.18800,Field temp and field EC from CRX800. Notebook ...,11:50:00
517,518,SH_Cr,2026-04-11,14:05,6.90,51.7,7.30,53.22,"TSS, Nuts, DOC, Alk",7.0,6,1.10380,1.23560,88.990,1133.58,1.29620,1.28900,,14:05:00
536,537,SH_Cr,2026-05-11,14:05,13.90,39.3,6.91,45.16,"TSS, Nuts, DOC, Alk",8.0,5,1.08900,1.22190,88.530,1074.72,1.49340,1.48060,,14:05:00
550,551,SH_Cr,2026-06-13,07:10,6.60,50.7,6.73,53.83,"TSS, Nuts, DOC, Alk",10.0,38,1.09850,1.23060,87.560,1118.04,1.23420,1.23290,,07:10:00
567,568,SH_Cr,2026-07-10,08:35,10.90,55.3,7.26,60.33,"TSS, Nuts, DOC, Alk",8.0,41,1.06220,1.19520,88.540,1073.92,1.19850,1.19750,,08:35:00
584,585,SH_Cr,2026-07-31,09:40,12.50,54.9,6.92,60.65,"TSS, Nuts, DOC, Alk",17.0,FC14,1.08190,1.19950,88.330,1081.08,1.20130,1.20050,Whatman GF/F 934-AH used for DOC/TSS,09:40:00
601,602,SH_Cr,2026-08-06,08:20,10.60,58.1,7.35,61.72,"TSS, Nuts, Alk",13.0,FC17,1.08960,1.21620,88.730,1100.74,1.21740,1.21700,duplicate TSS bottle labled site 13,08:20:00

--- Data for Site: Wapiti_Cr ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
66,67,Wapiti_Cr,2024-11-09,16:00,NaN,87.5,7.92,NaN,"TSS, Nuts, DOC, Alk",NaN,59,1.09200,1.21300,88.08,1034.73,1.21914,1.21791,,16:00:00
185,186,Wapiti_Cr,2025-04-15,10:20,3.10,62.3,7.70,NaN,"TSS, Nuts, DOC, Alk",NaN,9,1.06343,1.18968,88.70,1145.44,1.19419,1.19271,,10:20:00
203,204,Wapiti_Cr,2025-04-28,12:20,5.40,58.8,7.84,NaN,"TSS, Nuts, DOC, Alk",NaN,11,1.08554,1.21706,87.63,1101.13,1.22485,1.22263,,12:20:00
220,221,Wapiti_Cr,2025-05-10,10:05,5.70,56.8,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10724,1.24071,89.64,1149.96,1.26535,1.25607,,10:05:00
239,240,Wapiti_Cr,2025-05-27,12:50,7.80,49.5,7.37,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08535,1.21751,88.51,1131.93,1.23264,1.22865,,12:50:00
258,259,Wapiti_Cr,2025-06-08,08:50,6.40,10.8,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08794,1.21544,88.59,1149.98,1.22131,1.21936,,08:50:00
277,278,Wapiti_Cr,2025-06-22,08:50,5.10,73.7,7.43,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08527,1.21230,87.95,1153.59,1.21647,1.21513,Rained/snowed late 6/21 through 13:30 on 6/22,08:50:00
297,298,Wapiti_Cr,2025-07-07,11:15,8.60,130.5,7.79,61.19,"TSS, Nuts, DOC, Alk",NaN,15,1.08534,1.21122,88.25,1020.30,1.21546,1.21391,Large rainstorm 7/4,11:15:00
316,317,Wapiti_Cr,2025-07-21,09:04,7.08,76.0,7.39,NaN,"TSS, Nuts, DOC, Alk",15.0,14,1.07708,1.20592,89.06,1000.35,1.21112,1.20934,used old YSI probe for temp and us,09:04:00
335,336,Wapiti_Cr,2025-08-01,10:00,7.69,79.0,7.98,83.49,"TSS, Nuts, DOC, Alk",19.0,5,1.08900,1.22100,89.61,1061.07,1.22200,1.22100,rainstorm night of 7/31 before sampling,10:00:00
354,355,Wapiti_Cr,2025-08-14,14:30,10.00,54.0,6.91,88.38,"TSS, Nuts, DOC, Alk",10.0,30,1.09600,1.23100,88.65,1088.75,1.23500,1.23250,,14:30:00
387,388,Wapiti_Cr,2025-08-29,18:28,9.86,82.0,6.92,82.51,"TSS, Nuts, DOC, Alk",9.0,39,1.10090,1.23440,88.35,1157.55,1.24110,1.23710,,18:28:00
392,393,Wapiti_Cr,2025-09-12,11:40,6.68,81.0,6.40,84.08,"TSS, Nuts, DOC, Alk",4.0,11,1.08510,1.21600,102.53,1032.60,1.22170,1.21830,,11:40:00
452,453,Wapiti_Cr,2025-10-04,16:40,7.53,67.0,7.91,83.07,TSS,19.0,13,1.06490,1.19790,87.47,1114.14,1.21120,1.20890,non-regular sampling after 10/03 rain.,16:40:00

--- Data for Site: Warm_Sp ---

,sample_num,site,date,time,field_temp,field_EC,lab_pH,lab_EC,bottles_collected,bottle_site_num,tin_num,tin_weight,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,notes,time_cleaned
0,1,Warm_Sp,2024-10-11,15:00,NaN,NaN,8.39,NaN,"TSS, Nuts",NaN,19,1.07500,1.20800,88.570,1135.00,1.20800,1.20500,,15:00:00
8,9,Warm_Sp,2024-10-12,13:15,13.00,114.0,NaN,NaN,DOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,13:15:00
21,22,Warm_Sp,2024-10-19,11:40,8.20,115.2,8.27,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08600,1.21700,100.990,1135.94,1.21400,1.21200,"Glass vial broke, sample gone",11:40:00
46,47,Warm_Sp,2024-11-04,13:40,8.20,109.4,8.14,NaN,"TSS, Nuts, DOC, Alk",NaN,39,1.10100,1.22900,87.870,1120.70,1.23600,1.23234,,13:40:00
54,55,Warm_Sp,2024-11-09,10:35,NaN,116.1,8.02,NaN,"TSS, Nuts, DOC, Alk",NaN,48,1.09800,1.22200,88.590,1122.91,1.22274,1.22237,,10:35:00
71,72,Warm_Sp,2024-11-24,11:07,NaN,112.4,8.01,NaN,"TSS, Nuts, DOC, Alk",NaN,14,1.07599,1.19937,88.320,1138.31,1.24092,1.23873,,11:07:00
86,87,Warm_Sp,2025-01-17,10:35,5.30,107.7,7.44,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10076,1.23195,87.440,1123.14,1.23693,1.23622,Lab(omega) EC = 133.9 @8.0C,10:35:00
101,102,Warm_Sp,2025-01-30,14:06,6.30,98.7,7.97,NaN,"TSS, Nuts, DOC, Alk",NaN,8,1.10623,1.23845,88.330,1168.10,1.24267,1.24186,Lab(metrohm) EC = 125.7 @6.4C,14:06:00
116,117,Warm_Sp,2025-02-15,15:40,8.40,120.6,7.94,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08724,1.21766,88.710,1123.34,1.22059,1.21977,,15:40:00
132,133,Warm_Sp,2025-03-02,18:30,9.10,114.3,7.51,NaN,"TSS, Nuts, DOC, Alk",NaN,22,1.11082,1.23651,88.400,1094.01,1.26331,1.26164,,18:30:00
147,148,Warm_Sp,2025-03-19,10:55,4.60,115.0,7.58,NaN,"TSS, Nuts, DOC, Alk",NaN,20,1.06415,1.18929,87.630,1101.42,1.19518,1.19413,,10:55:00
159,160,Warm_Sp,2025-03-30,11:30,7.00,103.5,7.57,NaN,"TSS, Nuts, DOC, Alk",NaN,50,1.08731,1.21494,88.330,1089.77,1.43392,1.43092,,11:30:00
172,173,Warm_Sp,2025-04-15,14:25,11.00,86.7,7.68,NaN,"TSS, Nuts, DOC, Alk",NaN,7,1.08255,1.20955,88.500,1102.97,1.27461,1.27259,,14:25:00
190,191,Warm_Sp,2025-04-28,10:30,6.20,71.6,7.81,NaN,"TSS, Nuts, DOC, Alk",NaN,6,1.04190,1.23573,88.230,1131.04,1.37904,1.37575,,10:30:00
208,209,Warm_Sp,2025-05-10,14:20,9.50,52.8,7.13,NaN,"TSS, Nuts, DOC, Alk",NaN,15,1.08478,1.21667,88.400,1162.06,1.57770,1.56572,,14:20:00
227,228,Warm_Sp,2025-05-27,15:30,12.00,40.6,7.25,NaN,"TSS, Nuts, DOC, Alk",NaN,55,1.09473,1.22604,88.360,1112.69,1.31552,1.31479,,15:30:00
246,247,Warm_Sp,2025-06-08,12:20,11.70,7.8,7.62,NaN,"TSS, Nuts, DOC, Alk",NaN,46,1.10142,1.22823,87.690,1140.38,1.23560,1.23275,,12:20:00
265,266,Warm_Sp,2025-06-22,12:40,10.40,80.1,7.35,NaN,"TSS, Nuts, DOC, Alk",NaN,17,1.09208,1.21857,88.380,1142.61,1.21999,1.21943,Rained/snowed late 6/21 through 13:30 on 6/22,12:40:00
284,285,Warm_Sp,2025-07-07,14:15,16.90,153.6,7.35,70.49,"TSS, Nuts, DOC, Alk",NaN,11,1.08594,1.21253,87.650,1155.70,1.21803,1.21697,Large rainstorm 7/4,14:15:00
303,304,Warm_Sp,2025-07-21,13:25,15.03,97.0,7.79,NaN,"TSS, Nuts, DOC, Alk",13.0,9,1.06387,1.19159,88.360,1146.78,1.19519,1.19424,used old YSI probe for temp and us,13:25:00
322,323,Warm_Sp,2025-08-01,14:30,14.44,63.0,8.18,103.30,"TSS, Nuts, DOC, Alk",2.0,2,1.09800,1.22600,88.530,1116.34,1.22600,1.22500,rainstorm night of 7/31 before sampling,14:30:00
341,342,Warm_Sp,2025-08-14,10:45,12.03,79.0,7.11,116.80,"TSS, Nuts, DOC, Alk",7.0,50,1.09200,1.21900,89.540,1121.45,1.22000,1.22060,,10:45:00
366,367,Warm_Sp,2025-08-27,15:55,14.60,90.0,7.03,103.20,"TSS, Nuts, DOC, Alk",18.0,"28,47,20",3.26730,3.66840,58.189,590.95,4.06790,4.03150,non-regular sampling after rain. 500ml bottle ...,15:55:00
375,376,Warm_Sp,2025-08-29,10:10,10.91,102.0,6.79,102.30,"TSS, Nuts, DOC, Alk",5.0,32,1.07900,1.21250,88.390,1147.76,1.29090,1.28250,,10:10:00
405,406,Warm_Sp,2025-09-12,17:25,14.53,103.0,6.53,104.20,"TSS, Nuts, DOC, Alk",17.0,46,1.10050,1.23330,88.730,1157.88,1.24370,1.24100,,17:25:00
428,429,Warm_Sp,2025-09-26,17:25,14.47,110.0,6.57,107.50,"TSS, Nuts, DOC, Alk",9.0,10,1.08210,1.21520,88.360,1108.05,1.22020,1.21890,,17:25:00
442,443,Warm_Sp,2025-10-04,10:05,9.86,103.0,8.31,105.10,TSS,16.0,20,1.06200,1.19500,88.460,1116.93,1.25880,1.25490,non-regular sampling after 10/03 rain.,10:05:00
471,472,Warm_Sp,2025-10-10,16:20,13.55,109.0,7.67,109.20,"TSS, Nuts, DOC, Alk",4.0,31,1.09390,1.22650,87.910,1112.58,1.24330,1.24190,,16:20:00
484,485,Warm_Sp,2025-12-04,13:55,5.27,115.0,7.18,102.70,"TSS, Nuts, DOC, Alk",6.0,48,1.09900,1.23220,87.450,1091.36,1.23960,1.23890,,13:55:00
498,499,Warm_Sp,2026-02-07,15:35,NaN,106.0,6.33,103.50,"TSS, Nuts, DOC, Alk",12.0,58,1.08300,1.21720,87.870,1140.60,1.22350,1.22320,,15:35:00
508,509,Warm_Sp,2026-03-08,15:45,10.20,104.0,7.10,119.40,"TSS, Nuts, DOC, Alk",19.0,14,1.07710,1.20930,87.460,1124.12,1.21260,1.21190,,15:45:00
524,525,Warm_Sp,2026-04-11,16:00,7.90,74.8,6.99,78.61,"TSS, Nuts, DOC, Alk",14.0,1,1.08480,1.21700,88.500,1138.09,1.43660,1.42720,,16:00:00
543,544,Warm_Sp,2026-05-11,15:50,11.70,54.4,7.79,57.30,"TSS, Nuts, DOC, Alk",15.0,48,1.09910,1.23170,87.970,1139.53,1.52400,1.51760,,15:50:00
560,561,Warm_Sp,2026-06-13,10:30,8.80,71.5,6.75,87.97,"TSS, Nuts, DOC, Alk",2.0,FC13,1.06980,1.20180,89.610,1139.92,1.20570,1.20530,,10:30:00
577,578,Warm_Sp,2026-07-10,11:35,12.60,87.4,7.36,103.70,"TSS, Nuts, DOC, Alk",9.0,10,1.08230,1.21500,88.360,1142.65,1.22100,1.22020,,11:35:00
594,595,Warm_Sp,2026-07-31,12:20,14.80,105.0,6.74,109.00,"TSS, Nuts, Alk",16.0,39,1.10170,1.21840,88.440,1098.37,1.21980,1.21960,Whatman GF/F 934-AH used for TSS,12:20:00
611,612,Warm_Sp,2026-08-06,11:00,12.00,107.3,7.53,114.90,"TSS, Nuts, Alk",3.0,31,1.09470,1.22080,88.210,1139.28,1.22170,1.22160,duplicate TSS bottle labeled site 12,11:00:00

## TSS data descriptions

In [21]:
for site, group in tss_df.groupby("site"):
    print(f"--- TSS Data for Site: {site} ---")
    display(group)
    print("\n")

--- TSS Data for Site: Avalanche_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
30,31,2024-10-19,Avalanche_Cr,4,1.23000,101.45,1110.23,1.24000,1.23700,10.00,1.00878,10.00,3.00
37,38,2024-11-03,Avalanche_Cr,31,1.21700,87.64,1123.76,1.26950,1.26391,52.50,1.03612,52.50,5.59
57,58,2024-11-09,Avalanche_Cr,51,1.18500,88.77,1125.45,1.18642,1.18574,1.42,1.03668,1.42,0.68
74,75,2024-11-24,Avalanche_Cr,16,1.21856,88.49,1124.38,1.22548,1.22249,6.92,1.03589,6.92,2.99
89,90,2025-01-17,Avalanche_Cr,51,1.19312,88.34,1063.49,1.19561,1.19490,2.49,0.97515,2.49,0.71
104,105,2025-01-30,Avalanche_Cr,22,1.24091,88.43,644.80,1.24326,1.24241,2.35,0.55637,2.35,0.85
119,120,NaT,Avalanche_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,136,2025-03-02,Avalanche_Cr,5,1.21565,88.71,1142.03,1.27106,1.26811,55.41,1.05332,55.41,2.95
182,183,2025-04-15,Avalanche_Cr,25,1.22438,88.55,1152.61,1.43208,1.33420,207.70,1.06406,207.70,97.88
200,201,2025-04-28,Avalanche_Cr,8,1.23833,88.46,1143.78,1.76401,1.74821,525.68,1.05532,525.68,15.80
217,218,2025-05-10,Avalanche_Cr,55,1.22702,89.00,1130.46,1.60014,1.56489,373.12,1.04146,373.12,35.25
236,237,2025-05-27,Avalanche_Cr,4,1.23638,89.01,1075.05,1.26565,1.26253,29.27,0.98604,29.27,3.12
255,256,2025-06-08,Avalanche_Cr,8,1.23303,88.50,1164.14,1.23886,1.23728,5.83,1.07564,5.83,1.58
274,275,2025-06-22,Avalanche_Cr,19,1.20167,89.01,1147.82,1.20332,1.20274,1.65,1.05881,1.65,0.58
294,295,2025-07-07,Avalanche_Cr,51,1.19076,87.84,1101.70,1.22199,1.21754,31.23,1.01386,31.23,4.45
313,314,2025-07-21,Avalanche_Cr,19,1.20409,87.47,1117.18,1.21155,1.20988,7.46,1.02971,7.46,1.67
332,333,2025-08-01,Avalanche_Cr,1,1.21600,88.99,1131.08,1.23400,1.22400,18.00,1.04209,18.00,10.00
351,352,2025-08-14,Avalanche_Cr,27,1.23400,88.21,1111.92,1.23500,1.23700,1.00,1.02371,1.00,-2.00
384,385,2025-08-29,Avalanche_Cr,12,1.19940,88.57,1137.31,1.41410,1.27230,214.70,1.04874,214.70,141.80
402,403,2025-09-12,Avalanche_Cr,57,1.21170,88.38,NaN,1.26120,1.25870,49.50,NaN,49.50,2.50
425,426,2025-09-26,Avalanche_Cr,29,1.24920,88.50,1136.80,1.25610,1.25460,6.90,1.04830,6.90,1.50
468,469,2025-10-10,Avalanche_Cr,28,1.24140,87.57,1119.22,1.31370,1.31250,72.30,1.03165,72.30,1.20
514,515,2026-04-11,Avalanche_Cr,FC14,1.21430,87.56,1100.03,1.78470,1.75270,570.40,1.01247,570.40,32.00
532,533,2026-05-11,Avalanche_Cr,68,1.22860,89.61,1096.01,1.50870,1.49740,280.10,1.00640,280.10,11.30
557,558,2026-06-13,Avalanche_Cr,25,1.23170,88.72,1136.42,1.23310,1.23230,1.40,1.04770,1.40,0.80
574,575,2026-07-10,Avalanche_Cr,4,1.21420,87.91,1117.66,1.21580,1.21510,1.60,1.02975,1.60,0.70
591,592,2026-07-31,Avalanche_Cr,16,1.21360,88.27,1140.21,1.21390,1.21370,0.30,1.05194,0.30,0.20
608,609,2026-08-06,Avalanche_Cr,4,1.20960,87.90,1104.40,1.21060,1.20990,1.00,1.01650,1.00,0.70

--- TSS Data for Site: BJ_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
3,4,2024-10-11,BJ_Cr,21,1.213000,87.430,1080.30,1.23800,NaN,25.000,0.992870,25.000,NaN
7,8,2024-10-12,BJ_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,2024-10-19,BJ_Cr,3,1.230000,101.060,1082.96,1.24600,1.23700,16.000,0.981900,16.000,9.00
48,49,2024-11-04,BJ_Cr,41,1.186000,88.580,1075.83,1.19220,1.18744,6.200,0.987250,6.200,4.76
52,53,2024-11-09,BJ_Cr,46,1.223000,88.560,1119.97,1.22534,1.22395,2.340,1.031410,2.340,1.39
69,70,2024-11-24,BJ_Cr,5,1.211970,88.250,1130.70,1.21413,1.21233,2.160,1.042450,2.160,1.80
84,85,2025-01-17,BJ_Cr,9,1.189689,87.460,1034.02,1.18888,1.18744,-0.809,0.946560,-0.809,1.44
99,100,2025-01-30,BJ_Cr,20,1.192530,88.370,511.10,1.19471,1.19341,2.180,0.422730,2.180,1.30
114,115,2025-02-15,BJ_Cr,51,1.193690,88.420,1092.78,1.19824,1.19601,4.550,1.004360,4.550,2.23
130,131,2025-03-02,BJ_Cr,25,1.223710,88.380,1107.88,1.22524,1.22442,1.530,1.019500,1.530,0.82
145,146,2025-03-19,BJ_Cr,14,1.203910,89.200,1065.29,1.20717,1.20549,3.260,0.976090,3.260,1.68
157,158,2025-03-30,BJ_Cr,60,1.220860,88.700,1046.68,1.22345,1.22242,2.590,0.957980,2.590,1.03
170,171,2025-04-15,BJ_Cr,14,1.203690,87.440,1016.08,1.20812,1.20594,4.430,0.928640,4.430,2.18
188,189,2025-04-28,BJ_Cr,60,1.227110,88.340,1112.23,1.23377,1.23103,6.660,1.023890,6.660,2.74
206,207,2025-05-10,BJ_Cr,60,1.225540,88.380,1141.69,1.24912,1.24645,23.580,1.053310,23.580,2.67
225,226,2025-05-27,BJ_Cr,17,1.224450,88.240,1125.74,1.22968,1.22819,5.230,1.037500,5.230,1.49
244,245,2025-06-08,BJ_Cr,22,1.239550,88.540,1122.57,1.24461,1.24183,5.060,1.034030,5.060,2.78
263,264,2025-06-22,BJ_Cr,6,1.230680,88.200,1116.12,1.23323,1.23172,2.550,1.027920,2.550,1.51
282,283,2025-07-07,BJ_Cr,7,1.209640,88.570,1152.00,1.21334,1.21156,3.700,1.063430,3.700,1.78
301,302,2025-07-21,BJ_Cr,33,1.235810,88.790,1106.94,1.23861,1.23698,2.800,1.018150,2.800,1.63
320,321,2025-08-01,BJ_Cr,12,1.193000,88.380,1090.53,1.20200,1.19300,9.000,1.002150,9.000,9.00
339,340,2025-08-14,BJ_Cr,58,1.212000,88.570,1116.33,1.21900,1.21800,7.000,1.027760,7.000,1.00
368,369,2025-08-27,BJ_Cr,34,1.197600,58.168,591.10,1.19930,1.19680,1.700,0.532932,1.700,2.50
373,374,2025-08-29,BJ_Cr,FC11,1.212800,87.450,1057.64,1.21480,1.21250,2.000,0.970190,2.000,2.30
407,408,2025-09-12,BJ_Cr,49,1.219400,87.450,NaN,1.22220,1.22050,2.800,NaN,2.800,1.70
430,431,2025-09-26,BJ_Cr,36,1.214600,87.840,1103.23,1.21760,1.21600,3.000,1.015390,3.000,1.60
440,441,2025-10-04,BJ_Cr,5,1.221900,88.730,1093.84,1.22360,1.22230,1.700,1.005110,1.700,1.30
473,474,2025-10-10,BJ_Cr,14,1.208300,88.520,1091.57,1.21130,1.20990,3.000,1.003050,3.000,1.40
486,487,2025-12-04,BJ_Cr,53,1.217600,88.390,1083.29,1.21930,1.21730,1.700,0.994900,1.700,2.00
500,501,2026-02-07,BJ_Cr,FC16,1.204200,88.360,1110.25,1.20560,1.20380,1.400,1.021890,1.400,1.80
510,511,2026-03-08,BJ_Cr,2,1.230800,88.390,1117.64,1.23210,1.23060,1.300,1.029250,1.300,1.50
526,527,2026-04-11,BJ_Cr,34,1.197200,88.270,1122.96,1.20010,1.19790,2.900,1.034690,2.900,2.20
545,546,2026-05-11,BJ_Cr,12,1.200000,88.720,1067.11,1.20270,1.20090,2.700,0.978390,2.700,1.80
562,563,2026-06-13,BJ_Cr,8,1.239900,87.890,1102.14,1.24200,1.24000,2.100,1.014250,2.100,2.00
579,580,2026-07-10,BJ_Cr,7,1.200000,87.570,1008.27,1.20140,1.20020,1.400,0.920700,1.400,1.20
596,597,2026-07-31,BJ_Cr,1,1.200800,88.990,1089.76,1.20330,1.20180,2.500,1.000770,2.500,1.50
613,614,2026-08-06,BJ_Cr,FC9,1.216800,88.550,1083.60,1.21820,1.21630,1.400,0.995050,1.400,1.90

--- TSS Data for Site: Bear_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
222,223,2025-05-10,Bear_Cr,"11,51",2.41332,88.24,1150.55,3.30473,3.27641,891.41,1.06231,891.41,28.32
241,242,2025-05-27,Bear_Cr,22,1.24172,88.45,1074.04,1.36588,1.36237,124.16,0.98559,124.16,3.51
260,261,2025-06-08,Bear_Cr,32,1.20683,87.84,1134.04,1.22348,1.22207,16.65,1.04620,16.65,1.41
279,280,2025-06-22,Bear_Cr,12,1.19338,88.46,1128.62,1.19844,1.19726,5.06,1.04016,5.06,1.18
298,299,2025-07-07,Bear_Cr,6,1.23115,88.52,1058.80,1.24066,1.23929,9.51,0.97028,9.51,1.37
317,318,2025-07-21,Bear_Cr,58,1.21146,87.88,1141.35,1.21582,1.21449,4.36,1.05347,4.36,1.33
336,337,2025-08-01,Bear_Cr,9,1.19700,87.85,1081.82,1.21100,1.19900,14.00,0.99397,14.00,12.00
355,356,2025-08-14,Bear_Cr,37,1.21400,87.93,1126.56,1.21500,1.21460,1.00,1.03863,1.00,0.40
388,389,2025-08-29,Bear_Cr,5,1.22210,89.61,1145.66,1.22320,1.22230,1.10,1.05605,1.10,0.90
394,395,2025-09-12,Bear_Cr,40,1.23740,101.89,1152.41,1.23960,1.23800,2.20,1.05052,2.20,1.60
417,418,2025-09-26,Bear_Cr,17,1.22540,87.46,1133.43,1.22730,1.22620,1.90,1.04597,1.90,1.10
450,451,2025-10-04,Bear_Cr,34,1.19820,87.73,1099.97,1.20060,1.19950,2.40,1.01224,2.40,1.10
457,458,2025-10-10,Bear_Cr,FC4,1.19150,88.34,1033.75,1.19340,1.19340,1.90,0.94541,1.90,0.00
476,477,2025-12-04,Bear_Cr,46,1.23440,87.57,1023.01,1.23670,1.23580,2.30,0.93544,2.30,0.90
516,517,2026-04-11,Bear_Cr,16,1.22810,89.58,1146.36,1.25860,1.25590,30.50,1.05678,30.50,2.70
535,536,2026-05-11,Bear_Cr,18,1.24360,88.19,1129.71,1.33470,1.32930,91.10,1.04152,91.10,5.40
549,550,2026-06-13,Bear_Cr,HZ,1.20270,88.33,1142.73,1.20960,1.20880,6.90,1.05440,6.90,0.80
566,567,2026-07-10,Bear_Cr,32,1.19590,87.47,1070.79,1.19840,1.19800,2.50,0.98332,2.50,0.40
583,584,2026-07-31,Bear_Cr,FC20,1.23520,87.89,1111.53,1.32530,1.32330,90.10,1.02364,90.10,2.00
600,601,2026-08-06,Bear_Cr,FC12,1.21460,87.84,1130.70,1.23670,1.23550,22.10,1.04286,22.10,1.20

--- TSS Data for Site: Camp_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
17,18,2024-10-13,Camp_Cr,17,1.22600,88.92,1139.68,1.25000,1.24800,24.00,1.05076,24.00,2.00
27,28,2024-10-19,Camp_Cr,8,1.23700,101.39,1113.49,1.24100,1.23900,4.00,1.01210,4.00,2.00
34,35,2024-11-03,Camp_Cr,28,1.23200,88.33,1129.93,1.23640,1.23461,4.40,1.04160,4.40,1.79
63,64,2024-11-09,Camp_Cr,56,1.21300,88.95,1125.12,1.21643,1.21510,3.43,1.03617,3.43,1.33
80,81,2024-11-24,Camp_Cr,6,1.22630,87.42,1110.77,1.23685,1.23572,10.55,1.02335,10.55,1.13
95,96,2025-01-17,Camp_Cr,22,1.24128,88.54,634.51,1.24499,1.24419,3.71,0.54597,3.71,0.80
110,111,2025-01-30,Camp_Cr,13,1.19489,88.10,1093.60,1.19737,1.19661,2.48,1.00550,2.48,0.76
125,126,2025-02-15,Camp_Cr,4,1.23431,88.51,1072.96,1.23677,1.23586,2.46,0.98445,2.46,0.91
141,142,2025-03-02,Camp_Cr,58,1.21562,87.61,1147.96,1.53894,1.52569,323.32,1.06035,323.32,13.25
153,154,2025-03-19,Camp_Cr,8,1.23277,88.70,1092.33,1.23857,1.23781,5.80,1.00363,5.80,0.76
165,166,2025-03-30,Camp_Cr,6,1.23126,88.99,1020.61,1.23609,1.23547,4.83,0.93162,4.83,0.62
178,179,2025-04-15,Camp_Cr,20,1.18801,87.80,1051.64,1.24008,1.23792,52.07,0.96384,52.07,2.16
196,197,2025-04-28,Camp_Cr,50,1.21932,88.53,1121.14,1.23404,1.23288,14.72,1.03261,14.72,1.16
214,215,2025-05-10,Camp_Cr,17,1.22239,88.35,1136.59,1.31439,1.30763,92.00,1.04824,92.00,6.76
233,234,2025-05-27,Camp_Cr,14,1.20979,88.55,1101.16,1.21441,1.21391,4.62,1.01261,4.62,0.50
252,253,2025-06-08,Camp_Cr,15,1.21226,88.41,1136.40,1.21471,1.21369,2.45,1.04799,2.45,1.02
271,272,2025-06-22,Camp_Cr,25,1.22493,88.52,1138.34,1.23775,1.23542,12.82,1.04982,12.82,2.33
291,292,2025-07-07,Camp_Cr,9,1.19144,88.36,1116.80,1.36117,1.35628,169.73,1.02844,169.73,4.89
310,311,2025-07-21,Camp_Cr,4,1.23106,88.52,1130.43,1.23823,1.23706,7.17,1.04191,7.17,1.17
329,330,2025-08-01,Camp_Cr,8,1.23800,87.89,1128.40,1.24200,1.24100,4.00,1.04051,4.00,1.00
348,349,2025-08-14,Camp_Cr,56,1.22200,88.78,1084.10,1.22500,1.22310,3.00,0.99532,3.00,1.90
381,382,2025-08-29,Camp_Cr,33,1.23970,88.45,1140.78,1.24570,1.24360,6.00,1.05233,6.00,2.10
396,397,2025-09-12,Camp_Cr,53,1.21820,106.69,1128.06,1.22430,1.22260,6.10,1.02137,6.10,1.70
419,420,2025-09-26,Camp_Cr,58,1.21640,87.73,1118.11,1.22670,1.22470,10.30,1.03038,10.30,2.00
449,450,2025-10-04,Camp_Cr,68,1.22640,88.80,1091.00,1.23080,1.22860,4.40,1.00220,4.40,2.20
459,460,2025-10-10,Camp_Cr,FC14,1.21440,88.80,1119.55,1.22410,1.22210,9.70,1.03075,9.70,2.00
478,479,2025-12-04,Camp_Cr,FC4,1.19080,88.73,1057.00,1.19290,1.19250,2.10,0.96827,2.10,0.40
492,493,2026-02-07,Camp_Cr,FC12,1.22060,88.99,1108.68,1.22710,1.22610,6.50,1.01969,6.50,1.00
502,503,2026-03-08,Camp_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,519,2026-04-11,Camp_Cr,33,1.23880,87.44,1014.60,1.28100,1.27640,42.20,0.92716,42.20,4.60
537,538,2026-05-11,Camp_Cr,FC11,1.21250,88.39,1133.81,1.22700,1.22460,14.50,1.04542,14.50,2.40
551,552,2026-06-13,Camp_Cr,45,1.23310,88.99,1084.82,1.24200,1.24080,8.90,0.99583,8.90,1.20
568,569,2026-07-10,Camp_Cr,RC8,1.20620,88.86,1102.53,1.21200,1.21050,5.80,1.01367,5.80,1.50
585,586,2026-07-31,Camp_Cr,27,1.21950,87.91,1112.95,1.22230,1.22160,2.80,1.02504,2.80,0.70
602,603,2026-08-06,Camp_Cr,FC26,1.20720,87.53,1112.36,1.21020,1.20930,3.00,1.02483,3.00,0.90

--- TSS Data for Site: Canyon_Cr_Banner ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
389,390,2025-08-29,Canyon_Cr_Banner,16,1.2290,87.72,1075.40,1.2376,1.2357,8.6,0.98768,8.6,1.9
410,411,2025-09-12,Canyon_Cr_Banner,2,1.2301,102.85,1090.46,NaN,1.2323,NaN,0.98761,NaN,NaN
433,434,2025-09-26,Canyon_Cr_Banner,38,1.2267,87.58,1076.76,1.2337,1.2329,7.0,0.98918,7.0,0.8
464,465,2025-10-10,Canyon_Cr_Banner,R21,1.2385,88.83,1101.57,1.2424,1.2426,3.9,1.01274,3.9,-0.2

--- TSS Data for Site: Canyon_Cr_DF2 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
411,412,2025-09-12,Canyon_Cr_DF2,32,1.2118,102.82,1034.33,NaN,1.2427,NaN,0.93151,NaN,NaN
434,435,2025-09-26,Canyon_Cr_DF2,HZ,1.2011,87.91,1099.57,1.2064,1.2046,5.3,1.01166,5.3,1.8

--- TSS Data for Site: Canyon_Cr_DF4 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
414,415,2025-09-12,Canyon_Cr_DF4,39,1.2349,102.79,1146.36,NaN,1.2475,NaN,1.04357,NaN,NaN
437,438,2025-09-26,Canyon_Cr_DF4,33,1.2400,88.07,1061.91,1.2444,1.2434,4.4,0.97384,4.4,1.0

--- TSS Data for Site: Canyon_Cr_DF5 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
413,414,2025-09-12,Canyon_Cr_DF5,5,1.2218,105.10,1039.92,NaN,1.2378,NaN,0.93482,NaN,NaN
436,437,2025-09-26,Canyon_Cr_DF5,16,1.2291,88.81,1084.96,1.2327,1.2320,3.6,0.99615,3.6,0.7
465,466,2025-10-10,Canyon_Cr_DF5,FC19,1.2003,89.74,1117.40,1.2128,1.2110,12.5,1.02766,12.5,1.8

--- TSS Data for Site: Canyon_Cr_DF8 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
412,413,2025-09-12,Canyon_Cr_DF8,FC11,1.2111,102.41,1091.29,NaN,1.3273,NaN,0.98888,NaN,NaN
435,436,2025-09-26,Canyon_Cr_DF8,43,1.2296,88.83,1106.01,1.2375,1.2360,7.9,1.01718,7.9,1.5

--- TSS Data for Site: Canyon_Cr_DF_1 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
390,391,2025-08-29,Canyon_Cr_DF_1,38,1.2297,105.86,1109.75,1.282,1.3885,52.3,1.00389,52.3,-106.5

--- TSS Data for Site: Canyon_Cr_DF_3 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
391,392,2025-08-29,Canyon_Cr_DF_3,25,1.2311,104.35,1133.14,1.5372,1.4835,306.1,1.02879,306.1,53.7

--- TSS Data for Site: Canyon_Cr_SFP ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
2,3,2024-10-11,Canyon_Cr_SFP,25,1.23200,87.50,1117.52,1.24100,1.23600,9.00,1.03002,9.00,5.00
13,14,2024-10-12,Canyon_Cr_SFP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,2024-10-19,Canyon_Cr_SFP,11,1.21500,101.63,1141.61,1.21900,1.21700,4.00,1.03998,4.00,2.00
42,43,2024-11-03,Canyon_Cr_SFP,36,1.20900,87.69,1078.19,1.21550,1.21401,6.50,0.99050,6.50,1.49
61,62,2024-11-09,Canyon_Cr_SFP,55,1.21800,87.69,1129.60,1.22278,1.22189,4.78,1.04191,4.78,0.89
78,79,2024-11-24,Canyon_Cr_SFP,60,1.21783,88.40,1137.76,1.22348,1.22174,5.65,1.04936,5.65,1.74
93,94,2025-01-17,Canyon_Cr_SFP,50,1.21728,87.82,1121.66,1.22062,1.21937,3.34,1.03384,3.34,1.25
108,109,2025-01-30,Canyon_Cr_SFP,60,1.22525,88.48,1108.00,1.22912,1.22815,3.87,1.01952,3.87,0.97
123,124,2025-02-15,Canyon_Cr_SFP,60,1.22452,88.36,1135.65,1.23561,1.23328,11.09,1.04729,11.09,2.33
139,140,2025-03-02,Canyon_Cr_SFP,9,1.18977,88.49,1146.88,1.19927,1.19713,9.50,1.05839,9.50,2.14
151,152,2025-03-19,Canyon_Cr_SFP,4,1.23124,88.36,1140.98,1.24274,1.23768,11.50,1.05262,11.50,5.06
163,164,2025-03-30,Canyon_Cr_SFP,58,1.20998,88.23,1135.60,1.23161,1.22774,21.63,1.04737,21.63,3.87
176,177,2025-04-15,Canyon_Cr_SFP,51,1.18917,89.20,1159.66,1.21881,1.21461,29.64,1.07046,29.64,4.20
194,195,2025-04-28,Canyon_Cr_SFP,12,1.19278,88.36,1114.68,1.23775,1.23330,44.97,1.02632,44.97,4.45
212,213,2025-05-10,Canyon_Cr_SFP,3,1.21485,87.88,1139.71,1.34684,1.32987,131.99,1.05183,131.99,16.97
231,232,2025-05-27,Canyon_Cr_SFP,32,1.21092,87.47,1118.96,1.31931,1.31456,108.39,1.03149,108.39,4.75
250,251,2025-06-08,Canyon_Cr_SFP,6,1.23137,88.72,1148.24,1.23923,1.23747,7.86,1.05952,7.86,1.76
269,270,2025-06-22,Canyon_Cr_SFP,18,1.23889,88.37,1148.08,1.24415,1.24346,5.26,1.05971,5.26,0.69
289,290,2025-07-07,Canyon_Cr_SFP,35,1.22772,89.01,1109.70,1.25826,1.25398,30.54,1.02069,30.54,4.28
308,309,2025-07-21,Canyon_Cr_SFP,20,1.18911,89.00,1134.53,1.19946,1.19775,10.35,1.04553,10.35,1.71
327,328,2025-08-01,Canyon_Cr_SFP,17,1.22300,88.73,1143.55,1.24100,1.23100,18.00,1.05482,18.00,10.00
346,347,2025-08-14,Canyon_Cr_SFP,53,1.21700,89.83,1149.43,1.22100,1.22070,4.00,1.05960,4.00,0.30
361,362,2025-08-27,Canyon_Cr_SFP,"4,40,39",3.71590,57.98,607.70,3.87320,3.84840,157.30,0.54972,157.30,24.80
379,380,2025-08-29,Canyon_Cr_SFP,4,1.23770,88.24,1149.05,1.39290,1.36960,155.20,1.06081,155.20,23.30
397,398,2025-09-12,Canyon_Cr_SFP,1,1.20720,106.05,1119.50,1.22590,1.22330,18.70,1.01345,18.70,2.60
420,421,2025-09-26,Canyon_Cr_SFP,45,1.23460,88.81,1101.35,1.24220,1.24030,7.60,1.01254,7.60,1.90
446,447,2025-10-04,Canyon_Cr_SFP,11,1.21950,88.39,1107.52,1.40800,1.38860,188.50,1.01913,188.50,19.40
460,461,2025-10-10,Canyon_Cr_SFP,FC16,1.20200,87.88,1113.98,1.25800,1.25290,56.00,1.02610,56.00,5.10
479,480,2025-12-04,Canyon_Cr_SFP,FC19,1.20040,88.09,1060.58,1.30880,1.30250,108.40,0.97249,108.40,6.30
493,494,2026-02-07,Canyon_Cr_SFP,1,1.20860,87.56,1139.92,1.30020,1.29900,91.60,1.05236,91.60,1.20
503,504,2026-03-08,Canyon_Cr_SFP,47,1.22840,88.73,1085.64,1.24320,1.24200,14.80,0.99691,14.80,1.20
519,520,2026-04-11,Canyon_Cr_SFP,55,1.22520,88.87,1077.76,1.50360,1.47960,278.40,0.98889,278.40,24.00
538,539,2026-05-11,Canyon_Cr_SFP,9,1.19600,87.56,1084.02,1.50020,1.48600,304.20,0.99646,304.20,14.20
552,553,2026-06-13,Canyon_Cr_SFP,FC16,1.20400,88.85,1122.14,1.22160,1.21980,17.60,1.03329,17.60,1.80
569,570,2026-07-10,Canyon_Cr_SFP,FC9,1.22310,88.47,1131.77,1.23340,1.23150,10.30,1.04330,10.30,1.90
586,587,2026-07-31,Canyon_Cr_SFP,47,1.21470,88.38,1128.62,1.33560,1.32930,120.90,1.04024,120.90,6.30
603,604,2026-08-06,Canyon_Cr_SFP,2,1.22430,87.45,1060.33,1.29410,1.29070,69.80,0.97288,69.80,3.40

--- TSS Data for Site: Canyon_Cr_slump1 ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
415,416,2025-09-12,Canyon_Cr_slump1,31,1.2258,102.87,1142.19,NaN,1.2773,NaN,1.03932,NaN,NaN
438,439,2025-09-26,Canyon_Cr_slump1,8,1.2392,89.61,1105.27,1.2467,1.2458,7.5,1.01566,7.5,0.9
466,467,2025-10-10,Canyon_Cr_slump1,2,1.2298,88.49,1113.33,1.3056,1.2974,75.8,1.02484,75.8,8.2

--- TSS Data for Site: Canyon_cr_avalanche (HP_old) ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
31,32,2024-10-19,Canyon_cr_avalanche (HP_old),5,1.210,101.21,1153.17,1.2230,1.22,13.0,1.05196,13.0,3.0
38,39,2024-11-03,Canyon_cr_avalanche (HP_old),32,1.211,88.13,1139.86,1.2202,NaN,9.2,1.05173,9.2,NaN

--- TSS Data for Site: Chapman_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
10,11,2024-10-12,Chapman_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,2024-11-04,Chapman_Cr,38,1.22700,88.42,1091.96,1.23600,1.22905,9.00,1.00354,9.00,6.95
286,287,2025-07-07,Chapman_Cr,"18,22,3,14,12",6.10803,88.21,1063.10,9.13658,8.99315,3028.55,0.97489,3028.55,143.43
305,306,2025-07-21,Chapman_Cr,51,1.18985,88.47,1026.57,1.21803,1.21578,28.18,0.93810,28.18,2.25
324,325,2025-08-01,Chapman_Cr,14,1.20800,87.45,1081.21,1.23100,1.23500,23.00,0.99376,23.00,-4.00
343,344,2025-08-14,Chapman_Cr,34,1.19800,88.75,1128.46,1.21100,1.20990,13.00,1.03971,13.00,1.10
454,455,2025-10-05,Chapman_Cr,53,1.21950,88.28,1038.67,1.27250,1.26650,53.00,0.95039,53.00,6.00

--- TSS Data for Site: Flat_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
221,222,2025-05-10,Flat_Cr,14,1.20734,87.83,1145.42,1.462480,1.39162,255.140,1.05759,255.140,70.860
240,241,2025-05-27,Flat_Cr,50,1.21961,88.40,1079.38,1.274460,1.26386,54.850,0.99098,54.850,10.600
259,260,2025-06-08,Flat_Cr,55,1.22109,88.44,1155.38,1.224350,1.22288,3.260,1.06694,3.260,1.470
278,279,2025-06-22,Flat_Cr,22,1.23853,89.61,1126.14,1.233997,1.23914,-4.533,1.03653,-4.533,-5.143

--- TSS Data for Site: Fox_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
12,13,2024-10-12,Fox_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,2024-10-19,Fox_Cr,13,1.19300,101.270,1153.79,1.19400,1.19200,1.00,1.052520,1.00,2.00
40,41,2024-11-03,Fox_Cr,34,1.19700,88.550,1148.14,1.20190,1.19760,4.90,1.059590,4.90,4.30
59,60,2024-11-09,Fox_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,77,2024-11-24,Fox_Cr,7,1.20739,87.460,1127.14,1.20993,1.20851,2.54,1.039680,2.54,1.42
91,92,2025-01-17,Fox_Cr,5,1.21864,88.460,1034.95,1.23582,1.22010,17.18,0.946490,17.18,15.72
106,107,2025-01-30,Fox_Cr,50,1.21984,88.320,1138.20,1.22171,1.22084,1.87,1.049880,1.87,0.87
121,122,2025-02-15,Fox_Cr,22,1.24235,88.200,1121.89,1.24343,1.24254,1.08,1.033690,1.08,0.89
137,138,2025-03-02,Fox_Cr,6,1.22975,88.440,1128.95,1.24023,1.23667,10.48,1.040510,10.48,3.56
149,150,2025-03-19,Fox_Cr,5,1.21797,88.500,1105.05,1.21977,1.21875,1.80,1.016550,1.80,1.02
161,162,2025-03-30,Fox_Cr,46,1.22627,87.440,1112.12,1.23878,1.23499,12.51,1.024680,12.51,3.79
174,175,2025-04-15,Fox_Cr,12,1.19321,88.330,1161.69,1.21205,1.20693,18.84,1.073360,18.84,5.12
192,193,2025-04-28,Fox_Cr,20,1.19313,88.560,1142.09,1.20863,1.20434,15.50,1.053530,15.50,4.29
210,211,2025-05-10,Fox_Cr,50,1.21878,88.570,1150.82,1.23162,1.22601,12.84,1.062250,12.84,5.61
229,230,2025-05-27,Fox_Cr,3,1.23748,88.740,1116.93,1.24144,1.24035,3.96,1.028190,3.96,1.09
248,249,2025-06-08,Fox_Cr,4,1.23251,88.500,1156.60,1.23621,1.23426,3.70,1.068100,3.70,1.95
267,268,2025-06-22,Fox_Cr,3,1.23361,88.450,1131.32,1.23537,1.23426,1.76,1.042870,1.76,1.11
287,288,2025-07-07,Fox_Cr,4,1.23205,88.440,1128.80,1.27762,1.26813,45.57,1.040360,45.57,9.49
306,307,2025-07-21,Fox_Cr,1,1.21293,88.400,1131.35,1.21856,1.21693,5.63,1.042950,5.63,1.63
325,326,2025-08-01,Fox_Cr,25,1.23000,88.230,1119.00,1.24400,1.23200,14.00,1.030770,14.00,12.00
344,345,2025-08-14,Fox_Cr,51,1.19600,88.910,1120.25,1.19900,1.19830,3.00,1.031340,3.00,0.70
363,364,2025-08-27,Fox_Cr,46,1.23360,58.498,566.91,1.24960,1.24500,16.00,0.508412,16.00,4.60
377,378,2025-08-29,Fox_Cr,58,1.21570,88.360,1030.99,1.22160,1.21910,5.90,0.942630,5.90,2.50
399,400,2025-09-12,Fox_Cr,47,1.22890,102.550,1136.36,1.23520,1.23290,6.30,1.033810,6.30,2.30
422,423,2025-09-26,Fox_Cr,44,1.22470,88.400,1080.69,1.23350,1.23040,8.80,0.992290,8.80,3.10
444,445,2025-10-04,Fox_Cr,25,1.23130,87.580,1090.86,1.24200,1.23910,10.70,1.003280,10.70,2.90
462,463,2025-10-10,Fox_Cr,1,1.20940,88.390,1112.15,1.21500,1.21350,5.60,1.023760,5.60,1.50
481,482,2025-12-04,Fox_Cr,18,1.24380,89.070,1103.77,1.25520,1.25250,11.40,1.014700,11.40,2.70
496,497,2026-02-07,Fox_Cr,4,1.23550,87.890,1086.22,1.24500,1.24230,9.50,0.998330,9.50,2.70
506,507,2026-03-08,Fox_Cr,49,1.22150,88.330,1085.09,1.22730,1.22670,5.80,0.996760,5.80,0.60
521,522,2026-04-11,Fox_Cr,51,1.19530,88.340,1124.04,1.22490,1.21890,29.60,1.035700,29.60,6.00
540,541,2026-05-11,Fox_Cr,13,1.19830,87.890,1120.47,1.21190,1.20940,13.60,1.032580,13.60,2.50
554,555,2026-06-13,Fox_Cr,14,1.21000,88.390,1073.72,1.21470,1.21310,4.70,0.985330,4.70,1.60
571,572,2026-07-10,Fox_Cr,FC29,1.08470,89.620,1097.08,1.08850,1.08730,3.80,1.007460,3.80,1.20
588,589,2026-07-31,Fox_Cr,37,1.19820,88.350,1092.37,1.19960,1.19900,1.40,1.004020,1.40,0.60
605,606,2026-08-06,Fox_Cr,RC8,1.19830,88.330,1099.74,1.19940,1.19860,1.10,1.011410,1.10,0.80

--- TSS Data for Site: GO_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
39,40,2024-11-03,GO_Cr,33,1.23700,88.55,1055.63,1.24360,1.23988,6.60,0.96708,6.60,3.72
58,59,2024-11-09,GO_Cr,52,1.17900,88.75,939.39,1.18053,1.17979,1.53,0.85064,1.53,0.74
75,76,2024-11-24,GO_Cr,25,1.22225,88.49,837.95,1.22509,1.22367,2.84,0.74946,2.84,1.42
90,91,2025-01-17,GO_Cr,6,1.23579,87.63,824.64,1.24951,1.24705,13.72,0.73701,13.72,2.46
105,106,NaT,GO_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,121,NaT,GO_Cr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,137,2025-03-02,GO_Cr,8,1.23326,87.82,1137.83,1.24189,1.23959,8.63,1.05001,8.63,2.30
183,184,2025-04-15,GO_Cr,13,1.19094,88.35,1134.45,1.22039,1.21249,29.45,1.04610,29.45,7.90
201,202,2025-04-28,GO_Cr,15,1.21681,88.48,1084.39,1.25479,1.24834,37.98,0.99591,37.98,6.45
218,219,2025-05-10,GO_Cr,"19,46",2.44051,88.39,1140.98,2.77911,2.70147,338.60,1.05259,338.60,77.64
237,238,2025-05-27,GO_Cr,25,1.23027,87.65,1114.95,1.24574,1.24239,15.47,1.02730,15.47,3.35
256,257,2025-06-08,GO_Cr,17,1.21785,87.59,1145.26,1.22247,1.22084,4.62,1.05767,4.62,1.63
275,276,2025-06-22,GO_Cr,1,1.21104,87.51,1104.42,1.21275,1.21167,1.71,1.01691,1.71,1.08
295,296,2025-07-07,GO_Cr,8,1.23389,88.74,1107.50,1.32969,1.31897,95.80,1.01876,95.80,10.72
314,315,2025-07-21,GO_Cr,60,1.22138,88.57,1135.37,1.22659,1.22472,5.21,1.04680,5.21,1.87
333,334,2025-08-01,GO_Cr,6,1.23700,88.49,1099.43,1.36600,1.35700,129.00,1.01094,129.00,9.00
352,353,2025-08-14,GO_Cr,39,1.23300,88.75,1082.22,1.24700,1.24380,14.00,0.99347,14.00,3.20
385,386,2025-08-29,GO_Cr,31,1.22780,88.50,1078.62,1.24820,1.24560,20.40,0.99012,20.40,2.60
401,402,2025-09-12,GO_Cr,37,1.21350,102.63,1111.06,1.22350,1.22080,10.00,1.00843,10.00,2.70
424,425,2025-09-26,GO_Cr,51,1.19540,88.74,1069.60,1.20430,1.20170,8.90,0.98086,8.90,2.60
469,470,2025-10-10,GO_Cr,37,1.21360,88.50,1081.19,1.24240,1.24040,28.80,0.99269,28.80,2.00
533,534,2026-05-11,GO_Cr,20,1.19550,88.85,1089.65,1.45230,1.43070,256.80,1.00080,256.80,21.60
558,559,2026-06-13,GO_Cr,4,1.23880,88.19,989.96,1.24060,1.23960,1.80,0.90177,1.80,1.00
575,576,2026-07-10,GO_Cr,FC27,1.24410,88.40,1074.02,1.24640,1.24520,2.30,0.98562,2.30,1.20
592,593,2026-07-31,GO_Cr,17,1.20840,88.71,1069.70,1.21040,1.20980,2.00,0.98099,2.00,0.60
609,610,2026-08-06,GO_Cr,58,1.20900,88.44,1095.88,1.21010,1.20950,1.10,1.00744,1.10,0.60

--- TSS Data for Site: HP ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
36,37,2024-11-03,HP,30,1.22000,88.64,1136.18,1.22400,1.22213,4.00,1.04754,4.00,1.87
56,57,2024-11-09,HP,50,1.21000,88.73,1133.81,1.21524,1.21425,5.24,1.04508,5.24,0.99
73,74,2024-11-24,HP,3,1.23191,87.83,1128.19,1.23412,1.23288,2.21,1.04036,2.21,1.24
88,89,2025-01-17,HP,60,1.22496,88.71,1121.81,1.22545,1.22479,0.49,1.03310,0.49,0.66
103,104,2025-01-30,HP,7,1.21282,88.71,1103.50,1.21434,1.21434,1.52,1.01479,1.52,0.00
118,119,NaT,HP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,135,2025-03-02,HP,7,1.20842,88.52,1082.60,1.30633,1.30441,97.91,0.99408,97.91,1.92
181,182,2025-04-15,HP,22,1.23741,87.86,1122.84,1.26152,1.25643,24.11,1.03498,24.11,5.09
199,200,2025-04-28,HP,13,1.19664,88.51,1147.04,1.22149,1.21752,24.85,1.05853,24.85,3.97
216,217,2025-05-10,HP,25,1.22966,87.49,1147.26,1.29725,1.28673,67.59,1.05977,67.59,10.52
235,236,2025-05-27,HP,46,1.23357,87.49,1092.76,1.24801,1.24594,14.44,1.00527,14.44,2.07
254,255,2025-06-08,HP,14,1.20401,87.45,1058.47,1.20674,1.20547,2.73,0.97102,2.73,1.27
273,274,2025-06-22,HP,13,1.19078,88.51,1152.22,1.19254,1.19183,1.76,1.06371,1.76,0.71
293,294,2025-07-07,HP,25,1.22470,89.61,1111.40,1.23748,1.23513,12.78,1.02179,12.78,2.35
312,313,2025-07-21,HP,6,1.23295,89.04,1122.45,1.23758,1.23627,4.63,1.03341,4.63,1.31
331,332,2025-08-01,HP,7,1.21400,88.57,1140.50,1.21500,1.21800,1.00,1.05193,1.00,-3.00
350,351,2025-08-14,HP,29,1.24700,88.07,1138.77,1.25000,1.25030,3.00,1.05070,3.00,-0.30
383,384,2025-08-29,HP,51,1.19600,88.08,1152.99,1.41600,1.39460,220.00,1.06491,220.00,21.40
403,404,2025-09-12,HP,34,1.19730,89.62,NaN,1.22560,1.21670,28.30,NaN,28.30,8.90
426,427,2025-09-26,HP,FC20,1.24940,88.20,1111.12,1.25570,1.25500,6.30,1.02292,6.30,0.70
467,468,2025-10-10,HP,9,1.19620,87.45,1119.05,1.25760,1.25350,61.40,1.03160,61.40,4.10
513,514,2026-04-11,HP,29,1.24930,87.89,1136.69,1.52450,1.49690,275.20,1.04880,275.20,27.60
531,532,2026-05-11,HP,FC19,1.20080,88.34,1147.86,1.39040,1.37470,189.60,1.05952,189.60,15.70
556,557,2026-06-13,HP,2,1.23080,88.34,1085.25,1.23330,1.23260,2.50,0.99691,2.50,0.70
573,574,2026-07-10,HP,59,1.22420,87.99,1126.26,1.22760,1.22640,3.40,1.03827,3.40,1.20
590,591,2026-07-31,HP,51,1.17920,87.84,1132.66,1.32560,1.32180,146.40,1.04482,146.40,3.80
607,608,2026-08-06,HP,41,1.18860,88.87,1133.05,1.20930,1.20810,20.70,1.04418,20.70,1.20

--- TSS Data for Site: MFP_Crouch ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
358,359,2025-08-27,MFP_Crouch,58,1.2177,58.031,579.85,1.2268,1.2237,9.1,0.521819,9.1,3.1

--- TSS Data for Site: MainPayette_Gauge ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
356,357,2025-08-27,MainPayette_Gauge,25,1.2314,58.144,591.81,1.2751,1.2673,43.7,0.533666,43.7,7.8

--- TSS Data for Site: Nutcracker_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
167,168,2025-03-30,Nutcracker_Cr,13,1.19138,88.35,1054.18,1.20208,1.20025,10.70,0.96583,10.70,1.83
180,181,2025-04-15,Nutcracker_Cr,4,1.23019,88.23,1103.09,1.23278,1.23224,2.59,1.01486,2.59,0.54
198,199,2025-04-28,Nutcracker_Cr,7,1.21078,89.00,1093.28,1.21468,1.21361,3.90,1.00428,3.90,1.07

--- TSS Data for Site: SFP_Alder_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
4,5,2024-10-12,SFP_Alder_Cr,16,1.22800,88.350,1159.42,1.23100,1.22800,3.00,1.071070,3.00,3.00
18,19,2024-10-19,SFP_Alder_Cr,1,1.21000,87.360,1155.33,1.21700,1.21300,7.00,1.067970,7.00,4.00
50,51,2024-11-09,SFP_Alder_Cr,44,1.21400,88.070,1115.80,1.21681,1.21594,2.81,1.027730,2.81,0.87
67,68,2024-11-24,SFP_Alder_Cr,4,1.22797,88.510,1143.17,1.25297,1.24823,25.00,1.054660,25.00,4.74
82,83,2025-01-17,SFP_Alder_Cr,25,1.22760,88.430,1124.32,1.22865,1.22795,1.05,1.035890,1.05,0.70
97,98,2025-01-30,SFP_Alder_Cr,51,1.19256,87.450,1158.50,1.20222,1.20111,9.66,1.071050,9.66,1.11
112,113,2025-02-15,SFP_Alder_Cr,5,1.21926,87.430,1135.29,1.22298,1.22181,3.72,1.047860,3.72,1.17
128,129,2025-03-02,SFP_Alder_Cr,60,1.22051,87.840,1126.01,1.22893,1.22688,8.42,1.038170,8.42,2.05
143,144,2025-03-19,SFP_Alder_Cr,60,1.22094,88.350,1141.14,1.22874,1.22665,7.80,1.052790,7.80,2.09
155,156,2025-03-30,SFP_Alder_Cr,25,1.22538,87.800,1140.05,1.24697,1.24309,21.59,1.052250,21.59,3.88
168,169,2025-04-15,SFP_Alder_Cr,60,1.22029,87.630,1121.48,1.24459,1.24034,24.30,1.033850,24.30,4.25
186,187,2025-04-28,SFP_Alder_Cr,46,1.23313,89.610,1124.44,1.30538,1.29695,72.25,1.034830,72.25,8.43
204,205,2025-05-10,SFP_Alder_Cr,6,1.23715,88.540,1150.84,1.33699,1.32745,99.84,1.062300,99.84,9.54
223,224,2025-05-27,SFP_Alder_Cr,8,1.23464,44.600,657.59,1.25933,1.25753,24.69,0.612990,24.69,1.80
242,243,2025-06-08,SFP_Alder_Cr,25,1.22576,88.390,1127.21,1.25754,1.25497,31.78,1.038820,31.78,2.57
261,262,2025-06-22,SFP_Alder_Cr,31,1.22096,88.400,1146.14,1.23168,1.22989,10.72,1.057740,10.72,1.79
280,281,2025-07-07,SFP_Alder_Cr,13,1.19237,87.890,1156.10,1.21994,1.21607,27.57,1.068210,27.57,3.87
299,300,2025-07-21,SFP_Alder_Cr,5,1.21634,87.650,1132.09,1.22811,1.22575,11.77,1.044440,11.77,2.36
318,319,2025-08-01,SFP_Alder_Cr,13,1.19100,87.630,1137.63,1.21600,1.21200,25.00,1.050000,25.00,4.00
337,338,2025-08-14,SFP_Alder_Cr,32,1.21200,88.340,1155.71,1.22500,1.22380,13.00,1.067370,13.00,1.20
370,371,2025-08-27,SFP_Alder_Cr,"1,HZ,FC20,55,51,44,50,14,17,7,18",13.43370,58.226,594.02,17.50040,16.79060,4066.70,0.535794,4066.70,709.80
371,372,2025-08-29,SFP_Alder_Cr,45,1.23380,88.560,1142.10,1.29370,1.28490,59.90,1.053540,59.90,8.80
409,410,2025-09-12,SFP_Alder_Cr,14,1.20900,88.380,1153.68,1.21360,1.21250,4.60,1.065300,4.60,1.10
432,433,2025-09-26,SFP_Alder_Cr,41,1.19540,88.380,1123.35,1.19850,1.19690,3.10,1.034970,3.10,1.60
453,454,2025-10-04,SFP_Alder_Cr,"57,FC11",2.42450,102.860,1080.07,2.77360,2.73050,349.10,0.977210,349.10,43.10
474,475,2025-10-10,SFP_Alder_Cr,FC17,1.22200,88.730,1108.92,1.23110,1.23030,9.10,1.020190,9.10,0.80
488,489,2025-12-04,SFP_Alder_Cr,FC11,1.21170,88.340,1129.21,1.21370,1.21300,2.00,1.040870,2.00,0.70
489,490,2026-02-07,SFP_Alder_Cr,45,1.23260,88.510,1162.78,1.23740,1.23610,4.80,1.074270,4.80,1.30
512,513,2026-03-08,SFP_Alder_Cr,28,1.24040,88.330,1138.94,1.24360,1.24270,3.20,1.050610,3.20,0.90
528,529,2026-04-11,SFP_Alder_Cr,40,1.23840,87.970,1128.68,1.34200,1.32840,103.60,1.040710,103.60,13.60
547,548,2026-05-11,SFP_Alder_Cr,36,1.21270,87.830,1129.44,1.31060,1.30400,97.90,1.041610,97.90,6.60
564,565,2026-06-13,SFP_Alder_Cr,31,1.22730,88.450,1136.51,1.23910,1.23750,11.80,1.048060,11.80,1.60
581,582,2026-07-10,SFP_Alder_Cr,28,1.24170,88.520,1136.94,1.27970,1.27550,38.00,1.048420,38.00,4.20
598,599,2026-07-31,SFP_Alder_Cr,33,1.22320,88.530,1108.81,1.26990,1.26600,46.70,1.020280,46.70,3.90
615,616,2026-08-06,SFP_Alder_Cr,49,1.21560,88.280,1136.24,1.23620,1.23410,20.60,1.047960,20.60,2.10

--- TSS Data for Site: SFP_Alder_Cr_AM ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
529,530,2026-04-11,SFP_Alder_Cr_AM,27,1.2342,87.83,1148.56,1.3014,1.2933,67.2,1.06073,67.2,8.1

--- TSS Data for Site: SFP_BJ ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
6,7,2024-10-12,SFP_BJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,2024-10-19,SFP_BJ,6,1.23000,101.400,1143.84,1.23400,1.23000,4.00,1.042440,4.00,4.00
47,48,2024-11-04,SFP_BJ,40,1.23700,88.010,1105.42,1.24520,1.23789,8.20,1.017410,8.20,7.31
53,54,2024-11-09,SFP_BJ,47,1.21800,88.110,1121.83,1.22115,1.22053,3.15,1.033720,3.15,0.62
70,71,2024-11-24,SFP_BJ,13,1.18838,87.790,1108.58,1.19682,1.19571,8.44,1.020790,8.44,1.11
85,86,2025-01-17,SFP_BJ,20,1.19206,88.470,1103.92,1.19452,1.19363,2.46,1.015450,2.46,0.89
100,101,2025-01-30,SFP_BJ,25,1.22851,87.620,1108.60,1.23037,1.23037,1.86,1.020980,1.86,0.00
115,116,2025-02-15,SFP_BJ,6,1.23456,87.800,1112.77,1.24461,1.24045,10.05,1.024970,10.05,4.16
131,132,2025-03-02,SFP_BJ,14,1.20186,88.980,1150.60,1.20924,1.20818,7.38,1.061620,7.38,1.06
146,147,2025-03-19,SFP_BJ,25,1.22314,87.440,1118.01,1.22588,1.22503,2.74,1.030570,2.74,0.85
158,159,2025-03-30,SFP_BJ,22,1.23704,88.440,1122.86,1.26056,1.25819,23.52,1.034420,23.52,2.37
171,172,2025-04-15,SFP_BJ,18,1.23828,88.990,1152.88,1.26024,1.25817,21.96,1.063890,21.96,2.07
189,190,2025-04-28,SFP_BJ,55,1.22665,88.720,1142.14,1.27748,1.27417,50.83,1.053420,50.83,3.31
207,208,2025-05-10,SFP_BJ,7,1.21348,87.650,1157.67,1.35082,1.34374,137.34,1.070020,137.34,7.08
226,227,2025-05-27,SFP_BJ,1,1.21597,87.890,1111.25,1.31336,1.31050,97.39,1.023360,97.39,2.86
245,246,2025-06-08,SFP_BJ,1,1.21321,88.190,1124.24,1.22617,1.22471,12.96,1.036050,12.96,1.46
264,265,2025-06-22,SFP_BJ,8,1.23373,87.640,1135.51,1.23691,1.23604,3.18,1.047870,3.18,0.87
283,284,2025-07-07,SFP_BJ,46,1.22874,88.400,1159.70,1.25283,1.24925,24.09,1.071300,24.09,3.58
302,303,2025-07-21,SFP_BJ,23,1.23013,89.010,1143.23,1.23394,1.23301,3.81,1.054220,3.81,0.93
321,322,2025-08-01,SFP_BJ,4,1.23100,88.210,1116.96,1.24700,1.23900,16.00,1.028750,16.00,8.00
340,341,2025-08-14,SFP_BJ,68,1.22500,88.220,1099.53,1.22600,1.22610,1.00,1.011310,1.00,-0.10
367,368,2025-08-27,SFP_BJ,"37,8,13,29,31,36",7.34530,58.078,603.64,8.74420,8.59350,1398.90,0.545562,1398.90,150.70
374,375,2025-08-29,SFP_BJ,23,1.23430,88.190,1158.74,1.29810,1.29110,63.80,1.070550,63.80,7.00
406,407,2025-09-12,SFP_BJ,13,1.19540,87.570,1153.48,1.20360,1.20210,8.20,1.065910,8.20,1.50
429,430,2025-09-26,SFP_BJ,7,1.21540,88.520,1119.17,1.21900,1.21830,3.60,1.030650,3.60,0.70
441,442,2025-10-04,SFP_BJ,48,1.23140,88.730,1081.82,1.29770,1.29150,66.30,0.993090,66.30,6.20
472,473,2025-10-10,SFP_BJ,32,1.21020,87.830,1141.43,1.22670,1.22600,16.50,1.053600,16.50,0.70
485,486,2025-12-04,SFP_BJ,20,1.19380,88.520,1122.37,1.19890,1.19810,5.10,1.033850,5.10,0.80
499,500,2026-02-07,SFP_BJ,8,1.24140,88.790,1143.46,1.24720,1.24600,5.80,1.054670,5.80,1.20
509,510,2026-03-08,SFP_BJ,25,1.23100,87.440,1131.04,1.23380,1.23340,2.80,1.043600,2.80,0.40
525,526,2026-04-11,SFP_BJ,39,1.23480,87.870,1122.36,1.40930,1.39500,174.50,1.034490,174.50,14.30
544,545,2026-05-11,SFP_BJ,46,1.23360,88.450,1143.06,1.37120,1.36320,137.60,1.054610,137.60,8.00
561,562,2026-06-13,SFP_BJ,47,1.23000,88.510,1116.70,1.23800,1.23700,8.00,1.028190,8.00,1.00
578,579,2026-07-10,SFP_BJ,58,1.21600,89.020,1126.49,1.22210,1.22090,6.10,1.037470,6.10,1.20
595,596,2026-07-31,SFP_BJ,29,1.23470,87.530,1106.06,2.57020,2.55980,1335.50,1.018530,1335.50,10.40
612,613,2026-08-06,SFP_BJ,FC16,1.23290,87.470,1135.19,1.73470,1.72910,501.80,1.047720,501.80,5.60

--- TSS Data for Site: SFP_Canyon_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
14,15,2024-10-12,SFP_Canyon_Cr,22,1.24600,88.36,1152.62,1.24900,1.24800,3.00,1.06426,3.00,1.00
26,27,2024-10-19,SFP_Canyon_Cr,15,1.21400,103.07,1130.51,1.21700,1.21600,3.00,1.02744,3.00,1.00
43,44,2024-11-03,SFP_Canyon_Cr,42,1.19300,101.22,1065.01,1.19930,1.19448,6.30,0.96379,6.30,4.82
62,63,2024-11-09,SFP_Canyon_Cr,53,1.21100,88.91,1144.09,1.21080,1.21022,-0.20,1.05518,-0.20,0.58
79,80,2024-11-24,SFP_Canyon_Cr,11,1.20881,88.46,1137.13,1.21528,1.21436,6.47,1.04867,6.47,0.92
94,95,2025-01-17,SFP_Canyon_Cr,58,1.21334,88.36,1126.74,1.21895,1.21649,5.61,1.03838,5.61,2.46
109,110,2025-01-30,SFP_Canyon_Cr,9,1.19365,87.46,1115.20,1.19501,1.19404,1.36,1.02774,1.36,0.97
124,125,2025-02-15,SFP_Canyon_Cr,7,1.21369,88.36,1141.91,1.22480,1.22148,11.11,1.05355,11.11,3.32
140,141,2025-03-02,SFP_Canyon_Cr,20,1.18713,88.32,1148.42,1.22394,1.22004,36.81,1.06010,36.81,3.90
152,153,2025-03-19,SFP_Canyon_Cr,6,1.22966,88.44,1119.97,1.23447,1.23343,4.81,1.03153,4.81,1.04
164,165,2025-03-30,SFP_Canyon_Cr,8,1.23238,88.55,1113.29,1.25168,1.25051,19.30,1.02474,19.30,1.17
177,178,2025-04-15,SFP_Canyon_Cr,1,1.21185,88.36,1151.81,1.23882,1.23741,26.97,1.06345,26.97,1.41
195,196,2025-04-28,SFP_Canyon_Cr,3,1.23833,88.44,1133.73,1.25607,1.25442,17.74,1.04529,17.74,1.65
213,214,2025-05-10,SFP_Canyon_Cr,13,1.19784,88.50,1137.44,1.25111,1.24572,53.27,1.04894,53.27,5.39
232,233,2025-05-27,SFP_Canyon_Cr,18,1.24295,87.84,1123.47,1.26972,1.26789,26.77,1.03563,26.77,1.83
251,252,2025-06-08,SFP_Canyon_Cr,9,1.19121,88.21,1146.64,1.20562,1.20363,14.41,1.05843,14.41,1.99
270,271,2025-06-22,SFP_Canyon_Cr,7,1.21068,87.87,1141.47,1.21315,1.21239,2.47,1.05360,2.47,0.76
290,291,2025-07-07,SFP_Canyon_Cr,59,1.21851,87.45,1129.90,1.22646,1.22531,7.95,1.04245,7.95,1.15
309,310,2025-07-21,SFP_Canyon_Cr,34,1.19284,89.38,1145.99,1.19494,1.19405,2.10,1.05661,2.10,0.89
328,329,2025-08-01,SFP_Canyon_Cr,18,1.24400,88.34,1084.70,1.24400,1.24700,0.00,0.99636,0.00,-3.00
347,348,2025-08-14,SFP_Canyon_Cr,54,1.20900,88.59,1148.32,1.21100,1.21000,2.00,1.05973,2.00,1.00
362,363,2025-08-27,SFP_Canyon_Cr,59,1.22640,57.78,604.07,1.30540,1.29590,79.00,0.54629,79.00,9.50
380,381,2025-08-29,SFP_Canyon_Cr,43,1.22980,88.51,1146.87,1.25990,1.25610,30.10,1.05836,30.10,3.80
398,399,2025-09-12,SFP_Canyon_Cr,59,1.22380,101.51,1158.76,1.22770,1.22610,3.90,1.05725,3.90,1.60
421,422,2025-09-26,SFP_Canyon_Cr,27,1.23560,87.47,1081.66,1.23830,1.23670,2.70,0.99419,2.70,1.60
447,448,2025-10-04,SFP_Canyon_Cr,40,1.24030,89.61,1115.18,1.25070,1.24910,10.40,1.02557,10.40,1.60
461,462,2025-10-10,SFP_Canyon_Cr,FC18,1.18490,88.20,1114.13,1.18820,1.18850,3.30,1.02593,3.30,-0.30
480,481,2025-12-04,SFP_Canyon_Cr,68,1.22760,88.46,1064.47,1.22970,1.22970,2.10,0.97601,2.10,0.00
494,495,2026-02-07,SFP_Canyon_Cr,HZ,1.20230,88.33,1164.74,1.20390,1.20330,1.60,1.07641,1.60,0.60
504,505,2026-03-08,SFP_Canyon_Cr,59,1.22580,87.97,1057.31,1.22790,1.22700,2.10,0.96934,2.10,0.90
520,521,2026-04-11,SFP_Canyon_Cr,7,1.21290,88.38,1165.60,1.29060,1.28270,77.70,1.07722,77.70,7.90
539,540,2026-05-11,SFP_Canyon_Cr,11,1.21910,88.99,1139.21,1.28290,1.27880,63.80,1.05022,63.80,4.10
553,554,2026-06-13,SFP_Canyon_Cr,FC17,1.22240,88.53,1130.53,1.22760,1.22650,5.20,1.04200,5.20,1.10
570,571,2026-07-10,SFP_Canyon_Cr,FC15,1.24190,87.46,1138.26,1.24490,1.24390,3.00,1.05080,3.00,1.00
587,588,2026-07-31,SFP_Canyon_Cr,34,1.18270,88.53,1116.02,2.00690,1.99830,824.20,1.02749,824.20,8.60
604,605,2026-08-06,SFP_Canyon_Cr,38,1.22570,89.61,1137.21,1.46050,1.45710,234.80,1.04760,234.80,3.40

--- TSS Data for Site: SFP_Chap ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
9,10,2024-10-12,SFP_Chap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,2024-10-19,SFP_Chap,10,1.21200,103.19,1121.86,1.21500,1.21400,3.00,1.01867,3.00,1.00
44,45,2024-11-04,SFP_Chap,37,1.21000,88.64,1139.50,1.21880,1.21068,8.80,1.05086,8.80,8.12
55,56,2024-11-09,SFP_Chap,49,1.21000,88.12,1130.00,1.21255,1.21184,2.55,1.04188,2.55,0.71
72,73,2024-11-24,SFP_Chap,8,1.22996,88.68,1136.98,1.23372,1.23261,3.76,1.04830,3.76,1.11
87,88,2025-01-17,SFP_Chap,14,1.20660,88.35,715.64,1.21031,1.20928,3.71,0.62729,3.71,1.03
102,103,2025-01-30,SFP_Chap,46,1.23101,87.83,920.00,1.23209,1.23167,1.08,0.83217,1.08,0.42
117,118,2025-02-15,SFP_Chap,14,1.20675,87.47,1089.64,1.21370,1.21233,6.95,1.00217,6.95,1.37
133,134,NaT,SFP_Chap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,149,2025-03-19,SFP_Chap,9,1.19051,87.48,1124.43,1.19770,1.19595,7.19,1.03695,7.19,1.75
160,161,2025-03-30,SFP_Chap,14,1.20318,88.45,1143.75,1.21837,1.21578,15.19,1.05530,15.19,2.59
173,174,2025-04-15,SFP_Chap,19,1.20229,88.45,1151.89,1.21678,1.21457,14.49,1.06344,14.49,2.21
191,192,2025-04-28,SFP_Chap,58,1.21148,87.83,1138.43,1.25432,1.25067,42.84,1.05060,42.84,3.65
209,210,2025-05-10,SFP_Chap,58,1.23682,88.44,1149.29,1.27844,1.25749,41.62,1.06085,41.62,20.95
228,229,2025-05-27,SFP_Chap,11,1.21625,88.43,1114.39,1.25804,1.25597,41.79,1.02596,41.79,2.07
247,248,2025-06-08,SFP_Chap,11,1.21298,88.36,1140.05,1.22463,1.22338,11.65,1.05169,11.65,1.25
266,267,2025-06-22,SFP_Chap,4,1.23207,87.47,1113.61,1.23682,1.23547,4.75,1.02614,4.75,1.35
285,286,2025-07-07,SFP_Chap,50,1.21594,87.50,1151.80,1.24049,1.23768,24.55,1.06430,24.55,2.81
304,305,2025-07-21,SFP_Chap,12,1.19515,87.50,1142.76,1.19861,1.19758,3.46,1.05526,3.46,1.03
323,324,2025-08-01,SFP_Chap,19,1.20700,87.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,343,2025-08-14,SFP_Chap,59,1.22600,88.03,1097.46,1.22600,1.22620,0.00,1.00943,0.00,-0.20
365,366,2025-08-27,SFP_Chap,48,1.23290,58.26,588.59,1.36870,1.35210,135.80,0.53033,135.80,16.60
376,377,2025-08-29,SFP_Chap,10,1.21460,89.00,1144.90,1.26630,1.25970,51.70,1.05590,51.70,6.60
404,405,2025-09-12,SFP_Chap,18,1.24210,88.34,NaN,1.24780,1.24680,5.70,NaN,5.70,1.00
427,428,2025-09-26,SFP_Chap,55,1.22670,88.51,1090.22,1.23020,1.22840,3.50,1.00171,3.50,1.80
443,444,2025-10-04,SFP_Chap,59,1.22620,88.20,1120.05,1.27640,1.27060,50.20,1.03185,50.20,5.80
470,471,2025-10-10,SFP_Chap,46,1.23260,89.00,1139.29,1.24340,1.24290,10.80,1.05029,10.80,0.50
483,484,2025-12-04,SFP_Chap,5,1.22310,88.36,1093.40,1.22690,1.22600,3.80,1.00504,3.80,0.90
497,498,2026-02-07,SFP_Chap,38,1.22850,88.38,1138.92,1.23140,1.23060,2.90,1.05054,2.90,0.80
507,508,2026-03-08,SFP_Chap,FC17,1.22200,89.00,1129.72,1.22320,1.22240,1.20,1.04072,1.20,0.80
523,524,2026-04-11,SFP_Chap,32,1.21030,88.72,1158.18,1.32470,1.31410,114.40,1.06946,114.40,10.60
542,543,2026-05-11,SFP_Chap,FC4,1.19170,87.87,1132.07,1.28460,1.27690,92.90,1.04420,92.90,7.70
559,560,2026-06-13,SFP_Chap,FC12,1.22180,87.83,1133.33,1.22780,1.22650,6.00,1.04550,6.00,1.30
576,577,2026-07-10,SFP_Chap,43,1.22880,88.21,1110.36,1.23330,1.23210,4.50,1.02215,4.50,1.20
593,594,2026-07-31,SFP_Chap,23,1.21930,87.45,1107.85,1.47120,1.46350,251.90,1.02040,251.90,7.70
610,611,2026-08-06,SFP_Chap,43,1.22470,88.36,1137.59,1.38370,1.37990,159.00,1.04923,159.00,3.80

--- TSS Data for Site: SFP_DW ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
5,6,2024-10-12,SFP_DW,20,1.19500,88.490,1156.48,1.19600,1.19400,1.00,1.067990,1.00,2.00
19,20,2024-10-19,SFP_DW,14,1.21200,102.420,1123.30,1.21500,1.21300,3.00,1.020880,3.00,2.00
49,50,2024-11-04,SFP_DW,43,1.22300,101.440,1091.72,1.23060,1.22174,7.60,0.990280,7.60,8.86
51,52,2024-11-09,SFP_DW,45,1.22300,88.790,1115.61,1.22771,1.22673,4.71,1.026820,4.71,0.98
68,69,2024-11-24,SFP_DW,22,1.23411,88.350,1137.70,1.24575,1.24357,11.64,1.049350,11.64,2.18
83,84,2025-01-17,SFP_DW,13,1.18881,88.360,1124.99,1.18921,1.18879,0.40,1.036630,0.40,0.42
98,99,2025-01-30,SFP_DW,6,1.23338,88.520,1161.60,1.23482,1.23414,1.44,1.073080,1.44,0.68
113,114,2025-02-15,SFP_DW,25,1.22826,88.410,1140.12,1.24042,1.23833,12.16,1.051710,12.16,2.09
129,130,2025-03-02,SFP_DW,13,1.19248,88.360,1138.82,1.20327,1.20161,10.79,1.050460,10.79,1.66
144,145,2025-03-19,SFP_DW,13,1.19247,88.520,1111.06,1.19563,1.19446,3.16,1.022540,3.16,1.17
156,157,2025-03-30,SFP_DW,20,1.18897,87.860,1129.93,1.21011,1.20605,21.14,1.042070,21.14,4.06
169,170,2025-04-15,SFP_DW,50,1.21478,88.520,1140.66,1.23038,1.22771,15.60,1.052140,15.60,2.67
187,188,2025-04-28,SFP_DW,17,1.22256,87.870,1124.32,1.28359,1.27662,61.03,1.036450,61.03,6.97
205,206,2025-05-10,SFP_DW,22,1.24201,87.450,1140.98,1.33674,1.32903,94.73,1.053530,94.73,7.71
224,225,2025-05-27,SFP_DW,12,1.19711,88.740,1125.86,1.24288,1.23997,45.77,1.037120,45.77,2.91
243,244,2025-06-08,SFP_DW,3,1.23319,89.000,1145.50,1.25015,1.24864,16.96,1.056500,16.96,1.51
262,263,2025-06-22,SFP_DW,9,1.19139,88.550,1152.43,1.19579,1.19472,4.40,1.063880,4.40,1.07
281,282,2025-07-07,SFP_DW,19,1.20219,88.380,1155.10,1.21849,1.21532,16.30,1.066720,16.30,3.17
300,301,2025-07-21,SFP_DW,2,1.22551,87.900,1152.45,1.22902,1.22756,3.51,1.064550,3.51,1.46
319,320,2025-08-01,SFP_DW,23,1.23000,88.400,1131.90,1.26300,1.25800,33.00,1.043500,33.00,5.00
338,339,2025-08-14,SFP_DW,33,1.23900,88.870,1126.54,1.24300,1.24310,4.00,1.037670,4.00,-0.10
369,370,2025-08-27,SFP_DW,"40,6,30,68",3.69790,57.163,592.81,4.39570,4.31310,697.80,0.535647,697.80,82.60
372,373,2025-08-29,SFP_DW,1,1.21710,87.640,1130.54,1.29590,1.28450,78.80,1.042900,78.80,11.40
408,409,2025-09-12,SFP_DW,48,1.23140,88.340,1146.89,1.23810,1.23650,6.70,1.058550,6.70,1.60
431,432,2025-09-26,SFP_DW,12,1.19940,88.460,1083.70,1.20350,1.20260,4.10,0.995240,4.10,0.90
439,440,2025-10-04,SFP_DW,47,1.22980,88.400,1107.13,1.31750,1.30740,87.70,1.018730,87.70,10.10
455,456,2025-10-10,SFP_DW,FC10,1.23870,87.460,1091.11,1.24970,1.24750,11.00,1.003650,11.00,2.20
487,488,2025-12-04,SFP_DW,13,1.19760,87.890,1114.74,1.20160,1.20090,4.00,1.026850,4.00,0.70
490,491,2026-02-07,SFP_DW,43,1.22750,88.440,1061.48,1.23050,1.22960,3.00,0.973040,3.00,0.90
511,512,2026-03-08,SFP_DW,R21,1.23970,87.840,1116.28,1.24240,1.24200,2.70,1.028440,2.70,0.40
527,528,2026-04-11,SFP_DW,37,1.21440,88.340,1133.67,1.33780,1.32420,123.40,1.045330,123.40,13.60
546,547,2026-05-11,SFP_DW,44,1.22520,88.510,1137.62,1.33380,1.32660,108.60,1.049110,108.60,7.20
563,564,2026-06-13,SFP_DW,R21,1.24100,87.970,1140.07,1.25080,1.24950,9.80,1.052100,9.80,1.30
580,581,2026-07-10,SFP_DW,FC26,1.21200,87.850,1120.90,1.21760,1.21580,5.60,1.033050,5.60,1.80
597,598,2026-07-31,SFP_DW,55,1.21010,88.860,1119.81,1.31470,1.30780,104.60,1.030950,104.60,6.90
614,615,2026-08-06,SFP_DW,FC27,1.23770,87.980,1116.23,1.28030,1.27480,42.60,1.028250,42.60,5.50

--- TSS Data for Site: SFP_DW_AM ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
530,531,2026-04-11,SFP_DW_AM,17,1.2229,88.51,1153.49,1.3333,1.3199,110.4,1.06498,110.4,13.4

--- TSS Data for Site: SFP_Staircase ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
357,358,2025-08-27,SFP_Staircase,"16,32,27,41",4.8741,57.94,597.88,5.7575,5.5978,883.4,0.53994,883.4,159.7

--- TSS Data for Site: SFP_Wapiti ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
29,30,2024-10-19,SFP_Wapiti,2,1.27000,101.07,1152.46,1.22900,1.22829,-41.00,1.05139,-41.00,0.71
33,34,2024-11-03,SFP_Wapiti,27,1.22700,88.73,1142.95,1.23120,1.22705,4.20,1.05422,4.20,4.15
65,66,2024-11-09,SFP_Wapiti,58,1.20700,88.31,1117.76,1.21005,1.20902,3.05,1.02945,3.05,1.03
127,128,2025-02-15,SFP_Wapiti,9,1.19565,88.36,1132.84,1.19638,1.19598,0.73,1.04448,0.73,0.40
184,185,2025-04-15,SFP_Wapiti,8,1.23314,88.44,1022.68,1.23553,1.23472,2.39,0.93424,2.39,0.81
202,203,2025-04-28,SFP_Wapiti,19,1.20614,88.39,1150.80,1.21133,1.21038,5.19,1.06241,5.19,0.95
219,220,2025-05-10,SFP_Wapiti,12,1.19851,88.46,1148.39,1.23501,1.23088,36.50,1.05993,36.50,4.13
238,239,2025-05-27,SFP_Wapiti,35,1.23364,88.38,1089.84,1.24797,1.24680,14.33,1.00146,14.33,1.17
257,258,2025-06-08,SFP_Wapiti,35,1.22946,87.89,1123.58,1.23689,1.21576,7.43,1.03569,7.43,21.13
276,277,2025-06-22,SFP_Wapiti,10,1.20896,88.73,1155.35,1.21142,1.21049,2.46,1.06662,2.46,0.93
296,297,2025-07-07,SFP_Wapiti,31,1.22157,88.45,1123.00,1.22559,1.22385,4.02,1.03455,4.02,1.74
315,316,2025-07-21,SFP_Wapiti,13,1.19374,88.74,1159.68,1.19508,1.19452,1.34,1.07094,1.34,0.56
334,335,2025-08-01,SFP_Wapiti,20,1.19300,88.46,1144.32,1.20500,1.19600,12.00,1.05586,12.00,9.00
353,354,2025-08-14,SFP_Wapiti,28,1.24000,89.13,1140.71,1.24200,1.24200,2.00,1.05158,2.00,0.00
359,360,2025-08-27,SFP_Wapiti,11,1.21800,58.19,576.71,1.27950,1.27170,61.50,0.51852,61.50,7.80
386,387,2025-08-29,SFP_Wapiti,29,1.25100,87.84,1148.58,1.27890,1.27520,27.90,1.06074,27.90,3.70
393,394,2025-09-12,SFP_Wapiti,20,1.19400,104.97,1138.68,1.19710,1.19640,3.10,1.03371,3.10,0.70
416,417,2025-09-26,SFP_Wapiti,1,1.21750,87.88,1119.34,1.22070,1.22020,3.20,1.03146,3.20,0.50
451,452,2025-10-04,SFP_Wapiti,18,1.24450,88.35,1106.54,1.25370,1.25240,9.20,1.01819,9.20,1.30
456,457,2025-10-10,SFP_Wapiti,FC13,1.20200,88.38,1068.99,1.20480,1.20480,2.80,0.98061,2.80,0.00
475,476,2025-12-04,SFP_Wapiti,9,1.19730,88.54,1121.15,1.20100,1.20010,3.70,1.03261,3.70,0.90
515,516,2026-04-11,SFP_Wapiti,FC20,1.25070,88.19,1113.59,1.31840,1.31210,67.70,1.02540,67.70,6.30
534,535,2026-05-11,SFP_Wapiti,FC10,1.23970,87.45,1142.85,1.28480,1.28100,45.10,1.05540,45.10,3.80
548,549,2026-06-13,SFP_Wapiti,1,1.20940,87.87,1157.55,1.21490,1.21390,5.50,1.06968,5.50,1.00
565,566,2026-07-10,SFP_Wapiti,RC15,1.23540,87.88,1090.31,1.23790,1.23640,2.50,1.00243,2.50,1.50
582,583,2026-07-31,SFP_Wapiti,HZ,1.18740,87.95,1124.17,1.34740,1.34120,160.00,1.03622,160.00,6.20
599,600,2026-08-06,SFP_Wapiti,25,1.22480,89.01,1074.28,1.30170,1.30020,76.90,0.98527,76.90,1.50

--- TSS Data for Site: SFP_Wolf_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
11,12,2024-10-12,SFP_Wolf_Cr,18,1.24300,88.230,1153.16,1.24400,1.243000,1.00,1.064930,1.00,1.000
24,25,2024-10-19,SFP_Wolf_Cr,9,1.19300,101.200,1140.83,1.19500,1.191000,2.00,1.039630,2.00,4.000
41,42,2024-11-03,SFP_Wolf_Cr,35,1.23000,88.710,1136.85,1.23560,1.232540,5.60,1.048140,5.60,3.060
60,61,2024-11-09,SFP_Wolf_Cr,54,1.20400,88.750,1143.00,1.20588,1.205110,1.88,1.054250,1.88,0.770
77,78,2024-11-24,SFP_Wolf_Cr,20,1.18578,88.330,1126.42,1.18904,1.187840,3.26,1.038090,3.26,1.200
92,93,2025-01-17,SFP_Wolf_Cr,7,1.21231,88.070,920.59,1.21761,1.216580,5.30,0.832520,5.30,1.030
107,108,2025-01-30,SFP_Wolf_Cr,14,1.20942,88.490,1162.20,1.23606,1.232780,26.64,1.073710,26.64,3.280
122,123,2025-02-15,SFP_Wolf_Cr,13,1.19522,88.480,1145.03,1.20021,1.198570,4.99,1.056550,4.99,1.640
138,139,2025-03-02,SFP_Wolf_Cr,4,1.23144,88.360,1146.14,1.24064,1.238330,9.20,1.057780,9.20,2.310
150,151,2025-03-19,SFP_Wolf_Cr,22,1.23731,87.800,1134.36,1.24189,1.240650,4.58,1.046560,4.58,1.240
162,163,2025-03-30,SFP_Wolf_Cr,51,1.18783,87.630,1134.69,1.20102,1.198990,13.19,1.047060,13.19,2.030
175,176,2025-04-15,SFP_Wolf_Cr,58,1.20979,88.380,1123.55,1.23004,1.226030,20.25,1.035170,20.25,4.010
193,194,2025-04-28,SFP_Wolf_Cr,9,1.19517,87.470,1136.03,1.24947,1.246210,54.30,1.048560,54.30,3.260
211,212,2025-05-10,SFP_Wolf_Cr,20,1.19346,88.490,1148.18,1.25481,1.247480,61.35,1.059690,61.35,7.330
230,231,2025-05-27,SFP_Wolf_Cr,9,1.19591,88.470,1134.29,1.23299,1.230820,37.08,1.045820,37.08,2.170
249,250,2025-06-08,SFP_Wolf_Cr,18,1.23829,88.330,1058.05,1.24964,1.247930,11.35,0.969720,11.35,1.710
268,269,2025-06-22,SFP_Wolf_Cr,14,1.26318,88.580,1142.44,1.20704,1.206011,-56.14,1.053860,-56.14,1.029
288,289,2025-07-07,SFP_Wolf_Cr,17,1.21837,88.580,1136.70,1.23367,1.231290,15.30,1.048120,15.30,2.380
307,308,2025-07-21,SFP_Wolf_Cr,25,1.22471,88.480,1098.77,1.22818,1.226850,3.47,1.010290,3.47,1.330
326,327,2025-08-01,SFP_Wolf_Cr,22,1.24300,88.510,1140.91,1.24400,1.247000,1.00,1.052400,1.00,-3.000
345,346,2025-08-14,SFP_Wolf_Cr,31,1.22800,88.670,1151.42,1.23300,1.231300,5.00,1.062750,5.00,1.700
364,365,2025-08-27,SFP_Wolf_Cr,45,1.23220,57.091,594.95,1.37440,1.357600,142.20,0.537859,142.20,16.800
378,379,2025-08-29,SFP_Wolf_Cr,2,1.23100,87.880,1104.77,1.29150,1.282800,60.50,1.016890,60.50,8.700
400,401,2025-09-12,SFP_Wolf_Cr,9,1.19720,101.560,1081.57,1.20260,1.201100,5.40,0.980010,5.40,1.500
423,424,2025-09-26,SFP_Wolf_Cr,23,1.23490,88.360,1092.88,1.23840,1.237800,3.50,1.004520,3.50,0.600
445,446,2025-10-04,SFP_Wolf_Cr,4,1.23810,87.830,1118.06,1.28630,1.280800,48.20,1.030230,48.20,5.500
463,464,2025-10-10,SFP_Wolf_Cr,49,1.22150,88.460,1114.79,1.23370,1.232900,12.20,1.026330,12.20,0.800
482,483,2025-12-04,SFP_Wolf_Cr,11,1.21690,87.840,1132.30,1.22180,1.221300,4.90,1.044460,4.90,0.500
495,496,2026-02-07,SFP_Wolf_Cr,31,1.22750,88.180,1113.90,1.23090,1.229700,3.40,1.025720,3.40,1.200
505,506,2026-03-08,SFP_Wolf_Cr,10,1.21570,88.500,1088.90,1.21670,1.216200,1.00,1.000400,1.00,0.500
522,523,2026-04-11,SFP_Wolf_Cr,23,1.23560,87.460,1153.40,1.38030,1.363500,144.70,1.065940,144.70,16.800
541,542,2026-05-11,SFP_Wolf_Cr,53,1.21790,88.330,1159.34,1.33280,1.324700,114.90,1.071010,114.90,8.100
555,556,2026-06-13,SFP_Wolf_Cr,49,1.21950,87.450,1112.98,1.22710,1.225700,7.60,1.025530,7.60,1.400
572,573,2026-07-10,SFP_Wolf_Cr,FC18,1.18510,88.290,1140.23,1.18900,1.188300,3.90,1.051940,3.90,0.700
589,590,2026-07-31,SFP_Wolf_Cr,6,1.22210,87.430,1126.54,1.66010,1.652000,438.00,1.039110,438.00,8.100
606,607,2026-08-06,SFP_Wolf_Cr,32,1.20560,88.340,1136.23,1.38600,1.382900,180.40,1.047890,180.40,3.100

--- TSS Data for Site: SH_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
1,2,2024-10-11,SH_Cr,26,1.21400,88.540,1133.87,1.23400,NaN,20.00,1.045330,20.00,NaN
15,16,2024-10-12,SH_Cr,23,1.23700,87.630,1147.85,1.24000,1.23791,3.00,1.060220,3.00,2.09
16,17,2024-10-13,SH_Cr,24,1.19900,88.810,1141.80,1.21800,NaN,19.00,1.052990,19.00,NaN
28,29,2024-10-19,SH_Cr,12,1.19600,101.430,1001.98,1.21400,1.21100,18.00,0.900550,18.00,3.00
35,36,2024-11-03,SH_Cr,29,1.24300,88.790,1120.02,1.25460,1.24751,11.60,1.031230,11.60,7.09
64,65,2024-11-09,SH_Cr,57,1.20400,88.590,1067.57,1.20766,1.20682,3.66,0.978980,3.66,0.84
81,82,2024-11-24,SH_Cr,9,1.18718,887.590,1126.84,1.23012,1.22715,42.94,0.239250,42.94,2.97
96,97,2025-01-17,SH_Cr,8,1.23723,88.230,1053.98,1.41141,1.40853,174.18,0.965750,174.18,2.88
111,112,2025-01-30,SH_Cr,5,1.21926,88.220,1124.90,1.23974,1.23806,20.48,1.036680,20.48,1.68
126,127,2025-02-15,SH_Cr,46,1.23171,88.110,737.44,1.25185,1.25060,20.14,0.649330,20.14,1.25
142,143,2025-03-02,SH_Cr,55,1.22181,88.430,1140.23,1.43265,1.42028,210.84,1.051800,210.84,12.37
154,155,2025-03-19,SH_Cr,58,1.20921,88.230,1133.60,1.22533,1.22314,16.12,1.045370,16.12,2.19
166,167,2025-03-30,SH_Cr,4,1.23196,88.380,1109.36,1.25098,1.23938,19.02,1.020980,19.02,11.60
179,180,2025-04-15,SH_Cr,6,1.23156,87.480,1133.55,1.38447,1.37621,152.91,1.046070,152.91,8.26
197,198,2025-04-28,SH_Cr,51,1.19431,87.450,1142.47,1.57037,1.55268,376.06,1.055020,376.06,17.69
215,216,2025-05-10,SH_Cr,9,1.19487,88.720,1162.66,2.18516,2.16329,990.29,1.073940,990.29,21.87
234,235,2025-05-27,SH_Cr,6,1.23593,88.670,1115.32,1.23861,1.23830,2.68,1.026650,2.68,0.31
253,254,2025-06-08,SH_Cr,7,1.21023,89.590,1058.81,1.21349,1.21217,3.26,0.969220,3.26,1.32
272,273,2025-06-22,SH_Cr,11,1.21373,88.240,1151.27,1.26332,1.25945,49.59,1.063030,49.59,3.87
292,293,2025-07-07,SH_Cr,1,1.21112,88.500,1126.00,1.57721,1.56832,366.09,1.037500,366.09,8.89
311,312,2025-07-21,SH_Cr,50,1.21641,89.620,1093.83,1.23924,1.23677,22.83,1.004210,22.83,2.47
330,331,2025-08-01,SH_Cr,15,1.21500,88.070,1072.33,1.25500,1.25200,40.00,0.984260,40.00,3.00
349,350,2025-08-14,SH_Cr,43,1.22800,88.930,1104.76,1.24300,1.23970,15.00,1.015830,15.00,3.30
360,361,2025-08-27,SH_Cr,49,1.22280,57.887,573.18,1.23980,1.23610,17.00,0.515293,17.00,3.70
382,383,2025-08-29,SH_Cr,27,1.23350,88.730,1152.67,1.24180,1.23980,8.30,1.063940,8.30,2.00
395,396,2025-09-12,SH_Cr,28,1.23940,103.180,1089.71,1.24600,1.24440,6.60,0.986530,6.60,1.60
418,419,2025-09-26,SH_Cr,6,1.23710,88.280,1048.12,1.24430,1.24250,7.20,0.959840,7.20,1.80
448,449,2025-10-04,SH_Cr,39,1.23470,88.830,1088.59,1.32900,1.32310,94.30,0.999760,94.30,5.90
458,459,2025-10-10,SH_Cr,FC12,1.22050,88.060,1096.30,1.26050,1.25720,40.00,1.008240,40.00,3.30
477,478,2025-12-04,SH_Cr,FC10,1.23870,88.850,1077.43,1.24260,1.24190,3.90,0.988580,3.90,0.70
491,492,2026-02-07,SH_Cr,FC13,1.20090,87.440,1113.19,1.21250,1.21130,11.60,1.025750,11.60,1.20
501,502,2026-03-08,SH_Cr,FC18,1.18670,88.450,1089.31,1.18890,1.18800,2.20,1.000860,2.20,0.90
517,518,2026-04-11,SH_Cr,6,1.23560,88.990,1133.58,1.29620,1.28900,60.60,1.044590,60.60,7.20
536,537,2026-05-11,SH_Cr,5,1.22190,88.530,1074.72,1.49340,1.48060,271.50,0.986190,271.50,12.80
550,551,2026-06-13,SH_Cr,38,1.23060,87.560,1118.04,1.23420,1.23290,3.60,1.030480,3.60,1.30
567,568,2026-07-10,SH_Cr,41,1.19520,88.540,1073.92,1.19850,1.19750,3.30,0.985380,3.30,1.00
584,585,2026-07-31,SH_Cr,FC14,1.19950,88.330,1081.08,1.20130,1.20050,1.80,0.992750,1.80,0.80
601,602,2026-08-06,SH_Cr,FC17,1.21620,88.730,1100.74,1.21740,1.21700,1.20,1.012010,1.20,0.40

--- TSS Data for Site: Wapiti_Cr ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
66,67,2024-11-09,Wapiti_Cr,59,1.21300,88.08,1034.73,1.21914,1.21791,6.14,0.94665,6.14,1.23
185,186,2025-04-15,Wapiti_Cr,9,1.18968,88.70,1145.44,1.19419,1.19271,4.51,1.05674,4.51,1.48
203,204,2025-04-28,Wapiti_Cr,11,1.21706,87.63,1101.13,1.22485,1.22263,7.79,1.01350,7.79,2.22
220,221,2025-05-10,Wapiti_Cr,8,1.24071,89.64,1149.96,1.26535,1.25607,24.64,1.06032,24.64,9.28
239,240,2025-05-27,Wapiti_Cr,15,1.21751,88.51,1131.93,1.23264,1.22865,15.13,1.04342,15.13,3.99
258,259,2025-06-08,Wapiti_Cr,50,1.21544,88.59,1149.98,1.22131,1.21936,5.87,1.06139,5.87,1.95
277,278,2025-06-22,Wapiti_Cr,15,1.21230,87.95,1153.59,1.21647,1.21513,4.17,1.06564,4.17,1.34
297,298,2025-07-07,Wapiti_Cr,15,1.21122,88.25,1020.30,1.21546,1.21391,4.24,0.93205,4.24,1.55
316,317,2025-07-21,Wapiti_Cr,14,1.20592,89.06,1000.35,1.21112,1.20934,5.20,0.91129,5.20,1.78
335,336,2025-08-01,Wapiti_Cr,5,1.22100,89.61,1061.07,1.22200,1.22100,1.00,0.97146,1.00,1.00
354,355,2025-08-14,Wapiti_Cr,30,1.23100,88.65,1088.75,1.23500,1.23250,4.00,1.00010,4.00,2.50
387,388,2025-08-29,Wapiti_Cr,39,1.23440,88.35,1157.55,1.24110,1.23710,6.70,1.06920,6.70,4.00
392,393,2025-09-12,Wapiti_Cr,11,1.21600,102.53,1032.60,1.22170,1.21830,5.70,0.93007,5.70,3.40
452,453,2025-10-04,Wapiti_Cr,13,1.19790,87.47,1114.14,1.21120,1.20890,13.30,1.02667,13.30,2.30

--- TSS Data for Site: Warm_Sp ---

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
0,1,2024-10-11,Warm_Sp,19,1.20800,88.570,1135.00,1.20800,1.20500,0.00,1.046430,0.00,3.00
8,9,2024-10-12,Warm_Sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,2024-10-19,Warm_Sp,7,1.21700,100.990,1135.94,1.21400,1.21200,-3.00,1.034950,-3.00,2.00
46,47,2024-11-04,Warm_Sp,39,1.22900,87.870,1120.70,1.23600,1.23234,7.00,1.032830,7.00,3.66
54,55,2024-11-09,Warm_Sp,48,1.22200,88.590,1122.91,1.22274,1.22237,0.74,1.034320,0.74,0.37
71,72,2024-11-24,Warm_Sp,14,1.19937,88.320,1138.31,1.24092,1.23873,41.55,1.049990,41.55,2.19
86,87,2025-01-17,Warm_Sp,46,1.23195,87.440,1123.14,1.23693,1.23622,4.98,1.035700,4.98,0.71
101,102,2025-01-30,Warm_Sp,8,1.23845,88.330,1168.10,1.24267,1.24186,4.22,1.079770,4.22,0.81
116,117,2025-02-15,Warm_Sp,50,1.21766,88.710,1123.34,1.22059,1.21977,2.93,1.034630,2.93,0.82
132,133,2025-03-02,Warm_Sp,22,1.23651,88.400,1094.01,1.26331,1.26164,26.80,1.005610,26.80,1.67
147,148,2025-03-19,Warm_Sp,20,1.18929,87.630,1101.42,1.19518,1.19413,5.89,1.013790,5.89,1.05
159,160,2025-03-30,Warm_Sp,50,1.21494,88.330,1089.77,1.43392,1.43092,218.98,1.001440,218.98,3.00
172,173,2025-04-15,Warm_Sp,7,1.20955,88.500,1102.97,1.27461,1.27259,65.06,1.014470,65.06,2.02
190,191,2025-04-28,Warm_Sp,6,1.23573,88.230,1131.04,1.37904,1.37575,143.31,1.042810,143.31,3.29
208,209,2025-05-10,Warm_Sp,15,1.21667,88.400,1162.06,1.57770,1.56572,361.03,1.073660,361.03,11.98
227,228,2025-05-27,Warm_Sp,55,1.22604,88.360,1112.69,1.31552,1.31479,89.48,1.024330,89.48,0.73
246,247,2025-06-08,Warm_Sp,46,1.22823,87.690,1140.38,1.23560,1.23275,7.37,1.052690,7.37,2.85
265,266,2025-06-22,Warm_Sp,17,1.21857,88.380,1142.61,1.21999,1.21943,1.42,1.054230,1.42,0.56
284,285,2025-07-07,Warm_Sp,11,1.21253,87.650,1155.70,1.21803,1.21697,5.50,1.068050,5.50,1.06
303,304,2025-07-21,Warm_Sp,9,1.19159,88.360,1146.78,1.19519,1.19424,3.60,1.058420,3.60,0.95
322,323,2025-08-01,Warm_Sp,2,1.22600,88.530,1116.34,1.22600,1.22500,0.00,1.027810,0.00,1.00
341,342,2025-08-14,Warm_Sp,50,1.21900,89.540,1121.45,1.22000,1.22060,1.00,1.031910,1.00,-0.60
366,367,2025-08-27,Warm_Sp,"28,47,20",3.66840,58.189,590.95,4.06790,4.03150,399.50,0.532761,399.50,36.40
375,376,2025-08-29,Warm_Sp,32,1.21250,88.390,1147.76,1.29090,1.28250,78.40,1.059370,78.40,8.40
405,406,2025-09-12,Warm_Sp,46,1.23330,88.730,1157.88,1.24370,1.24100,10.40,1.069150,10.40,2.70
428,429,2025-09-26,Warm_Sp,10,1.21520,88.360,1108.05,1.22020,1.21890,5.00,1.019690,5.00,1.30
442,443,2025-10-04,Warm_Sp,20,1.19500,88.460,1116.93,1.25880,1.25490,63.80,1.028470,63.80,3.90
471,472,2025-10-10,Warm_Sp,31,1.22650,87.910,1112.58,1.24330,1.24190,16.80,1.024670,16.80,1.40
484,485,2025-12-04,Warm_Sp,48,1.23220,87.450,1091.36,1.23960,1.23890,7.40,1.003910,7.40,0.70
498,499,2026-02-07,Warm_Sp,58,1.21720,87.870,1140.60,1.22350,1.22320,6.30,1.052730,6.30,0.30
508,509,2026-03-08,Warm_Sp,14,1.20930,87.460,1124.12,1.21260,1.21190,3.30,1.036660,3.30,0.70
524,525,2026-04-11,Warm_Sp,1,1.21700,88.500,1138.09,1.43660,1.42720,219.60,1.049590,219.60,9.40
543,544,2026-05-11,Warm_Sp,48,1.23170,87.970,1139.53,1.52400,1.51760,292.30,1.051560,292.30,6.40
560,561,2026-06-13,Warm_Sp,FC13,1.20180,89.610,1139.92,1.20570,1.20530,3.90,1.050310,3.90,0.40
577,578,2026-07-10,Warm_Sp,10,1.21500,88.360,1142.65,1.22100,1.22020,6.00,1.054290,6.00,0.80
594,595,2026-07-31,Warm_Sp,39,1.21840,88.440,1098.37,1.21980,1.21960,1.40,1.009930,1.40,0.20
611,612,2026-08-06,Warm_Sp,31,1.22080,88.210,1139.28,1.22170,1.22160,0.90,1.051070,0.90,0.10

In [22]:
# drop the entire site if a TSS column is missing data
tss_df_complete = tss_df.dropna(subset=tss_cols)

In [23]:
# For each site show the number of dates, the number of bottles, and the min sediment weight
# A mismatch between date count and sitecount means that site may have been visited but no bottles collected?
summary = tss_df.groupby("site").agg({
    'date': 'count',
    'site': 'count',
    'susp_sed_mg': 'min'
})
display(summary)

                              date  site  susp_sed_mg
site
Avalanche_Cr                    27    28       -2.000
BJ_Cr                           37    37        0.820
Bear_Cr                         20    20        0.000
Camp_Cr                         35    35        0.400
Canyon_Cr_Banner                 4     4       -0.200
Canyon_Cr_DF2                    2     2        1.800
Canyon_Cr_DF4                    2     2        1.000
Canyon_Cr_DF5                    3     3        0.700
Canyon_Cr_DF8                    2     2        1.500
Canyon_Cr_DF_1                   1     1     -106.500
Canyon_Cr_DF_3                   1     1       53.700
Canyon_Cr_SFP                   37    37        0.300
Canyon_Cr_slump1                 3     3        0.900
Canyon_cr_avalanche (HP_old)     2     2        3.000
Chapman_Cr                       7     7       -4.000
Flat_Cr                          4     4       -5.143
Fox_Cr                          36    36        0.600
GO_Cr                           24    26        0.600
HP                              26    27       -3.000
MFP_Crouch                       1     1        3.100
MainPayette_Gauge                1     1        7.800
Nutcracker_Cr                    3     3        0.540
SFP_Alder_Cr                    35    35        0.700
SFP_Alder_Cr_AM                  1     1        8.100
SFP_BJ                          36    36       -0.100
SFP_Canyon_Cr                   36    36       -3.000
SFP_Chap                        35    36       -0.200
SFP_DW                          36    36       -0.100
SFP_DW_AM                        1     1       13.400
SFP_Staircase                    1     1      159.700
SFP_Wapiti                      27    27        0.000
SFP_Wolf_Cr                     36    36       -3.000
SH_Cr                           38    38        0.310
Wapiti_Cr                       14    14        1.000
Warm_Sp                         37    37       -0.600

In [24]:
# check for negative values of suspended sediment
negative_tss = tss_df[tss_df['susp_sed_mg'] < 0]
# display records with negative TSS values
negative_tss

,sample_num,date,site,tin_num,tin_filter_weight,bottle_tare,bottle_full,tin_filter_sed_weight,tin_filter_sed_ashed_weight,sed_weight_mg,TSS_conc_mgL-1,susp_solids_mg,susp_sed_mg
278,279,2025-06-22,Flat_Cr,22,1.23853,89.61,1126.14,1.233997,1.23914,-4.533,1.03653,-4.533,-5.143
324,325,2025-08-01,Chapman_Cr,14,1.20800,87.45,1081.21,1.231000,1.23500,23.000,0.99376,23.000,-4.000
326,327,2025-08-01,SFP_Wolf_Cr,22,1.24300,88.51,1140.91,1.244000,1.24700,1.000,1.05240,1.000,-3.000
328,329,2025-08-01,SFP_Canyon_Cr,18,1.24400,88.34,1084.70,1.244000,1.24700,0.000,0.99636,0.000,-3.000
331,332,2025-08-01,HP,7,1.21400,88.57,1140.50,1.215000,1.21800,1.000,1.05193,1.000,-3.000
338,339,2025-08-14,SFP_DW,33,1.23900,88.87,1126.54,1.243000,1.24310,4.000,1.03767,4.000,-0.100
340,341,2025-08-14,SFP_BJ,68,1.22500,88.22,1099.53,1.226000,1.22610,1.000,1.01131,1.000,-0.100
341,342,2025-08-14,Warm_Sp,50,1.21900,89.54,1121.45,1.220000,1.22060,1.000,1.03191,1.000,-0.600
342,343,2025-08-14,SFP_Chap,59,1.22600,88.03,1097.46,1.226000,1.22620,0.000,1.00943,0.000,-0.200
350,351,2025-08-14,HP,29,1.24700,88.07,1138.77,1.250000,1.25030,3.000,1.05070,3.000,-0.300
351,352,2025-08-14,Avalanche_Cr,27,1.23400,88.21,1111.92,1.235000,1.23700,1.000,1.02371,1.000,-2.000
390,391,2025-08-29,Canyon_Cr_DF_1,38,1.22970,105.86,1109.75,1.282000,1.38850,52.300,1.00389,52.300,-106.500
461,462,2025-10-10,SFP_Canyon_Cr,FC18,1.18490,88.20,1114.13,1.188200,1.18850,3.300,1.02593,3.300,-0.300
464,465,2025-10-10,Canyon_Cr_Banner,R21,1.23850,88.83,1101.57,1.242400,1.24260,3.900,1.01274,3.900,-0.200

In [25]:
# see the number of records for each site after dropping missing TSS values
counts = tss_df.groupby("site").size().sort_values(ascending=False)
print(counts)

site
SH_Cr                           38
Canyon_Cr_SFP                   37
BJ_Cr                           37
Warm_Sp                         37
SFP_Canyon_Cr                   36
SFP_BJ                          36
Fox_Cr                          36
SFP_Chap                        36
SFP_Wolf_Cr                     36
SFP_DW                          36
SFP_Alder_Cr                    35
Camp_Cr                         35
Avalanche_Cr                    28
SFP_Wapiti                      27
HP                              27
GO_Cr                           26
Bear_Cr                         20
Wapiti_Cr                       14
Chapman_Cr                       7
Canyon_Cr_Banner                 4
Flat_Cr                          4
Nutcracker_Cr                    3
Canyon_Cr_slump1                 3
Canyon_Cr_DF5                    3
Canyon_Cr_DF2                    2
Canyon_Cr_DF4                    2
Canyon_Cr_DF8                    2
Canyon_cr_avalanche (HP_old)     2
Canyon_Cr_DF_3                   1
Canyon_Cr_DF_1                   1
MainPayette_Gauge                1
SFP_Alder_Cr_AM                  1
MFP_Crouch                       1
SFP_Staircase                    1
SFP_DW_AM                        1
dtype: int64

# This section has options to export the cleaned dataset.
Running the cells below will overwrite the existing file.

In [26]:
def export_csv(df: pd.DataFrame, data_name: str, save_path: str) -> None:
    """
    Export a DataFrame to a CSV file in the specified root path.

    Args:
        df (pd.DataFrame): The DataFrame to export.
        data_name (str): The name of the parameter or dataset being exported.
        e.g. 'All', 'TSS', 'DOC', 'ions', 'nutrients'.
        save_path (str): The root path where the CSV file will be saved.

    Returns:
        None
    """
    # get current date
    current_date = datetime.datetime.now().strftime("%Y%m%d")
    if data_name not in {'ALL','TSS', 'DOC', 'IONS', 'NUTRIENTS', 'FIELD_DATA'}:
      print('Invalid data_name. Use ALL, TSS, DOC, IONS, or NUTRIENTS')
      return
    else:
      df_name = f'wapiti_water_{data_name}_sample_data_CLEANED_{current_date}.csv'
      file_path = os.path.join(save_path, df_name)
      df.to_csv(file_path, index=False,na_rep='-9999')
      print(f"DataFrame saved to {file_path}")

In [27]:
# export the full dataset
export_csv(df=df, data_name='FIELD_DATA', save_path=out_path)

DataFrame saved to /content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC/wapiti_water_FIELD_DATA_sample_data_CLEANED_20260826.csv

In [28]:
# export the TSS dataset
export_csv(df=tss_df, data_name='TSS', save_path=out_path)

DataFrame saved to /content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC/wapiti_water_TSS_sample_data_CLEANED_20260826.csv

In [29]:
# export the Carbon dataset
export_csv(df=toc_df, data_name='DOC', save_path=out_path)

DataFrame saved to /content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC/wapiti_water_DOC_sample_data_CLEANED_20260826.csv

In [30]:
# export the combined dataset
export_csv(df=final_df, data_name='ALL', save_path=out_path)

DataFrame saved to /content/drive/Shareddrives/RAPID_Wapiti_project/water_samples_QC/wapiti_water_ALL_sample_data_CLEANED_20260826.csv